// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/add-to-cart` — registers only <usa-add-to-cart>: `import { defineAddToCart } from 'motionary/widgets/add-to-cart'; defineAddToCart();` */
export { defineAddToCart } from '../../components/widgets/add-to-cart';
export type { UsaAddToCartElement } from '../../components/widgets/add-to-cart';
