// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/badge-wall` — registers only <usa-badge-wall>: `import { defineBadgeWall } from 'motionary/widgets/badge-wall'; defineBadgeWall();` */
export { defineBadgeWall } from '../../components/widgets/badge-wall';
export type { UsaBadgeWallElement } from '../../components/widgets/badge-wall';
