// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/bar-chart` — registers only <usa-bar-chart>: `import { defineBarChart } from 'motionary/widgets/bar-chart'; defineBarChart();` */
export { defineBarChart } from '../../components/widgets/bar-chart';
export type { UsaBarChartElement } from '../../components/widgets/bar-chart';
