// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/bg-generator` — registers only <usa-bg-generator>: `import { defineBgGenerator } from 'motionary/widgets/bg-generator'; defineBgGenerator();` */
export { defineBgGenerator } from '../../components/widgets/bg-generator';
export type { UsaBgGeneratorElement } from '../../components/widgets/bg-generator';
