// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/carousel` — registers only <usa-carousel>: `import { defineCarousel } from 'motionary/widgets/carousel'; defineCarousel();` */
export { defineCarousel } from '../../components/widgets/carousel';
export type { UsaCarouselElement } from '../../components/widgets/carousel';
