// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/cart-drawer` — registers only <usa-cart-drawer>: `import { defineCartDrawer } from 'motionary/widgets/cart-drawer'; defineCartDrawer();` */
export { defineCartDrawer } from '../../components/widgets/cart-drawer';
export type { UsaCartDrawerElement } from '../../components/widgets/cart-drawer';
