// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/chapter-nav` — registers only <usa-chapter-nav>: `import { defineChapterNav } from 'motionary/widgets/chapter-nav'; defineChapterNav();` */
export { defineChapterNav } from '../../components/widgets/chapter-nav';
export type { UsaChapterNavElement } from '../../components/widgets/chapter-nav';
