// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/chat-composer` — registers only <usa-chat-composer>: `import { defineChatComposer } from 'motionary/widgets/chat-composer'; defineChatComposer();` */
export { defineChatComposer } from '../../components/widgets/chat-composer';
export type { UsaChatComposerElement } from '../../components/widgets/chat-composer';
