// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/clock-control` — registers only <usa-clock-control>: `import { defineClockControl } from 'motionary/widgets/clock-control'; defineClockControl();` */
export { defineClockControl } from '../../components/widgets/clock-control';
export type { UsaClockControlElement } from '../../components/widgets/clock-control';
