// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/code-export` — registers only <usa-code-export>: `import { defineCodeExport } from 'motionary/widgets/code-export'; defineCodeExport();` */
export { defineCodeExport } from '../../components/widgets/code-export';
export type { UsaCodeExportElement } from '../../components/widgets/code-export';
