// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/color-picker` — registers only <usa-color-picker>: `import { defineColorPicker } from 'motionary/widgets/color-picker'; defineColorPicker();` */
export { defineColorPicker } from '../../components/widgets/color-picker';
export type { UsaColorPickerElement } from '../../components/widgets/color-picker';
