// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/command-palette` — registers only <usa-command-palette>: `import { defineCommandPalette } from 'motionary/widgets/command-palette'; defineCommandPalette();` */
export { defineCommandPalette } from '../../components/widgets/command-palette';
export type { UsaCommandPaletteElement } from '../../components/widgets/command-palette';
