// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/compare` — registers only <usa-compare>: `import { defineCompare } from 'motionary/widgets/compare'; defineCompare();` */
export { defineCompare } from '../../components/widgets/compare';
export type { UsaCompareElement } from '../../components/widgets/compare';
