// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/countdown` — registers only <usa-countdown>: `import { defineCountdown } from 'motionary/widgets/countdown'; defineCountdown();` */
export { defineCountdown } from '../../components/widgets/countdown';
export type { UsaCountdownElement } from '../../components/widgets/countdown';
