// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/cube-gallery` — registers only <usa-cube-gallery>: `import { defineCubeGallery } from 'motionary/widgets/cube-gallery'; defineCubeGallery();` */
export { defineCubeGallery } from '../../components/widgets/cube-gallery';
export type { UsaCubeGalleryElement } from '../../components/widgets/cube-gallery';
