// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/date-picker` — registers only <usa-date-picker>: `import { defineDatePicker } from 'motionary/widgets/date-picker'; defineDatePicker();` */
export { defineDatePicker } from '../../components/widgets/date-picker';
export type { UsaDatePickerElement } from '../../components/widgets/date-picker';
