// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/disclosure` — registers only <usa-disclosure>: `import { defineDisclosure } from 'motionary/widgets/disclosure'; defineDisclosure();` */
export { defineDisclosure } from '../../components/widgets/disclosure';
export type { UsaDisclosureElement } from '../../components/widgets/disclosure';
