// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/dock` — registers only <usa-dock>: `import { defineDock } from 'motionary/widgets/dock'; defineDock();` */
export { defineDock } from '../../components/widgets/dock';
export type { UsaDockElement } from '../../components/widgets/dock';
