// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/dotlottie` — registers only <usa-dotlottie>: `import { defineDotLottie } from 'motionary/widgets/dotlottie'; defineDotLottie();` */
export { defineDotLottie } from '../../components/widgets/dotlottie';
