// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/equalizer` — registers only <usa-equalizer>: `import { defineEqualizer } from 'motionary/widgets/equalizer'; defineEqualizer();` */
export { defineEqualizer } from '../../components/widgets/equalizer';
export type { UsaEqualizerElement } from '../../components/widgets/equalizer';
