// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/festival-banner` — registers only <usa-festival-banner>: `import { defineFestivalBanner } from 'motionary/widgets/festival-banner'; defineFestivalBanner();` */
export { defineFestivalBanner } from '../../components/widgets/festival-banner';
export type { UsaFestivalBannerElement } from '../../components/widgets/festival-banner';
