// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/field` — registers only <usa-field>: `import { defineField } from 'motionary/widgets/field'; defineField();` */
export { defineField } from '../../components/widgets/field';
export type { UsaFieldElement } from '../../components/widgets/field';
