// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/file-drop` — registers only <usa-file-drop>: `import { defineFileDrop } from 'motionary/widgets/file-drop'; defineFileDrop();` */
export { defineFileDrop } from '../../components/widgets/file-drop';
export type { UsaFileDropElement } from '../../components/widgets/file-drop';
