// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/gauge` — registers only <usa-gauge>: `import { defineGauge } from 'motionary/widgets/gauge'; defineGauge();` */
export { defineGauge } from '../../components/widgets/gauge';
export type { UsaGaugeElement } from '../../components/widgets/gauge';
