// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/gen-art` — registers only <usa-gen-art>: `import { defineGenArt } from 'motionary/widgets/gen-art'; defineGenArt();` */
export { defineGenArt } from '../../components/widgets/gen-art';
export type { UsaGenArtElement } from '../../components/widgets/gen-art';
