// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/gesture-sticker` — registers only <usa-gesture-sticker>: `import { defineGestureSticker } from 'motionary/widgets/gesture-sticker'; defineGestureSticker();` */
export { defineGestureSticker } from '../../components/widgets/gesture-sticker';
export type { UsaGestureStickerElement } from '../../components/widgets/gesture-sticker';
