// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/gl-model` — registers only <usa-gl-model>: `import { defineGlModel } from 'motionary/widgets/gl-model'; defineGlModel();` */
export { defineGlModel } from '../../components/widgets/gl-model';
