// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/gl-scene` — registers only <usa-gl-scene>: `import { defineGlScene } from 'motionary/widgets/gl-scene'; defineGlScene();` */
export { defineGlScene } from '../../components/widgets/gl-scene';
export type { UsaGlSceneElement } from '../../components/widgets/gl-scene';
