// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/globe` — registers only <usa-globe>: `import { defineGlobe } from 'motionary/widgets/globe'; defineGlobe();` */
export { defineGlobe } from '../../components/widgets/globe';
export type { UsaGlobeElement } from '../../components/widgets/globe';
