// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/gpu-particles` — registers only <usa-gpu-particles>: `import { defineGpuParticles } from 'motionary/widgets/gpu-particles'; defineGpuParticles();` */
export { defineGpuParticles } from '../../components/widgets/gpu-particles';
export type { UsaGpuParticlesElement } from '../../components/widgets/gpu-particles';
