// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/gyro-card` — registers only <usa-gyro-card>: `import { defineGyroCard } from 'motionary/widgets/gyro-card'; defineGyroCard();` */
export { defineGyroCard } from '../../components/widgets/gyro-card';
export type { UsaGyroCardElement } from '../../components/widgets/gyro-card';
