// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/hero-video` — registers only <usa-hero-video>: `import { defineHeroVideo } from 'motionary/widgets/hero-video'; defineHeroVideo();` */
export { defineHeroVideo } from '../../components/widgets/hero-video';
export type { UsaHeroVideoElement } from '../../components/widgets/hero-video';
