// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/hud-panel` — registers only <usa-hud-panel>: `import { defineHudPanel } from 'motionary/widgets/hud-panel'; defineHudPanel();` */
export { defineHudPanel } from '../../components/widgets/hud-panel';
export type { UsaHudPanelElement } from '../../components/widgets/hud-panel';
