// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/hydrate` — registers only <usa-hydrate>: `import { defineHydrate } from 'motionary/widgets/hydrate'; defineHydrate();` */
export { defineHydrate } from '../../components/widgets/hydrate';
export type { UsaHydrateElement } from '../../components/widgets/hydrate';
