// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/install-button` — registers only <usa-install-button>: `import { defineInstallButton } from 'motionary/widgets/install-button'; defineInstallButton();` */
export { defineInstallButton } from '../../components/widgets/install-button';
export type { UsaInstallButtonElement } from '../../components/widgets/install-button';
