// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/kanban` — registers only <usa-kanban>: `import { defineKanban } from 'motionary/widgets/kanban'; defineKanban();` */
export { defineKanban } from '../../components/widgets/kanban';
export type { UsaKanbanElement } from '../../components/widgets/kanban';
