// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/keyframe-editor` — registers only <usa-keyframe-editor>: `import { defineKeyframeEditor } from 'motionary/widgets/keyframe-editor'; defineKeyframeEditor();` */
export { defineKeyframeEditor } from '../../components/widgets/keyframe-editor';
export type { UsaKeyframeEditorElement } from '../../components/widgets/keyframe-editor';
