// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/kpi` — registers only <usa-kpi>: `import { defineKpi } from 'motionary/widgets/kpi'; defineKpi();` */
export { defineKpi } from '../../components/widgets/kpi';
export type { UsaKpiElement } from '../../components/widgets/kpi';
