// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/leaderboard` — registers only <usa-leaderboard>: `import { defineLeaderboard } from 'motionary/widgets/leaderboard'; defineLeaderboard();` */
export { defineLeaderboard } from '../../components/widgets/leaderboard';
export type { UsaLeaderboardElement } from '../../components/widgets/leaderboard';
