// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/liquid-nav` — registers only <usa-liquid-nav>: `import { defineLiquidNav } from 'motionary/widgets/liquid-nav'; defineLiquidNav();` */
export { defineLiquidNav } from '../../components/widgets/liquid-nav';
export type { UsaLiquidNavElement } from '../../components/widgets/liquid-nav';
