// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/location-card` — registers only <usa-location-card>: `import { defineLocationCard } from 'motionary/widgets/location-card'; defineLocationCard();` */
export { defineLocationCard } from '../../components/widgets/location-card';
export type { UsaLocationCardElement } from '../../components/widgets/location-card';
