// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/lottie` — registers only <usa-lottie>: `import { defineLottie } from 'motionary/widgets/lottie'; defineLottie();` */
export { defineLottie } from '../../components/widgets/lottie';
export type { UsaLottieElement } from '../../components/widgets/lottie';
