// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/lottie-icon` — registers only <usa-lottie-icon>: `import { defineLottieIcon } from 'motionary/widgets/lottie-icon'; defineLottieIcon();` */
export { defineLottieIcon } from '../../components/widgets/lottie-icon';
export type { UsaLottieIconElement } from '../../components/widgets/lottie-icon';
