// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/lottie-player` — registers only <usa-lottie-player>: `import { defineLottiePlayer } from 'motionary/widgets/lottie-player'; defineLottiePlayer();` */
export { defineLottiePlayer } from '../../components/widgets/lottie-player';
export type { UsaLottiePlayerElement } from '../../components/widgets/lottie-player';
