// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/lyrics` — registers only <usa-lyrics>: `import { defineLyrics } from 'motionary/widgets/lyrics'; defineLyrics();` */
export { defineLyrics } from '../../components/widgets/lyrics';
export type { UsaLyricsElement } from '../../components/widgets/lyrics';
