// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/masonry-flow` — registers only <usa-masonry-flow>: `import { defineMasonryFlow } from 'motionary/widgets/masonry-flow'; defineMasonryFlow();` */
export { defineMasonryFlow } from '../../components/widgets/masonry-flow';
export type { UsaMasonryFlowElement } from '../../components/widgets/masonry-flow';
