// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/menu-toggle` — registers only <usa-menu-toggle>: `import { defineMenuToggle } from 'motionary/widgets/menu-toggle'; defineMenuToggle();` */
export { defineMenuToggle } from '../../components/widgets/menu-toggle';
export type { UsaMenuToggleElement } from '../../components/widgets/menu-toggle';
