// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/menu` — registers only <usa-menu>: `import { defineMenu } from 'motionary/widgets/menu'; defineMenu();` */
export { defineMenu } from '../../components/widgets/menu';
export type { UsaMenuElement } from '../../components/widgets/menu';
