// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/message-list` — registers only <usa-message-list>: `import { defineMessageList } from 'motionary/widgets/message-list'; defineMessageList();` */
export { defineMessageList } from '../../components/widgets/message-list';
export type { UsaMessageListElement } from '../../components/widgets/message-list';
