// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/milestones` — registers only <usa-milestones>: `import { defineMilestones } from 'motionary/widgets/milestones'; defineMilestones();` */
export { defineMilestones } from '../../components/widgets/milestones';
export type { UsaMilestonesElement } from '../../components/widgets/milestones';
