// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/modal` — registers only <usa-modal>: `import { defineModal } from 'motionary/widgets/modal'; defineModal();` */
export { defineModal } from '../../components/widgets/overlay';
export type { UsaModalElement, UsaSheetElement } from '../../components/widgets/overlay';
