// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/motion-prompt` — registers only <usa-motion-prompt>: `import { defineMotionPrompt } from 'motionary/widgets/motion-prompt'; defineMotionPrompt();` */
export { defineMotionPrompt } from '../../components/widgets/motion-prompt';
export type { UsaMotionPromptElement } from '../../components/widgets/motion-prompt';
