// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/motion-inspector` — registers only <usa-motion-inspector>: `import { defineMotionInspector } from 'motionary/widgets/motion-inspector'; defineMotionInspector();` */
export { defineMotionInspector } from '../../components/widgets/motion-inspector';
export type { UsaMotionInspectorElement } from '../../components/widgets/motion-inspector';
