// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/motion-spec` — registers only <usa-motion-spec>: `import { defineMotionSpec } from 'motionary/widgets/motion-spec'; defineMotionSpec();` */
export { defineMotionSpec } from '../../components/widgets/motion-spec';
export type { UsaMotionSpecElement } from '../../components/widgets/motion-spec';
