// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/motion-prefs` — registers only <usa-motion-prefs>: `import { defineMotionPrefs } from 'motionary/widgets/motion-prefs'; defineMotionPrefs();` */
export { defineMotionPrefs } from '../../components/widgets/motion-prefs';
export type { UsaMotionPrefsElement } from '../../components/widgets/motion-prefs';
