// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/motion` — registers only <usa-motion>: `import { defineMotion } from 'motionary/widgets/motion'; defineMotion();` */
export { defineMotion } from '../../components/widgets/motion';
export type { UsaMotionElement } from '../../components/widgets/motion';
