// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/music-player` — registers only <usa-music-player>: `import { defineMusicPlayer } from 'motionary/widgets/music-player'; defineMusicPlayer();` */
export { defineMusicPlayer } from '../../components/widgets/music-player';
export type { UsaMusicPlayerElement } from '../../components/widgets/music-player';
