// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/native-preview` — registers only <usa-native-preview>: `import { defineNativePreview } from 'motionary/widgets/native-preview'; defineNativePreview();` */
export { defineNativePreview } from '../../components/widgets/native-preview';
export type { UsaNativePreviewElement } from '../../components/widgets/native-preview';
