// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/nav-morph` — registers only <usa-nav-morph>: `import { defineNavMorph } from 'motionary/widgets/nav-morph'; defineNavMorph();` */
export { defineNavMorph } from '../../components/widgets/nav-morph';
export type { UsaNavMorphElement } from '../../components/widgets/nav-morph';
