// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/notification-bell` — registers only <usa-notification-bell>: `import { defineNotificationBell } from 'motionary/widgets/notification-bell'; defineNotificationBell();` */
export { defineNotificationBell } from '../../components/widgets/notification-bell';
export type { UsaNotificationBellElement } from '../../components/widgets/notification-bell';
