// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/odometer` — registers only <usa-odometer>: `import { defineOdometer } from 'motionary/widgets/odometer'; defineOdometer();` */
export { defineOdometer } from '../../components/widgets/meters';
export type { UsaProgressRingElement, UsaOdometerElement } from '../../components/widgets/meters';
