// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/organic-card` — registers only <usa-organic-card>: `import { defineOrganicCard } from 'motionary/widgets/organic-card'; defineOrganicCard();` */
export { defineOrganicCard } from '../../components/widgets/organic-card';
export type { UsaOrganicCardElement } from '../../components/widgets/organic-card';
