// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/otp` — registers only <usa-otp>: `import { defineOtp } from 'motionary/widgets/otp'; defineOtp();` */
export { defineOtp } from '../../components/widgets/otp';
export type { UsaOtpElement } from '../../components/widgets/otp';
