// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/pagination` — registers only <usa-pagination>: `import { definePagination } from 'motionary/widgets/pagination'; definePagination();` */
export { definePagination } from '../../components/widgets/pagination';
export type { UsaPaginationElement } from '../../components/widgets/pagination';
