// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/panorama` — registers only <usa-panorama>: `import { definePanorama } from 'motionary/widgets/panorama'; definePanorama();` */
export { definePanorama } from '../../components/widgets/panorama';
export type { UsaPanoramaElement } from '../../components/widgets/panorama';
