// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/parallax-layers` — registers only <usa-parallax-layers>: `import { defineParallaxLayers } from 'motionary/widgets/parallax-layers'; defineParallaxLayers();` */
export { defineParallaxLayers } from '../../components/widgets/parallax-layers';
export type { UsaParallaxLayersElement } from '../../components/widgets/parallax-layers';
