// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/pause-all` — registers only <usa-pause-all>: `import { definePauseAll } from 'motionary/widgets/pause-all'; definePauseAll();` */
export { definePauseAll } from '../../components/widgets/pause-all';
export type { UsaPauseAllElement } from '../../components/widgets/pause-all';
