// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/perf-monitor` — registers only <usa-perf-monitor>: `import { definePerfMonitor } from 'motionary/widgets/perf-monitor'; definePerfMonitor();` */
export { definePerfMonitor } from '../../components/widgets/perf-monitor';
export type { UsaPerfMonitorElement } from '../../components/widgets/perf-monitor';
