// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/physics-playground` — registers only <usa-physics-playground>: `import { definePhysicsPlayground } from 'motionary/widgets/physics-playground'; definePhysicsPlayground();` */
export { definePhysicsPlayground } from '../../components/widgets/physics-playground';
export type { UsaPhysicsPlaygroundElement } from '../../components/widgets/physics-playground';
