// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/plugin-card` — registers only <usa-plugin-card>: `import { definePluginCard } from 'motionary/widgets/plugin-card'; definePluginCard();` */
export { definePluginCard } from '../../components/widgets/plugin-card';
export type { UsaPluginCardElement } from '../../components/widgets/plugin-card';
