// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/plugin-store` — registers only <usa-plugin-store>: `import { definePluginStore } from 'motionary/widgets/plugin-store'; definePluginStore();` */
export { definePluginStore } from '../../components/widgets/plugin-store';
export type { UsaPluginStoreElement } from '../../components/widgets/plugin-store';
