// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/presence` — registers only <usa-presence>: `import { definePresence } from 'motionary/widgets/presence'; definePresence();` */
export { definePresence } from '../../components/widgets/presence';
export type { UsaPresenceElement } from '../../components/widgets/presence';
