// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/prize-wheel` — registers only <usa-prize-wheel>: `import { definePrizeWheel } from 'motionary/widgets/prize-wheel'; definePrizeWheel();` */
export { definePrizeWheel } from '../../components/widgets/prize-wheel';
export type { UsaPrizeWheelElement } from '../../components/widgets/prize-wheel';
