// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/product-gallery` — registers only <usa-product-gallery>: `import { defineProductGallery } from 'motionary/widgets/product-gallery'; defineProductGallery();` */
export { defineProductGallery } from '../../components/widgets/product-gallery';
export type { UsaProductGalleryElement } from '../../components/widgets/product-gallery';
