// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/progress-ring` — registers only <usa-progress-ring>: `import { defineProgressRing } from 'motionary/widgets/progress-ring'; defineProgressRing();` */
export { defineProgressRing } from '../../components/widgets/meters';
export type { UsaProgressRingElement, UsaOdometerElement } from '../../components/widgets/meters';
