// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/prop-panel` — registers only <usa-prop-panel>: `import { definePropPanel } from 'motionary/widgets/prop-panel'; definePropPanel();` */
export { definePropPanel } from '../../components/widgets/prop-panel';
export type { UsaPropPanelElement } from '../../components/widgets/prop-panel';
