// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/pull-cord` — registers only <usa-pull-cord>: `import { definePullCord } from 'motionary/widgets/pull-cord'; definePullCord();` */
export { definePullCord } from '../../components/widgets/pull-cord';
export type { UsaPullCordElement } from '../../components/widgets/pull-cord';
