// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/radar` — registers only <usa-radar>: `import { defineRadar } from 'motionary/widgets/radar'; defineRadar();` */
export { defineRadar } from '../../components/widgets/radar';
export type { UsaRadarElement } from '../../components/widgets/radar';
