// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/reactions` — registers only <usa-reactions>: `import { defineReactions } from 'motionary/widgets/reactions'; defineReactions();` */
export { defineReactions } from '../../components/widgets/reactions';
export type { UsaReactionsElement } from '../../components/widgets/reactions';
