// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/red-envelope` — registers only <usa-red-envelope>: `import { defineRedEnvelope } from 'motionary/widgets/red-envelope'; defineRedEnvelope();` */
export { defineRedEnvelope } from '../../components/widgets/red-envelope';
export type { UsaRedEnvelopeElement } from '../../components/widgets/red-envelope';
