// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/retro-button` — registers only <usa-retro-button>: `import { defineRetroButton } from 'motionary/widgets/retro-button'; defineRetroButton();` */
export { defineRetroButton } from '../../components/widgets/retro-button';
export type { UsaRetroButtonElement } from '../../components/widgets/retro-button';
