// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/rive` — registers only <usa-rive>: `import { defineRive } from 'motionary/widgets/rive'; defineRive();` */
export { defineRive } from '../../components/widgets/rive';
export type { UsaRiveElement } from '../../components/widgets/rive';
