// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/route-transition` — registers only <usa-route-transition>: `import { defineRouteTransition } from 'motionary/widgets/route-transition'; defineRouteTransition();` */
export { defineRouteTransition } from '../../components/widgets/route-transition';
export type { UsaRouteTransitionElement } from '../../components/widgets/route-transition';
