// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/scene` — registers only <usa-scene>: `import { defineScene } from 'motionary/widgets/scene'; defineScene();` */
export { defineScene } from '../../components/widgets/scene';
export type { UsaSceneElement } from '../../components/widgets/scene';
