// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/scroll-scene` — registers only <usa-scroll-scene>: `import { defineScrollScene } from 'motionary/widgets/scroll-scene'; defineScrollScene();` */
export { defineScrollScene } from '../../components/widgets/scroll-scene';
export type { UsaScrollSceneElement } from '../../components/widgets/scroll-scene';
