// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/scroll-ring` — registers only <usa-scroll-ring>: `import { defineScrollRing } from 'motionary/widgets/scroll-ring'; defineScrollRing();` */
export { defineScrollRing } from '../../components/widgets/scroll-ring';
export type { UsaScrollRingElement } from '../../components/widgets/scroll-ring';
