// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/segmented` — registers only <usa-segmented>: `import { defineSegmented } from 'motionary/widgets/segmented'; defineSegmented();` */
export { defineSegmented } from '../../components/widgets/segmented';
export type { UsaSegmentedElement } from '../../components/widgets/segmented';
