// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/shader-backdrop` — registers only <usa-shader-backdrop>: `import { defineShaderBackdrop } from 'motionary/widgets/shader-backdrop'; defineShaderBackdrop();` */
export { defineShaderBackdrop } from '../../components/widgets/shader-backdrop';
export type { UsaShaderBackdropElement } from '../../components/widgets/shader-backdrop';
