// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/sheet` — registers only <usa-sheet>: `import { defineSheet } from 'motionary/widgets/sheet'; defineSheet();` */
export { defineSheet } from '../../components/widgets/overlay';
export type { UsaModalElement, UsaSheetElement } from '../../components/widgets/overlay';
