// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/shortcut` — registers only <usa-shortcut>: `import { defineShortcut } from 'motionary/widgets/shortcut'; defineShortcut();` */
export { defineShortcut } from '../../components/widgets/shortcut';
export type { UsaShortcutElement } from '../../components/widgets/shortcut';
