// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/skeleton-reveal` — registers only <usa-skeleton-reveal>: `import { defineSkeletonReveal } from 'motionary/widgets/skeleton-reveal'; defineSkeletonReveal();` */
export { defineSkeletonReveal } from '../../components/widgets/skeleton-reveal';
export type { UsaSkeletonRevealElement } from '../../components/widgets/skeleton-reveal';
