// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/sketch-chart` — registers only <usa-sketch-chart>: `import { defineSketchChart } from 'motionary/widgets/sketch-chart'; defineSketchChart();` */
export { defineSketchChart } from '../../components/widgets/sketch-chart';
export type { UsaSketchChartElement } from '../../components/widgets/sketch-chart';
