// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/smooth-scroll` — registers only <usa-smooth-scroll>: `import { defineSmoothScroll } from 'motionary/widgets/smooth-scroll'; defineSmoothScroll();` */
export { defineSmoothScroll } from '../../components/widgets/smooth-scroll';
export type { UsaSmoothScrollElement } from '../../components/widgets/smooth-scroll';
