// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/snap-carousel` — registers only <usa-snap-carousel>: `import { defineSnapCarousel } from 'motionary/widgets/snap-carousel'; defineSnapCarousel();` */
export { defineSnapCarousel } from '../../components/widgets/snap-carousel';
