// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/sparkline` — registers only <usa-sparkline>: `import { defineSparkline } from 'motionary/widgets/sparkline'; defineSparkline();` */
export { defineSparkline } from '../../components/widgets/sparkline';
export type { UsaSparklineElement } from '../../components/widgets/sparkline';
