// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/spatial-card` — registers only <usa-spatial-card>: `import { defineSpatialCard } from 'motionary/widgets/spatial-card'; defineSpatialCard();` */
export { defineSpatialCard } from '../../components/widgets/spatial-card';
export type { UsaSpatialCardElement } from '../../components/widgets/spatial-card';
