// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/star-rating` — registers only <usa-star-rating>: `import { defineStarRating } from 'motionary/widgets/star-rating'; defineStarRating();` */
export { defineStarRating } from '../../components/widgets/star-rating';
export type { UsaStarRatingElement } from '../../components/widgets/star-rating';
