// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/stepper` — registers only <usa-stepper>: `import { defineStepper } from 'motionary/widgets/stepper'; defineStepper();` */
export { defineStepper } from '../../components/widgets/stepper';
export type { UsaStepperElement } from '../../components/widgets/stepper';
