// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/sticky-wall` — registers only <usa-sticky-wall>: `import { defineStickyWall } from 'motionary/widgets/sticky-wall'; defineStickyWall();` */
export { defineStickyWall } from '../../components/widgets/sticky-wall';
export type { UsaStickyWallElement } from '../../components/widgets/sticky-wall';
