// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/stories` — registers only <usa-stories>: `import { defineStories } from 'motionary/widgets/stories'; defineStories();` */
export { defineStories } from '../../components/widgets/stories';
export type { UsaStoriesElement } from '../../components/widgets/stories';
