// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/suggestion-chips` — registers only <usa-suggestion-chips>: `import { defineSuggestionChips } from 'motionary/widgets/suggestion-chips'; defineSuggestionChips();` */
export { defineSuggestionChips } from '../../components/widgets/suggestion-chips';
export type { UsaSuggestionChipsElement } from '../../components/widgets/suggestion-chips';
