// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/swipe-deck` — registers only <usa-swipe-deck>: `import { defineSwipeDeck } from 'motionary/widgets/swipe-deck'; defineSwipeDeck();` */
export { defineSwipeDeck } from '../../components/widgets/swipe-deck';
export type { UsaSwipeDeckElement } from '../../components/widgets/swipe-deck';
