// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/switch` — registers only <usa-switch>: `import { defineSwitch } from 'motionary/widgets/switch'; defineSwitch();` */
export { defineSwitch } from '../../components/widgets/switch';
export type { UsaSwitchElement } from '../../components/widgets/switch';
