// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/tab-bar` — registers only <usa-tab-bar>: `import { defineTabBar } from 'motionary/widgets/tab-bar'; defineTabBar();` */
export { defineTabBar } from '../../components/widgets/tab-bar';
export type { UsaTabBarElement } from '../../components/widgets/tab-bar';
