// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/terminal` — registers only <usa-terminal>: `import { defineTerminal } from 'motionary/widgets/terminal'; defineTerminal();` */
export { defineTerminal } from '../../components/widgets/terminal';
export type { UsaTerminalElement } from '../../components/widgets/terminal';
