// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/text-splitter` — registers only <usa-text-splitter>: `import { defineTextSplitter } from 'motionary/widgets/text-splitter'; defineTextSplitter();` */
export { defineTextSplitter } from '../../components/widgets/text-splitter';
export type { UsaTextSplitterElement } from '../../components/widgets/text-splitter';
