// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/theme-surface` — registers only <usa-theme-surface>: `import { defineThemeSurface } from 'motionary/widgets/theme-surface'; defineThemeSurface();` */
export { defineThemeSurface } from '../../components/widgets/theme-surface';
export type { UsaThemeSurfaceElement } from '../../components/widgets/theme-surface';
