// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/theme-switcher` — registers only <usa-theme-switcher>: `import { defineThemeSwitcher } from 'motionary/widgets/theme-switcher'; defineThemeSwitcher();` */
export { defineThemeSwitcher } from '../../components/widgets/theme-switcher';
export type { UsaThemeSwitcherElement } from '../../components/widgets/theme-switcher';
