// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/three-scene` — registers only <usa-three-scene>: `import { defineThreeScene } from 'motionary/widgets/three-scene'; defineThreeScene();` */
export { defineThreeScene } from '../../components/widgets/gl-scene';
export type { UsaGlSceneElement } from '../../components/widgets/gl-scene';
