// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/tip` — registers only <usa-tip>: `import { defineTip } from 'motionary/widgets/tip'; defineTip();` */
export { defineTip } from '../../components/widgets/tip';
export type { UsaTipElement } from '../../components/widgets/tip';
