// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/toast-stack` — registers only <usa-toast-stack>: `import { defineToastStack } from 'motionary/widgets/toast-stack'; defineToastStack();` */
export { defineToastStack } from '../../components/widgets/toast';
export type { UsaToastStackElement } from '../../components/widgets/toast';
