// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/token-editor` — registers only <usa-token-editor>: `import { defineTokenEditor } from 'motionary/widgets/token-editor'; defineTokenEditor();` */
export { defineTokenEditor } from '../../components/widgets/token-editor';
export type { UsaTokenEditorElement } from '../../components/widgets/token-editor';
