// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/upload-progress` — registers only <usa-upload-progress>: `import { defineUploadProgress } from 'motionary/widgets/upload-progress'; defineUploadProgress();` */
export { defineUploadProgress } from '../../components/widgets/upload-progress';
export type { UsaUploadProgressElement } from '../../components/widgets/upload-progress';
