// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/video-card` — registers only <usa-video-card>: `import { defineVideoCard } from 'motionary/widgets/video-card'; defineVideoCard();` */
export { defineVideoCard } from '../../components/widgets/video-card';
export type { UsaVideoCardElement } from '../../components/widgets/video-card';
