// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/voice-button` — registers only <usa-voice-button>: `import { defineVoiceButton } from 'motionary/widgets/voice-button'; defineVoiceButton();` */
export { defineVoiceButton } from '../../components/widgets/voice-button';
export type { UsaVoiceButtonElement } from '../../components/widgets/voice-button';
