// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/volume-knob` — registers only <usa-volume-knob>: `import { defineVolumeKnob } from 'motionary/widgets/volume-knob'; defineVolumeKnob();` */
export { defineVolumeKnob } from '../../components/widgets/volume-knob';
export type { UsaVolumeKnobElement } from '../../components/widgets/volume-knob';
