// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/weather-card` — registers only <usa-weather-card>: `import { defineWeatherCard } from 'motionary/widgets/weather-card'; defineWeatherCard();` */
export { defineWeatherCard } from '../../components/widgets/weather-card';
export type { UsaWeatherCardElement } from '../../components/widgets/weather-card';
