// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/worker-canvas` — registers only <usa-worker-canvas>: `import { defineWorkerCanvas } from 'motionary/widgets/worker-canvas'; defineWorkerCanvas();` */
export { defineWorkerCanvas } from '../../components/widgets/worker-canvas';
export type { UsaWorkerCanvasElement } from '../../components/widgets/worker-canvas';
