// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/widgets/xp-bar` — registers only <usa-xp-bar>: `import { defineXpBar } from 'motionary/widgets/xp-bar'; defineXpBar();` */
export { defineXpBar } from '../../components/widgets/xp-bar';
export type { UsaXpBarElement } from '../../components/widgets/xp-bar';
