// 12.3: Figma export — tokens + runnable component snippets from the plugin.
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';

const read = (f: string) => readFileSync(f, 'utf8');
const load = () => { const module: any = { exports: {} }; new Function('module', read('figma-plugin/code.js'))(module); return module.exports; };

describe('12.3 Figma plugin', () => {
  it('code.js is generated from plugin-src.js and current', async () => {
    const { generate } = await import('../scripts/gen-figma-plugin.mjs');
    for (const [f, s] of Object.entries(generate() as Record<string, string>)) expect(read(f), f).toBe(s);
    expect(read('figma-plugin/code.js')).toContain('GENERATED by scripts/gen-figma-plugin.mjs');
    const man = JSON.parse(read('figma-plugin/manifest.json'));
    expect(man.main).toBe('code.js');
    expect(man.networkAccess).toEqual({ allowedDomains: ['none'] });
  });
  it('catalog matches the manifest; CDN major is the package major', async () => {
    const { buildManifest } = await import('../scripts/gen-manifest.mjs');
    const m = buildManifest(), x = load();
    expect(x.MOTIONARY_MAJOR).toBe(String(m.version).split('.')[0]);
    expect(Object.keys(x.CATALOG).length).toBe(m.components.length);
    const snap = m.components.find((c: any) => c.tag === 'usa-snap-carousel');
    expect(x.CATALOG['usa-snap-carousel'].r).toEqual(snap.requires);
    expect(x.CATALOG['usa-rive'].p).toEqual(['rive']);
  });
  it('tokens: defaults, Figma variables override and extend, CSS', () => {
    const x = load();
    const d = x.variablesToTokens([]);
    expect(d.motion.duration.normal.$value).toBe('300ms');
    const t = x.variablesToTokens([{ name: 'motion/duration/fast', value: 120 }, { name: 'Motion / Easing / Brand', value: 'cubic-bezier(0.1, 0.2, 0.3, 1)' }, { name: 'color/primary', value: '#fff' }]);
    expect(t.motion.duration.fast.$value).toBe('120ms');
    expect(t.motion.easing.brand).toEqual({ $type: 'cubicBezier', $value: [0.1, 0.2, 0.3, 1] });
    expect(t.$extensions['com.motionary'].fromFigmaVariables).toBe(2);
    const css = x.tokensToCss(t);
    expect(css).toContain('--usa-duration-fast: 120ms;');
    expect(css).toContain('--usa-easing-brand: cubic-bezier(0.1, 0.2, 0.3, 1);');
    expect(css).toContain('--usa-duration-normal: 300ms;');
  });
  it('layers → elements → a runnable page with prerequisites first', () => {
    const x = load();
    const r = x.exportSelection([
      { name: 'Card / usa-tilt', componentProperties: { max: { value: '12' }, Glare: { value: true }, bogus: { value: '1' } }, children: [{ characters: 'Card' }], reactions: [{ trigger: { type: 'ON_HOVER' }, action: { transition: { type: 'DISSOLVE', duration: 0.4, easing: { type: 'EASE_OUT' } } } }] },
      { name: '<usa-snap-carousel>' },
      { name: 'usa-nope' },
      { name: 'Plain frame' },
    ], []);
    const M = x.MOTIONARY_MAJOR;
    expect(r.html).toContain('<usa-tilt max="12" glare data-motion="hover: fade 400ms ease-out">Card</usa-tilt>');
    expect(r.html).toContain('<usa-snap-carousel></usa-snap-carousel>');
    expect(r.html).toContain('<div>Plain frame</div>');
    const core = r.html.indexOf(`motionary@${M}/dist/runtime.iife.js`), mod = r.html.indexOf(`motionary@${M}/dist/runtime/drag-snap.iife.js`), comp = r.html.search(/motionary@\d+\/dist\/(components|widgets)\.umd\.js/);
    expect(core).toBeGreaterThan(-1);
    expect(core).toBeLessThan(mod);
    expect(mod).toBeLessThan(comp);
    expect(r.html).toContain('applyMotion()');
    expect(r.rows.find((w: any) => w.tag === 'usa-nope').known).toBe(false);
    expect(r.html.startsWith('<!doctype html>')).toBe(true);
  });
  it('docs', () => {
    expect(read('figma-plugin/README.md')).toContain('HTML page');
    expect(read('README.md')).toContain('figma-plugin/README.md');
    expect(read('figma-plugin/ui.html')).toContain("execCommand('copy')");
  });
});
