// Generated by motionary/native (9.8) from: enter: fade-up; click: pop
import React, { useEffect, useRef } from 'react';
import { Animated, Easing, Pressable, AccessibilityInfo } from 'react-native';

export function MotionView({ children, index = 0, onPress }) {
  const t = useRef(new Animated.Value(0)).current;
  const s = useRef(new Animated.Value(1)).current;
  useEffect(() => {
    AccessibilityInfo.isReduceMotionEnabled().then((reduce) => {
      if (reduce) return t.setValue(1);
      Animated.timing(t, { toValue: 1, duration: 500, delay: 0 + index * 80, easing: Easing.bezier(0.22, 1, 0.36, 1), useNativeDriver: true }).start();
    });
  }, []);
  const style = {
    opacity: t.interpolate({ inputRange: [0, 1], outputRange: [0, 1] }),
    transform: [
      { translateX: t.interpolate({ inputRange: [0, 1], outputRange: [0, 0] }) },
      { translateY: t.interpolate({ inputRange: [0, 1], outputRange: [24, 0] }) },
      { scale: Animated.multiply(s, t.interpolate({ inputRange: [0, 1], outputRange: [1, 1] })) },
    ],
  };
  const pressIn = () => Animated.spring(s, { toValue: 0.92, stiffness: 300, damping: 30, useNativeDriver: true }).start();
  const pressOut = () => Animated.spring(s, { toValue: 1, stiffness: 260, damping: 12, useNativeDriver: true }).start();
  return (
    <Pressable onPressIn={pressIn} onPressOut={pressOut} onPress={onPress}>
      <Animated.View style={style}>{children}</Animated.View>
    </Pressable>
  );
}
