// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/achievement-unlock` — the `achievement-unlock` effect alone (game pack): `import { registerAchievementUnlock } from 'motionary/effects/achievement-unlock'; registerAchievementUnlock();` then <usa-fx effect="achievement-unlock"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GAME_FX } from '../../components/fx2/game';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ GAME_FX.find((d) => d.name === 'achievement-unlock')!;
/** Register only this effect (idempotent). */
export function registerAchievementUnlock(): void {
  registerEffects([effect]);
}
export { registerAchievementUnlock as register };
