// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/aurora-veil` — the `aurora-veil` effect alone (weather pack): `import { registerAuroraVeil } from 'motionary/effects/aurora-veil'; registerAuroraVeil();` then <usa-fx effect="aurora-veil"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { WEATHER_FX } from '../../components/fx2/weather';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ WEATHER_FX.find((d) => d.name === 'aurora-veil')!;
/** Register only this effect (idempotent). */
export function registerAuroraVeil(): void {
  registerEffects([effect]);
}
export { registerAuroraVeil as register };
