// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/badge-pop` — the `badge-pop` effect alone (shop pack): `import { registerBadgePop } from 'motionary/effects/badge-pop'; registerBadgePop();` then <usa-fx effect="badge-pop"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SHOP_FX } from '../../components/fx2/shop';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ SHOP_FX.find((d) => d.name === 'badge-pop')!;
/** Register only this effect (idempotent). */
export function registerBadgePop(): void {
  registerEffects([effect]);
}
export { registerBadgePop as register };
