// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/bars-grow` — the `bars-grow` effect alone (chart pack): `import { registerBarsGrow } from 'motionary/effects/bars-grow'; registerBarsGrow();` then <usa-fx effect="bars-grow"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { CHART_FX } from '../../components/fx2/chart';

/** The effect definition. */
export const effect: EffectDefinition = CHART_FX.find((d) => d.name === 'bars-grow')!;
/** Register only this effect (idempotent). */
export function registerBarsGrow(): void {
  registerEffects([effect]);
}
export { registerBarsGrow as register };
