// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/beat-bounce` — the `beat-bounce` effect alone (music pack): `import { registerBeatBounce } from 'motionary/effects/beat-bounce'; registerBeatBounce();` then <usa-fx effect="beat-bounce"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { MUSIC_FX } from '../../components/fx2/music';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ MUSIC_FX.find((d) => d.name === 'beat-bounce')!;
/** Register only this effect (idempotent). */
export function registerBeatBounce(): void {
  registerEffects([effect]);
}
export { registerBeatBounce as register };
