// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/blob-button` — the `blob-button` effect alone (morph pack): `import { registerBlobButton } from 'motionary/effects/blob-button'; registerBlobButton();` then <usa-fx effect="blob-button"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { MORPH2_FX } from '../../components/fx2/morph2';

/** The effect definition. */
export const effect: EffectDefinition = MORPH2_FX.find((d) => d.name === 'blob-button')!;
/** Register only this effect (idempotent). */
export function registerBlobButton(): void {
  registerEffects([effect]);
}
export { registerBlobButton as register };
