// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/bloom` — the `bloom` effect alone (organic pack): `import { registerBloom } from 'motionary/effects/bloom'; registerBloom();` then <usa-fx effect="bloom"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { ORGANIC_FX } from '../../components/fx2/organic';

/** The effect definition. */
export const effect: EffectDefinition = ORGANIC_FX.find((d) => d.name === 'bloom')!;
/** Register only this effect (idempotent). */
export function registerBloom(): void {
  registerEffects([effect]);
}
export { registerBloom as register };
