// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/breathe` — the `breathe` effect alone (organic pack): `import { registerBreathe } from 'motionary/effects/breathe'; registerBreathe();` then <usa-fx effect="breathe"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { ORGANIC_FX } from '../../components/fx2/organic';

/** The effect definition. */
export const effect: EffectDefinition = ORGANIC_FX.find((d) => d.name === 'breathe')!;
/** Register only this effect (idempotent). */
export function registerBreathe(): void {
  registerEffects([effect]);
}
export { registerBreathe as register };
