// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/brushed-metal` — the `brushed-metal` effect alone (light pack): `import { registerBrushedMetal } from 'motionary/effects/brushed-metal'; registerBrushedMetal();` then <usa-fx effect="brushed-metal"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { LIGHT_FX } from '../../components/fx2/light';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ LIGHT_FX.find((d) => d.name === 'brushed-metal')!;
/** Register only this effect (idempotent). */
export function registerBrushedMetal(): void {
  registerEffects([effect]);
}
export { registerBrushedMetal as register };
