// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/camera-dolly` — the `camera-dolly` effect alone (transitions pack): `import { registerCameraDolly } from 'motionary/effects/camera-dolly'; registerCameraDolly();` then <usa-fx effect="camera-dolly"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { TRANSITIONS2_FX } from '../../components/fx2/transitions2';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ TRANSITIONS2_FX.find((d) => d.name === 'camera-dolly')!;
/** Register only this effect (idempotent). */
export function registerCameraDolly(): void {
  registerEffects([effect]);
}
export { registerCameraDolly as register };
