// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/card-flip-3d` — the `card-flip-3d` effect alone (depth pack): `import { registerCardFlip3d } from 'motionary/effects/card-flip-3d'; registerCardFlip3d();` then <usa-fx effect="card-flip-3d"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { DEPTH3_FX } from '../../components/fx2/depth3';

/** The effect definition. */
export const effect: EffectDefinition = DEPTH3_FX.find((d) => d.name === 'card-flip-3d')!;
/** Register only this effect (idempotent). */
export function registerCardFlip3d(): void {
  registerEffects([effect]);
}
export { registerCardFlip3d as register };
