// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/chest-open` — the `chest-open` effect alone (game pack): `import { registerChestOpen } from 'motionary/effects/chest-open'; registerChestOpen();` then <usa-fx effect="chest-open"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GAME_FX } from '../../components/fx2/game';

/** The effect definition. */
export const effect: EffectDefinition = GAME_FX.find((d) => d.name === 'chest-open')!;
/** Register only this effect (idempotent). */
export function registerChestOpen(): void {
  registerEffects([effect]);
}
export { registerChestOpen as register };
