// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/cloth` — the `cloth` effect alone (physics pack): `import { registerCloth } from 'motionary/effects/cloth'; registerCloth();` then <usa-fx effect="cloth"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { PHYSICS2_FX } from '../../components/fx2/physics2';

/** The effect definition. */
export const effect: EffectDefinition = PHYSICS2_FX.find((d) => d.name === 'cloth')!;
/** Register only this effect (idempotent). */
export function registerCloth(): void {
  registerEffects([effect]);
}
export { registerCloth as register };
