// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/coin-burst` — the `coin-burst` effect alone (game pack): `import { registerCoinBurst } from 'motionary/effects/coin-burst'; registerCoinBurst();` then <usa-fx effect="coin-burst"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GAME_FX } from '../../components/fx2/game';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ GAME_FX.find((d) => d.name === 'coin-burst')!;
/** Register only this effect (idempotent). */
export function registerCoinBurst(): void {
  registerEffects([effect]);
}
export { registerCoinBurst as register };
