// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/color-pulse` — the `color-pulse` effect alone (safe pack): `import { registerColorPulse } from 'motionary/effects/color-pulse'; registerColorPulse();` then <usa-fx effect="color-pulse"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SAFE_FX } from '../../components/fx2/safemotion';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ SAFE_FX.find((d) => d.name === 'color-pulse')!;
/** Register only this effect (idempotent). */
export function registerColorPulse(): void {
  registerEffects([effect]);
}
export { registerColorPulse as register };
