// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/crt-power` — the `crt-power` effect alone (retro pack): `import { registerCrtPower } from 'motionary/effects/crt-power'; registerCrtPower();` then <usa-fx effect="crt-power"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { RETRO_FX } from '../../components/fx2/retro2';

/** The effect definition. */
export const effect: EffectDefinition = RETRO_FX.find((d) => d.name === 'crt-power')!;
/** Register only this effect (idempotent). */
export function registerCrtPower(): void {
  registerEffects([effect]);
}
export { registerCrtPower as register };
