// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/crumple` — the `crumple` effect alone (paper pack): `import { registerCrumple } from 'motionary/effects/crumple'; registerCrumple();` then <usa-fx effect="crumple"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { PAPER_FX } from '../../components/fx2/paper';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ PAPER_FX.find((d) => d.name === 'crumple')!;
/** Register only this effect (idempotent). */
export function registerCrumple(): void {
  registerEffects([effect]);
}
export { registerCrumple as register };
