// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/data-decode` — the `data-decode` effect alone (cyber pack): `import { registerDataDecode } from 'motionary/effects/data-decode'; registerDataDecode();` then <usa-fx effect="data-decode"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { CYBER_FX } from '../../components/fx2/cyber';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ CYBER_FX.find((d) => d.name === 'data-decode')!;
/** Register only this effect (idempotent). */
export function registerDataDecode(): void {
  registerEffects([effect]);
}
export { registerDataDecode as register };
