// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/day-cycle` — the `day-cycle` effect alone (weather pack): `import { registerDayCycle } from 'motionary/effects/day-cycle'; registerDayCycle();` then <usa-fx effect="day-cycle"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { WEATHER_FX } from '../../components/fx2/weather';

/** The effect definition. */
export const effect: EffectDefinition = WEATHER_FX.find((d) => d.name === 'day-cycle')!;
/** Register only this effect (idempotent). */
export function registerDayCycle(): void {
  registerEffects([effect]);
}
export { registerDayCycle as register };
