// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/depth-pop` — the `depth-pop` effect alone (spatial pack): `import { registerDepthPop } from 'motionary/effects/depth-pop'; registerDepthPop();` then <usa-fx effect="depth-pop"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SPATIAL_FX } from '../../components/fx2/spatial';

/** The effect definition. */
export const effect: EffectDefinition = SPATIAL_FX.find((d) => d.name === 'depth-pop')!;
/** Register only this effect (idempotent). */
export function registerDepthPop(): void {
  registerEffects([effect]);
}
export { registerDepthPop as register };
