// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/depth-stack` — the `depth-stack` effect alone (depth pack): `import { registerDepthStack } from 'motionary/effects/depth-stack'; registerDepthStack();` then <usa-fx effect="depth-stack"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { DEPTH3_FX } from '../../components/fx2/depth3';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ DEPTH3_FX.find((d) => d.name === 'depth-stack')!;
/** Register only this effect (idempotent). */
export function registerDepthStack(): void {
  registerEffects([effect]);
}
export { registerDepthStack as register };
