// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/depth-in` — the `depth-in` effect alone (gesture3 pack): `import { registerDepthIn } from 'motionary/effects/depth-in'; registerDepthIn();` then <usa-fx effect="depth-in"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GESTURE3_FX } from '../../components/fx2/gesture3';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ GESTURE3_FX.find((d) => d.name === 'depth-in')!;
/** Register only this effect (idempotent). */
export function registerDepthIn(): void {
  registerEffects([effect]);
}
export { registerDepthIn as register };
