// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/dolly-in` — the `dolly-in` effect alone (cinema pack): `import { registerDollyIn } from 'motionary/effects/dolly-in'; registerDollyIn();` then <usa-fx effect="dolly-in"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { CINEMA_FX } from '../../components/fx2/cinema';

/** The effect definition. */
export const effect: EffectDefinition = CINEMA_FX.find((d) => d.name === 'dolly-in')!;
/** Register only this effect (idempotent). */
export function registerDollyIn(): void {
  registerEffects([effect]);
}
export { registerDollyIn as register };
