// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/dots-pop` — the `dots-pop` effect alone (chart pack): `import { registerDotsPop } from 'motionary/effects/dots-pop'; registerDotsPop();` then <usa-fx effect="dots-pop"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { CHART_FX } from '../../components/fx2/chart';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ CHART_FX.find((d) => d.name === 'dots-pop')!;
/** Register only this effect (idempotent). */
export function registerDotsPop(): void {
  registerEffects([effect]);
}
export { registerDotsPop as register };
