// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/field-shake` — the `field-shake` effect alone (form pack): `import { registerFieldShake } from 'motionary/effects/field-shake'; registerFieldShake();` then <usa-fx effect="field-shake"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { FORM_FX } from '../../components/fx2/form';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ FORM_FX.find((d) => d.name === 'field-shake')!;
/** Register only this effect (idempotent). */
export function registerFieldShake(): void {
  registerEffects([effect]);
}
export { registerFieldShake as register };
