// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/field-success` — the `field-success` effect alone (form pack): `import { registerFieldSuccess } from 'motionary/effects/field-success'; registerFieldSuccess();` then <usa-fx effect="field-success"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { FORM_FX } from '../../components/fx2/form';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ FORM_FX.find((d) => d.name === 'field-success')!;
/** Register only this effect (idempotent). */
export function registerFieldSuccess(): void {
  registerEffects([effect]);
}
export { registerFieldSuccess as register };
