// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/film-burn` — the `film-burn` effect alone (video pack): `import { registerFilmBurn } from 'motionary/effects/film-burn'; registerFilmBurn();` then <usa-fx effect="film-burn"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { VIDEO_FX } from '../../components/fx2/video';

/** The effect definition. */
export const effect: EffectDefinition = VIDEO_FX.find((d) => d.name === 'film-burn')!;
/** Register only this effect (idempotent). */
export function registerFilmBurn(): void {
  registerEffects([effect]);
}
export { registerFilmBurn as register };
