// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/firework-burst` — the `firework-burst` effect alone (festival pack): `import { registerFireworkBurst } from 'motionary/effects/firework-burst'; registerFireworkBurst();` then <usa-fx effect="firework-burst"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { FESTIVAL_FX } from '../../components/fx2/festival';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ FESTIVAL_FX.find((d) => d.name === 'firework-burst')!;
/** Register only this effect (idempotent). */
export function registerFireworkBurst(): void {
  registerEffects([effect]);
}
export { registerFireworkBurst as register };
