// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/fire` — the `fire` effect alone (gpu pack): `import { registerFire } from 'motionary/effects/fire'; registerFire();` then <usa-fx effect="fire"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GPU_FX } from '../../components/fx2/gpu';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ GPU_FX.find((d) => d.name === 'fire')!;
/** Register only this effect (idempotent). */
export function registerFire(): void {
  registerEffects([effect]);
}
export { registerFire as register };
