// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/fireflies` — the `fireflies` effect alone (gpu pack): `import { registerFireflies } from 'motionary/effects/fireflies'; registerFireflies();` then <usa-fx effect="fireflies"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GPU_FX } from '../../components/fx2/gpu';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ GPU_FX.find((d) => d.name === 'fireflies')!;
/** Register only this effect (idempotent). */
export function registerFireflies(): void {
  registerEffects([effect]);
}
export { registerFireflies as register };
