// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/flip-chars` — the `flip-chars` effect alone (text pack): `import { registerFlipChars } from 'motionary/effects/flip-chars'; registerFlipChars();` then <usa-fx effect="flip-chars"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { TEXT3_FX } from '../../components/fx2/text3';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ TEXT3_FX.find((d) => d.name === 'flip-chars')!;
/** Register only this effect (idempotent). */
export function registerFlipChars(): void {
  registerEffects([effect]);
}
export { registerFlipChars as register };
