// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/fluid` — the `fluid` effect alone (gpu pack): `import { registerFluid } from 'motionary/effects/fluid'; registerFluid();` then <usa-fx effect="fluid"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GPU_FX } from '../../components/fx2/gpu';

/** The effect definition. */
export const effect: EffectDefinition = GPU_FX.find((d) => d.name === 'fluid')!;
/** Register only this effect (idempotent). */
export function registerFluid(): void {
  registerEffects([effect]);
}
export { registerFluid as register };
