// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/fly-to-cart` — the `fly-to-cart` effect alone (shop pack): `import { registerFlyToCart } from 'motionary/effects/fly-to-cart'; registerFlyToCart();` then <usa-fx effect="fly-to-cart"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SHOP_FX } from '../../components/fx2/shop';

/** The effect definition. */
export const effect: EffectDefinition = SHOP_FX.find((d) => d.name === 'fly-to-cart')!;
/** Register only this effect (idempotent). */
export function registerFlyToCart(): void {
  registerEffects([effect]);
}
export { registerFlyToCart as register };
