// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/focus-glow` — the `focus-glow` effect alone (safe pack): `import { registerFocusGlow } from 'motionary/effects/focus-glow'; registerFocusGlow();` then <usa-fx effect="focus-glow"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SAFE_FX } from '../../components/fx2/safemotion';

/** The effect definition. */
export const effect: EffectDefinition = SAFE_FX.find((d) => d.name === 'focus-glow')!;
/** Register only this effect (idempotent). */
export function registerFocusGlow(): void {
  registerEffects([effect]);
}
export { registerFocusGlow as register };
