// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/focus-draw` — the `focus-draw` effect alone (focus pack): `import { registerFocusDraw } from 'motionary/effects/focus-draw'; registerFocusDraw();` then <usa-fx effect="focus-draw"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { FOCUS_FX } from '../../components/fx2/focus';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ FOCUS_FX.find((d) => d.name === 'focus-draw')!;
/** Register only this effect (idempotent). */
export function registerFocusDraw(): void {
  registerEffects([effect]);
}
export { registerFocusDraw as register };
