// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/fog` — the `fog` effect alone (weather pack): `import { registerFog } from 'motionary/effects/fog'; registerFog();` then <usa-fx effect="fog"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { WEATHER_FX } from '../../components/fx2/weather';

/** The effect definition. */
export const effect: EffectDefinition = WEATHER_FX.find((d) => d.name === 'fog')!;
/** Register only this effect (idempotent). */
export function registerFog(): void {
  registerEffects([effect]);
}
export { registerFog as register };
