// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/font-breathe` — the `font-breathe` effect alone (text pack): `import { registerFontBreathe } from 'motionary/effects/font-breathe'; registerFontBreathe();` then <usa-fx effect="font-breathe"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { TEXT3_FX } from '../../components/fx2/text3';

/** The effect definition. */
export const effect: EffectDefinition = TEXT3_FX.find((d) => d.name === 'font-breathe')!;
/** Register only this effect (idempotent). */
export function registerFontBreathe(): void {
  registerEffects([effect]);
}
export { registerFontBreathe as register };
