// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/form-cascade` — the `form-cascade` effect alone (form pack): `import { registerFormCascade } from 'motionary/effects/form-cascade'; registerFormCascade();` then <usa-fx effect="form-cascade"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { FORM_FX } from '../../components/fx2/form';

/** The effect definition. */
export const effect: EffectDefinition = FORM_FX.find((d) => d.name === 'form-cascade')!;
/** Register only this effect (idempotent). */
export function registerFormCascade(): void {
  registerEffects([effect]);
}
export { registerFormCascade as register };
