// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/gen-skeleton` — the `gen-skeleton` effect alone (ai pack): `import { registerGenSkeleton } from 'motionary/effects/gen-skeleton'; registerGenSkeleton();` then <usa-fx effect="gen-skeleton"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { AI_FX } from '../../components/fx2/ai';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ AI_FX.find((d) => d.name === 'gen-skeleton')!;
/** Register only this effect (idempotent). */
export function registerGenSkeleton(): void {
  registerEffects([effect]);
}
export { registerGenSkeleton as register };
