// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/glass-frost` — the `glass-frost` effect alone (surface pack): `import { registerGlassFrost } from 'motionary/effects/glass-frost'; registerGlassFrost();` then <usa-fx effect="glass-frost"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SURFACE_FX } from '../../components/fx2/themefx';

/** The effect definition. */
export const effect: EffectDefinition = SURFACE_FX.find((d) => d.name === 'glass-frost')!;
/** Register only this effect (idempotent). */
export function registerGlassFrost(): void {
  registerEffects([effect]);
}
export { registerGlassFrost as register };
