// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/glitch-text` — the `glitch-text` effect alone (text pack): `import { registerGlitchText } from 'motionary/effects/glitch-text'; registerGlitchText();` then <usa-fx effect="glitch-text"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { TEXT3_FX } from '../../components/fx2/text3';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ TEXT3_FX.find((d) => d.name === 'glitch-text')!;
/** Register only this effect (idempotent). */
export function registerGlitchText(): void {
  registerEffects([effect]);
}
export { registerGlitchText as register };
