// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/globe-spin` — the `globe-spin` effect alone (geo pack): `import { registerGlobeSpin } from 'motionary/effects/globe-spin'; registerGlobeSpin();` then <usa-fx effect="globe-spin"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GEO_FX } from '../../components/fx2/geo';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ GEO_FX.find((d) => d.name === 'globe-spin')!;
/** Register only this effect (idempotent). */
export function registerGlobeSpin(): void {
  registerEffects([effect]);
}
export { registerGlobeSpin as register };
