// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/god-rays` — the `god-rays` effect alone (light pack): `import { registerGodRays } from 'motionary/effects/god-rays'; registerGodRays();` then <usa-fx effect="god-rays"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { LIGHT_FX } from '../../components/fx2/light';

/** The effect definition. */
export const effect: EffectDefinition = LIGHT_FX.find((d) => d.name === 'god-rays')!;
/** Register only this effect (idempotent). */
export function registerGodRays(): void {
  registerEffects([effect]);
}
export { registerGodRays as register };
