// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/gpu-lift` — the `gpu-lift` effect alone (perf3 pack): `import { registerGpuLift } from 'motionary/effects/gpu-lift'; registerGpuLift();` then <usa-fx effect="gpu-lift"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { PERF3_FX } from '../../components/fx2/perf3';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ PERF3_FX.find((d) => d.name === 'gpu-lift')!;
/** Register only this effect (idempotent). */
export function registerGpuLift(): void {
  registerEffects([effect]);
}
export { registerGpuLift as register };
