// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/grain-flicker` — the `grain-flicker` effect alone (genart pack): `import { registerGrainFlicker } from 'motionary/effects/grain-flicker'; registerGrainFlicker();` then <usa-fx effect="grain-flicker"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GENART_FX } from '../../components/fx2/genart';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ GENART_FX.find((d) => d.name === 'grain-flicker')!;
/** Register only this effect (idempotent). */
export function registerGrainFlicker(): void {
  registerEffects([effect]);
}
export { registerGrainFlicker as register };
