// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/halftone-in` — the `halftone-in` effect alone (genart pack): `import { registerHalftoneIn } from 'motionary/effects/halftone-in'; registerHalftoneIn();` then <usa-fx effect="halftone-in"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GENART_FX } from '../../components/fx2/genart';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ GENART_FX.find((d) => d.name === 'halftone-in')!;
/** Register only this effect (idempotent). */
export function registerHalftoneIn(): void {
  registerEffects([effect]);
}
export { registerHalftoneIn as register };
