// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/highlight-sweep` — the `highlight-sweep` effect alone (focus pack): `import { registerHighlightSweep } from 'motionary/effects/highlight-sweep'; registerHighlightSweep();` then <usa-fx effect="highlight-sweep"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { FOCUS_FX } from '../../components/fx2/focus';

/** The effect definition. */
export const effect: EffectDefinition = FOCUS_FX.find((d) => d.name === 'highlight-sweep')!;
/** Register only this effect (idempotent). */
export function registerHighlightSweep(): void {
  registerEffects([effect]);
}
export { registerHighlightSweep as register };
