// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/hologram` — the `hologram` effect alone (cyber pack): `import { registerHologram } from 'motionary/effects/hologram'; registerHologram();` then <usa-fx effect="hologram"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { CYBER_FX } from '../../components/fx2/cyber';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ CYBER_FX.find((d) => d.name === 'hologram')!;
/** Register only this effect (idempotent). */
export function registerHologram(): void {
  registerEffects([effect]);
}
export { registerHologram as register };
