// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/hud-frame` — the `hud-frame` effect alone (cyber pack): `import { registerHudFrame } from 'motionary/effects/hud-frame'; registerHudFrame();` then <usa-fx effect="hud-frame"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { CYBER_FX } from '../../components/fx2/cyber';

/** The effect definition. */
export const effect: EffectDefinition = CYBER_FX.find((d) => d.name === 'hud-frame')!;
/** Register only this effect (idempotent). */
export function registerHudFrame(): void {
  registerEffects([effect]);
}
export { registerHudFrame as register };
