// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/icon-pop` — the `icon-pop` effect alone (lottie pack): `import { registerIconPop } from 'motionary/effects/icon-pop'; registerIconPop();` then <usa-fx effect="icon-pop"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { LOTTIE_FX } from '../../components/fx2/lottie';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ LOTTIE_FX.find((d) => d.name === 'icon-pop')!;
/** Register only this effect (idempotent). */
export function registerIconPop(): void {
  registerEffects([effect]);
}
export { registerIconPop as register };
