// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/icon-swap` — the `icon-swap` effect alone (morph pack): `import { registerIconSwap } from 'motionary/effects/icon-swap'; registerIconSwap();` then <usa-fx effect="icon-swap"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { MORPH2_FX } from '../../components/fx2/morph2';

/** The effect definition. */
export const effect: EffectDefinition = MORPH2_FX.find((d) => d.name === 'icon-swap')!;
/** Register only this effect (idempotent). */
export function registerIconSwap(): void {
  registerEffects([effect]);
}
export { registerIconSwap as register };
