// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/idle-reveal` — the `idle-reveal` effect alone (perf3 pack): `import { registerIdleReveal } from 'motionary/effects/idle-reveal'; registerIdleReveal();` then <usa-fx effect="idle-reveal"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { PERF3_FX } from '../../components/fx2/perf3';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ PERF3_FX.find((d) => d.name === 'idle-reveal')!;
/** Register only this effect (idempotent). */
export function registerIdleReveal(): void {
  registerEffects([effect]);
}
export { registerIdleReveal as register };
