// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/ink` — the `ink` effect alone (gpu pack): `import { registerInk } from 'motionary/effects/ink'; registerInk();` then <usa-fx effect="ink"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GPU_FX } from '../../components/fx2/gpu';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ GPU_FX.find((d) => d.name === 'ink')!;
/** Register only this effect (idempotent). */
export function registerInk(): void {
  registerEffects([effect]);
}
export { registerInk as register };
