// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/jump-cut` — the `jump-cut` effect alone (video pack): `import { registerJumpCut } from 'motionary/effects/jump-cut'; registerJumpCut();` then <usa-fx effect="jump-cut"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { VIDEO_FX } from '../../components/fx2/video';

/** The effect definition. */
export const effect: EffectDefinition = VIDEO_FX.find((d) => d.name === 'jump-cut')!;
/** Register only this effect (idempotent). */
export function registerJumpCut(): void {
  registerEffects([effect]);
}
export { registerJumpCut as register };
