// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/kaleido` — the `kaleido` effect alone (genart pack): `import { registerKaleido } from 'motionary/effects/kaleido'; registerKaleido();` then <usa-fx effect="kaleido"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GENART_FX } from '../../components/fx2/genart';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ GENART_FX.find((d) => d.name === 'kaleido')!;
/** Register only this effect (idempotent). */
export function registerKaleido(): void {
  registerEffects([effect]);
}
export { registerKaleido as register };
