// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/label-float` — the `label-float` effect alone (form pack): `import { registerLabelFloat } from 'motionary/effects/label-float'; registerLabelFloat();` then <usa-fx effect="label-float"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { FORM_FX } from '../../components/fx2/form';

/** The effect definition. */
export const effect: EffectDefinition = FORM_FX.find((d) => d.name === 'label-float')!;
/** Register only this effect (idempotent). */
export function registerLabelFloat(): void {
  registerEffects([effect]);
}
export { registerLabelFloat as register };
