// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/lantern-rise` — the `lantern-rise` effect alone (festival pack): `import { registerLanternRise } from 'motionary/effects/lantern-rise'; registerLanternRise();` then <usa-fx effect="lantern-rise"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { FESTIVAL_FX } from '../../components/fx2/festival';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ FESTIVAL_FX.find((d) => d.name === 'lantern-rise')!;
/** Register only this effect (idempotent). */
export function registerLanternRise(): void {
  registerEffects([effect]);
}
export { registerLanternRise as register };
