// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/leaves` — the `leaves` effect alone (gpu pack): `import { registerLeaves } from 'motionary/effects/leaves'; registerLeaves();` then <usa-fx effect="leaves"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GPU_FX } from '../../components/fx2/gpu';

/** The effect definition. */
export const effect: EffectDefinition = GPU_FX.find((d) => d.name === 'leaves')!;
/** Register only this effect (idempotent). */
export function registerLeaves(): void {
  registerEffects([effect]);
}
export { registerLeaves as register };
