// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/letterbox` — the `letterbox` effect alone (cinema pack): `import { registerLetterbox } from 'motionary/effects/letterbox'; registerLetterbox();` then <usa-fx effect="letterbox"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { CINEMA_FX } from '../../components/fx2/cinema';

/** The effect definition. */
export const effect: EffectDefinition = CINEMA_FX.find((d) => d.name === 'letterbox')!;
/** Register only this effect (idempotent). */
export function registerLetterbox(): void {
  registerEffects([effect]);
}
export { registerLetterbox as register };
