// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/level-up` — the `level-up` effect alone (game pack): `import { registerLevelUp } from 'motionary/effects/level-up'; registerLevelUp();` then <usa-fx effect="level-up"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GAME_FX } from '../../components/fx2/game';

/** The effect definition. */
export const effect: EffectDefinition = GAME_FX.find((d) => d.name === 'level-up')!;
/** Register only this effect (idempotent). */
export function registerLevelUp(): void {
  registerEffects([effect]);
}
export { registerLevelUp as register };
