// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/light-follow` — the `light-follow` effect alone (light pack): `import { registerLightFollow } from 'motionary/effects/light-follow'; registerLightFollow();` then <usa-fx effect="light-follow"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { LIGHT_FX } from '../../components/fx2/light';

/** The effect definition. */
export const effect: EffectDefinition = LIGHT_FX.find((d) => d.name === 'light-follow')!;
/** Register only this effect (idempotent). */
export function registerLightFollow(): void {
  registerEffects([effect]);
}
export { registerLightFollow as register };
