// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/lightning` — the `lightning` effect alone (weather pack): `import { registerLightning } from 'motionary/effects/lightning'; registerLightning();` then <usa-fx effect="lightning"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { WEATHER_FX } from '../../components/fx2/weather';

/** The effect definition. */
export const effect: EffectDefinition = WEATHER_FX.find((d) => d.name === 'lightning')!;
/** Register only this effect (idempotent). */
export function registerLightning(): void {
  registerEffects([effect]);
}
export { registerLightning as register };
