// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/line-draw` — the `line-draw` effect alone (chart pack): `import { registerLineDraw } from 'motionary/effects/line-draw'; registerLineDraw();` then <usa-fx effect="line-draw"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { CHART_FX } from '../../components/fx2/chart';

/** The effect definition. */
export const effect: EffectDefinition = CHART_FX.find((d) => d.name === 'line-draw')!;
/** Register only this effect (idempotent). */
export function registerLineDraw(): void {
  registerEffects([effect]);
}
export { registerLineDraw as register };
