// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/liquid-wipe` — the `liquid-wipe` effect alone (transitions pack): `import { registerLiquidWipe } from 'motionary/effects/liquid-wipe'; registerLiquidWipe();` then <usa-fx effect="liquid-wipe"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { TRANSITIONS2_FX } from '../../components/fx2/transitions2';

/** The effect definition. */
export const effect: EffectDefinition = TRANSITIONS2_FX.find((d) => d.name === 'liquid-wipe')!;
/** Register only this effect (idempotent). */
export function registerLiquidWipe(): void {
  registerEffects([effect]);
}
export { registerLiquidWipe as register };
