// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/liquid-text` — the `liquid-text` effect alone (text pack): `import { registerLiquidText } from 'motionary/effects/liquid-text'; registerLiquidText();` then <usa-fx effect="liquid-text"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { TEXT3_FX } from '../../components/fx2/text3';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ TEXT3_FX.find((d) => d.name === 'liquid-text')!;
/** Register only this effect (idempotent). */
export function registerLiquidText(): void {
  registerEffects([effect]);
}
export { registerLiquidText as register };
