// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/lottie-play` — the `lottie-play` effect alone (lottie pack): `import { registerLottiePlay } from 'motionary/effects/lottie-play'; registerLottiePlay();` then <usa-fx effect="lottie-play"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { LOTTIE_FX } from '../../components/fx2/lottie';

/** The effect definition. */
export const effect: EffectDefinition = LOTTIE_FX.find((d) => d.name === 'lottie-play')!;
/** Register only this effect (idempotent). */
export function registerLottiePlay(): void {
  registerEffects([effect]);
}
export { registerLottiePlay as register };
