// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/magnet` — the `magnet` effect alone (physics pack): `import { registerMagnet } from 'motionary/effects/magnet'; registerMagnet();` then <usa-fx effect="magnet"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { PHYSICS2_FX } from '../../components/fx2/physics2';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ PHYSICS2_FX.find((d) => d.name === 'magnet')!;
/** Register only this effect (idempotent). */
export function registerMagnet(): void {
  registerEffects([effect]);
}
export { registerMagnet as register };
