// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/marching-ants` — the `marching-ants` effect alone (focus pack): `import { registerMarchingAnts } from 'motionary/effects/marching-ants'; registerMarchingAnts();` then <usa-fx effect="marching-ants"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { FOCUS_FX } from '../../components/fx2/focus';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ FOCUS_FX.find((d) => d.name === 'marching-ants')!;
/** Register only this effect (idempotent). */
export function registerMarchingAnts(): void {
  registerEffects([effect]);
}
export { registerMarchingAnts as register };
