// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/marker-pulse` — the `marker-pulse` effect alone (geo pack): `import { registerMarkerPulse } from 'motionary/effects/marker-pulse'; registerMarkerPulse();` then <usa-fx effect="marker-pulse"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GEO_FX } from '../../components/fx2/geo';

/** The effect definition. */
export const effect: EffectDefinition = GEO_FX.find((d) => d.name === 'marker-pulse')!;
/** Register only this effect (idempotent). */
export function registerMarkerPulse(): void {
  registerEffects([effect]);
}
export { registerMarkerPulse as register };
