// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/mention-glow` — the `mention-glow` effect alone (social pack): `import { registerMentionGlow } from 'motionary/effects/mention-glow'; registerMentionGlow();` then <usa-fx effect="mention-glow"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SOCIAL_FX } from '../../components/fx2/social';

/** The effect definition. */
export const effect: EffectDefinition = SOCIAL_FX.find((d) => d.name === 'mention-glow')!;
/** Register only this effect (idempotent). */
export function registerMentionGlow(): void {
  registerEffects([effect]);
}
export { registerMentionGlow as register };
