// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/mesh-drift` — the `mesh-drift` effect alone (genart pack): `import { registerMeshDrift } from 'motionary/effects/mesh-drift'; registerMeshDrift();` then <usa-fx effect="mesh-drift"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GENART_FX } from '../../components/fx2/genart';

/** The effect definition. */
export const effect: EffectDefinition = GENART_FX.find((d) => d.name === 'mesh-drift')!;
/** Register only this effect (idempotent). */
export function registerMeshDrift(): void {
  registerEffects([effect]);
}
export { registerMeshDrift as register };
