// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/message-in` — the `message-in` effect alone (social pack): `import { registerMessageIn } from 'motionary/effects/message-in'; registerMessageIn();` then <usa-fx effect="message-in"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SOCIAL_FX } from '../../components/fx2/social';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ SOCIAL_FX.find((d) => d.name === 'message-in')!;
/** Register only this effect (idempotent). */
export function registerMessageIn(): void {
  registerEffects([effect]);
}
export { registerMessageIn as register };
