// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/mosaic-flip` — the `mosaic-flip` effect alone (transitions pack): `import { registerMosaicFlip } from 'motionary/effects/mosaic-flip'; registerMosaicFlip();` then <usa-fx effect="mosaic-flip"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { TRANSITIONS2_FX } from '../../components/fx2/transitions2';

/** The effect definition. */
export const effect: EffectDefinition = TRANSITIONS2_FX.find((d) => d.name === 'mosaic-flip')!;
/** Register only this effect (idempotent). */
export function registerMosaicFlip(): void {
  registerEffects([effect]);
}
export { registerMosaicFlip as register };
