// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/neon-pulse` — the `neon-pulse` effect alone (surface pack): `import { registerNeonPulse } from 'motionary/effects/neon-pulse'; registerNeonPulse();` then <usa-fx effect="neon-pulse"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SURFACE_FX } from '../../components/fx2/themefx';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ SURFACE_FX.find((d) => d.name === 'neon-pulse')!;
/** Register only this effect (idempotent). */
export function registerNeonPulse(): void {
  registerEffects([effect]);
}
export { registerNeonPulse as register };
