// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/neon-ignite` — the `neon-ignite` effect alone (surface pack): `import { registerNeonIgnite } from 'motionary/effects/neon-ignite'; registerNeonIgnite();` then <usa-fx effect="neon-ignite"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SURFACE_FX } from '../../components/fx2/themefx';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ SURFACE_FX.find((d) => d.name === 'neon-ignite')!;
/** Register only this effect (idempotent). */
export function registerNeonIgnite(): void {
  registerEffects([effect]);
}
export { registerNeonIgnite as register };
