// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/neon-write` — the `neon-write` effect alone (text pack): `import { registerNeonWrite } from 'motionary/effects/neon-write'; registerNeonWrite();` then <usa-fx effect="neon-write"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { TEXT3_FX } from '../../components/fx2/text3';

/** The effect definition. */
export const effect: EffectDefinition = TEXT3_FX.find((d) => d.name === 'neon-write')!;
/** Register only this effect (idempotent). */
export function registerNeonWrite(): void {
  registerEffects([effect]);
}
export { registerNeonWrite as register };
