// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/neu-press` — the `neu-press` effect alone (surface pack): `import { registerNeuPress } from 'motionary/effects/neu-press'; registerNeuPress();` then <usa-fx effect="neu-press"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SURFACE_FX } from '../../components/fx2/themefx';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ SURFACE_FX.find((d) => d.name === 'neu-press')!;
/** Register only this effect (idempotent). */
export function registerNeuPress(): void {
  registerEffects([effect]);
}
export { registerNeuPress as register };
