// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/noise-reveal` — the `noise-reveal` effect alone (morph pack): `import { registerNoiseReveal } from 'motionary/effects/noise-reveal'; registerNoiseReveal();` then <usa-fx effect="noise-reveal"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { MORPH2_FX } from '../../components/fx2/morph2';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ MORPH2_FX.find((d) => d.name === 'noise-reveal')!;
/** Register only this effect (idempotent). */
export function registerNoiseReveal(): void {
  registerEffects([effect]);
}
export { registerNoiseReveal as register };
