// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/number-roll` — the `number-roll` effect alone (chart pack): `import { registerNumberRoll } from 'motionary/effects/number-roll'; registerNumberRoll();` then <usa-fx effect="number-roll"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { CHART_FX } from '../../components/fx2/chart';

/** The effect definition. */
export const effect: EffectDefinition = CHART_FX.find((d) => d.name === 'number-roll')!;
/** Register only this effect (idempotent). */
export function registerNumberRoll(): void {
  registerEffects([effect]);
}
export { registerNumberRoll as register };
