// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/orbit-in` — the `orbit-in` effect alone (spatial pack): `import { registerOrbitIn } from 'motionary/effects/orbit-in'; registerOrbitIn();` then <usa-fx effect="orbit-in"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SPATIAL_FX } from '../../components/fx2/spatial';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ SPATIAL_FX.find((d) => d.name === 'orbit-in')!;
/** Register only this effect (idempotent). */
export function registerOrbitIn(): void {
  registerEffects([effect]);
}
export { registerOrbitIn as register };
