// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/orbit-camera` — the `orbit-camera` effect alone (depth pack): `import { registerOrbitCamera } from 'motionary/effects/orbit-camera'; registerOrbitCamera();` then <usa-fx effect="orbit-camera"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { DEPTH3_FX } from '../../components/fx2/depth3';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ DEPTH3_FX.find((d) => d.name === 'orbit-camera')!;
/** Register only this effect (idempotent). */
export function registerOrbitCamera(): void {
  registerEffects([effect]);
}
export { registerOrbitCamera as register };
