// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/origami` — the `origami` effect alone (depth pack): `import { registerOrigami } from 'motionary/effects/origami'; registerOrigami();` then <usa-fx effect="origami"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { DEPTH3_FX } from '../../components/fx2/depth3';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ DEPTH3_FX.find((d) => d.name === 'origami')!;
/** Register only this effect (idempotent). */
export function registerOrigami(): void {
  registerEffects([effect]);
}
export { registerOrigami as register };
