// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/page-curl` — the `page-curl` effect alone (transitions pack): `import { registerPageCurl } from 'motionary/effects/page-curl'; registerPageCurl();` then <usa-fx effect="page-curl"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { TRANSITIONS2_FX } from '../../components/fx2/transitions2';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ TRANSITIONS2_FX.find((d) => d.name === 'page-curl')!;
/** Register only this effect (idempotent). */
export function registerPageCurl(): void {
  registerEffects([effect]);
}
export { registerPageCurl as register };
