// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/pan-reveal` — the `pan-reveal` effect alone (cinema pack): `import { registerPanReveal } from 'motionary/effects/pan-reveal'; registerPanReveal();` then <usa-fx effect="pan-reveal"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { CINEMA_FX } from '../../components/fx2/cinema';

/** The effect definition. */
export const effect: EffectDefinition = CINEMA_FX.find((d) => d.name === 'pan-reveal')!;
/** Register only this effect (idempotent). */
export function registerPanReveal(): void {
  registerEffects([effect]);
}
export { registerPanReveal as register };
