// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/paper-unfold` — the `paper-unfold` effect alone (paper pack): `import { registerPaperUnfold } from 'motionary/effects/paper-unfold'; registerPaperUnfold();` then <usa-fx effect="paper-unfold"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { PAPER_FX } from '../../components/fx2/paper';

/** The effect definition. */
export const effect: EffectDefinition = PAPER_FX.find((d) => d.name === 'paper-unfold')!;
/** Register only this effect (idempotent). */
export function registerPaperUnfold(): void {
  registerEffects([effect]);
}
export { registerPaperUnfold as register };
