// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/particle-text` — the `particle-text` effect alone (text pack): `import { registerParticleText } from 'motionary/effects/particle-text'; registerParticleText();` then <usa-fx effect="particle-text"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { TEXT3_FX } from '../../components/fx2/text3';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ TEXT3_FX.find((d) => d.name === 'particle-text')!;
/** Register only this effect (idempotent). */
export function registerParticleText(): void {
  registerEffects([effect]);
}
export { registerParticleText as register };
