// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/path-morph` — the `path-morph` effect alone (morph pack): `import { registerPathMorph } from 'motionary/effects/path-morph'; registerPathMorph();` then <usa-fx effect="path-morph"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { MORPH2_FX } from '../../components/fx2/morph2';

/** The effect definition. */
export const effect: EffectDefinition = MORPH2_FX.find((d) => d.name === 'path-morph')!;
/** Register only this effect (idempotent). */
export function registerPathMorph(): void {
  registerEffects([effect]);
}
export { registerPathMorph as register };
