// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/pearlescent` — the `pearlescent` effect alone (light pack): `import { registerPearlescent } from 'motionary/effects/pearlescent'; registerPearlescent();` then <usa-fx effect="pearlescent"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { LIGHT_FX } from '../../components/fx2/light';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ LIGHT_FX.find((d) => d.name === 'pearlescent')!;
/** Register only this effect (idempotent). */
export function registerPearlescent(): void {
  registerEffects([effect]);
}
export { registerPearlescent as register };
