// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/pencil-sketch` — the `pencil-sketch` effect alone (paper pack): `import { registerPencilSketch } from 'motionary/effects/pencil-sketch'; registerPencilSketch();` then <usa-fx effect="pencil-sketch"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { PAPER_FX } from '../../components/fx2/paper';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ PAPER_FX.find((d) => d.name === 'pencil-sketch')!;
/** Register only this effect (idempotent). */
export function registerPencilSketch(): void {
  registerEffects([effect]);
}
export { registerPencilSketch as register };
