// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/pin-drop` — the `pin-drop` effect alone (geo pack): `import { registerPinDrop } from 'motionary/effects/pin-drop'; registerPinDrop();` then <usa-fx effect="pin-drop"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GEO_FX } from '../../components/fx2/geo';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ GEO_FX.find((d) => d.name === 'pin-drop')!;
/** Register only this effect (idempotent). */
export function registerPinDrop(): void {
  registerEffects([effect]);
}
export { registerPinDrop as register };
