// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/pinball` — the `pinball` effect alone (physics pack): `import { registerPinball } from 'motionary/effects/pinball'; registerPinball();` then <usa-fx effect="pinball"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { PHYSICS2_FX } from '../../components/fx2/physics2';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ PHYSICS2_FX.find((d) => d.name === 'pinball')!;
/** Register only this effect (idempotent). */
export function registerPinball(): void {
  registerEffects([effect]);
}
export { registerPinball as register };
