// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/pinch-hint` — the `pinch-hint` effect alone (gesture3 pack): `import { registerPinchHint } from 'motionary/effects/pinch-hint'; registerPinchHint();` then <usa-fx effect="pinch-hint"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GESTURE3_FX } from '../../components/fx2/gesture3';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ GESTURE3_FX.find((d) => d.name === 'pinch-hint')!;
/** Register only this effect (idempotent). */
export function registerPinchHint(): void {
  registerEffects([effect]);
}
export { registerPinchHint as register };
