// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/pixelate-in` — the `pixelate-in` effect alone (retro pack): `import { registerPixelateIn } from 'motionary/effects/pixelate-in'; registerPixelateIn();` then <usa-fx effect="pixelate-in"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { RETRO_FX } from '../../components/fx2/retro2';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ RETRO_FX.find((d) => d.name === 'pixelate-in')!;
/** Register only this effect (idempotent). */
export function registerPixelateIn(): void {
  registerEffects([effect]);
}
export { registerPixelateIn as register };
