// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/pointer-shadow` — the `pointer-shadow` effect alone (light pack): `import { registerPointerShadow } from 'motionary/effects/pointer-shadow'; registerPointerShadow();` then <usa-fx effect="pointer-shadow"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { LIGHT_FX } from '../../components/fx2/light';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ LIGHT_FX.find((d) => d.name === 'pointer-shadow')!;
/** Register only this effect (idempotent). */
export function registerPointerShadow(): void {
  registerEffects([effect]);
}
export { registerPointerShadow as register };
