// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/portal-open` — the `portal-open` effect alone (spatial pack): `import { registerPortalOpen } from 'motionary/effects/portal-open'; registerPortalOpen();` then <usa-fx effect="portal-open"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SPATIAL_FX } from '../../components/fx2/spatial';

/** The effect definition. */
export const effect: EffectDefinition = SPATIAL_FX.find((d) => d.name === 'portal-open')!;
/** Register only this effect (idempotent). */
export function registerPortalOpen(): void {
  registerEffects([effect]);
}
export { registerPortalOpen as register };
