// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/price-flip` — the `price-flip` effect alone (shop pack): `import { registerPriceFlip } from 'motionary/effects/price-flip'; registerPriceFlip();` then <usa-fx effect="price-flip"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SHOP_FX } from '../../components/fx2/shop';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ SHOP_FX.find((d) => d.name === 'price-flip')!;
/** Register only this effect (idempotent). */
export function registerPriceFlip(): void {
  registerEffects([effect]);
}
export { registerPriceFlip as register };
