// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/product-spin` — the `product-spin` effect alone (depth pack): `import { registerProductSpin } from 'motionary/effects/product-spin'; registerProductSpin();` then <usa-fx effect="product-spin"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { DEPTH3_FX } from '../../components/fx2/depth3';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ DEPTH3_FX.find((d) => d.name === 'product-spin')!;
/** Register only this effect (idempotent). */
export function registerProductSpin(): void {
  registerEffects([effect]);
}
export { registerProductSpin as register };
