// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/rack-focus` — the `rack-focus` effect alone (cinema pack): `import { registerRackFocus } from 'motionary/effects/rack-focus'; registerRackFocus();` then <usa-fx effect="rack-focus"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { CINEMA_FX } from '../../components/fx2/cinema';

/** The effect definition. */
export const effect: EffectDefinition = CINEMA_FX.find((d) => d.name === 'rack-focus')!;
/** Register only this effect (idempotent). */
export function registerRackFocus(): void {
  registerEffects([effect]);
}
export { registerRackFocus as register };
