// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/radial-spectrum` — the `radial-spectrum` effect alone (music pack): `import { registerRadialSpectrum } from 'motionary/effects/radial-spectrum'; registerRadialSpectrum();` then <usa-fx effect="radial-spectrum"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { MUSIC_FX } from '../../components/fx2/music';

/** The effect definition. */
export const effect: EffectDefinition = MUSIC_FX.find((d) => d.name === 'radial-spectrum')!;
/** Register only this effect (idempotent). */
export function registerRadialSpectrum(): void {
  registerEffects([effect]);
}
export { registerRadialSpectrum as register };
