// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/rain-glass` — the `rain-glass` effect alone (weather pack): `import { registerRainGlass } from 'motionary/effects/rain-glass'; registerRainGlass();` then <usa-fx effect="rain-glass"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { WEATHER_FX } from '../../components/fx2/weather';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ WEATHER_FX.find((d) => d.name === 'rain-glass')!;
/** Register only this effect (idempotent). */
export function registerRainGlass(): void {
  registerEffects([effect]);
}
export { registerRainGlass as register };
