// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/reaction-burst` — the `reaction-burst` effect alone (social pack): `import { registerReactionBurst } from 'motionary/effects/reaction-burst'; registerReactionBurst();` then <usa-fx effect="reaction-burst"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SOCIAL_FX } from '../../components/fx2/social';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ SOCIAL_FX.find((d) => d.name === 'reaction-burst')!;
/** Register only this effect (idempotent). */
export function registerReactionBurst(): void {
  registerEffects([effect]);
}
export { registerReactionBurst as register };
