// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/read-receipt` — the `read-receipt` effect alone (social pack): `import { registerReadReceipt } from 'motionary/effects/read-receipt'; registerReadReceipt();` then <usa-fx effect="read-receipt"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SOCIAL_FX } from '../../components/fx2/social';

/** The effect definition. */
export const effect: EffectDefinition = SOCIAL_FX.find((d) => d.name === 'read-receipt')!;
/** Register only this effect (idempotent). */
export function registerReadReceipt(): void {
  registerEffects([effect]);
}
export { registerReadReceipt as register };
