// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/refraction` — the `refraction` effect alone (light pack): `import { registerRefraction } from 'motionary/effects/refraction'; registerRefraction();` then <usa-fx effect="refraction"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { LIGHT_FX } from '../../components/fx2/light';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ LIGHT_FX.find((d) => d.name === 'refraction')!;
/** Register only this effect (idempotent). */
export function registerRefraction(): void {
  registerEffects([effect]);
}
export { registerRefraction as register };
