// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/ring-sweep` — the `ring-sweep` effect alone (chart pack): `import { registerRingSweep } from 'motionary/effects/ring-sweep'; registerRingSweep();` then <usa-fx effect="ring-sweep"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { CHART_FX } from '../../components/fx2/chart';

/** The effect definition. */
export const effect: EffectDefinition = CHART_FX.find((d) => d.name === 'ring-sweep')!;
/** Register only this effect (idempotent). */
export function registerRingSweep(): void {
  registerEffects([effect]);
}
export { registerRingSweep as register };
