// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/ripple-dissolve` — the `ripple-dissolve` effect alone (transitions pack): `import { registerRippleDissolve } from 'motionary/effects/ripple-dissolve'; registerRippleDissolve();` then <usa-fx effect="ripple-dissolve"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { TRANSITIONS2_FX } from '../../components/fx2/transitions2';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ TRANSITIONS2_FX.find((d) => d.name === 'ripple-dissolve')!;
/** Register only this effect (idempotent). */
export function registerRippleDissolve(): void {
  registerEffects([effect]);
}
export { registerRippleDissolve as register };
