// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/rope` — the `rope` effect alone (physics pack): `import { registerRope } from 'motionary/effects/rope'; registerRope();` then <usa-fx effect="rope"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { PHYSICS2_FX } from '../../components/fx2/physics2';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ PHYSICS2_FX.find((d) => d.name === 'rope')!;
/** Register only this effect (idempotent). */
export function registerRope(): void {
  registerEffects([effect]);
}
export { registerRope as register };
