// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/route-draw` — the `route-draw` effect alone (geo pack): `import { registerRouteDraw } from 'motionary/effects/route-draw'; registerRouteDraw();` then <usa-fx effect="route-draw"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GEO_FX } from '../../components/fx2/geo';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ GEO_FX.find((d) => d.name === 'route-draw')!;
/** Register only this effect (idempotent). */
export function registerRouteDraw(): void {
  registerEffects([effect]);
}
export { registerRouteDraw as register };
