// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/safe-fade` — the `safe-fade` effect alone (safe pack): `import { registerSafeFade } from 'motionary/effects/safe-fade'; registerSafeFade();` then <usa-fx effect="safe-fade"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SAFE_FX } from '../../components/fx2/safemotion';

/** The effect definition. */
export const effect: EffectDefinition = SAFE_FX.find((d) => d.name === 'safe-fade')!;
/** Register only this effect (idempotent). */
export function registerSafeFade(): void {
  registerEffects([effect]);
}
export { registerSafeFade as register };
