// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/sakura` — the `sakura` effect alone (gpu pack): `import { registerSakura } from 'motionary/effects/sakura'; registerSakura();` then <usa-fx effect="sakura"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GPU_FX } from '../../components/fx2/gpu';

/** The effect definition. */
export const effect: EffectDefinition = GPU_FX.find((d) => d.name === 'sakura')!;
/** Register only this effect (idempotent). */
export function registerSakura(): void {
  registerEffects([effect]);
}
export { registerSakura as register };
