// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/sale-shine` — the `sale-shine` effect alone (shop pack): `import { registerSaleShine } from 'motionary/effects/sale-shine'; registerSaleShine();` then <usa-fx effect="sale-shine"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SHOP_FX } from '../../components/fx2/shop';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ SHOP_FX.find((d) => d.name === 'sale-shine')!;
/** Register only this effect (idempotent). */
export function registerSaleShine(): void {
  registerEffects([effect]);
}
export { registerSaleShine as register };
