// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/sankey-flow` — the `sankey-flow` effect alone (chart pack): `import { registerSankeyFlow } from 'motionary/effects/sankey-flow'; registerSankeyFlow();` then <usa-fx effect="sankey-flow"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { CHART_FX } from '../../components/fx2/chart';

/** The effect definition. */
export const effect: EffectDefinition = CHART_FX.find((d) => d.name === 'sankey-flow')!;
/** Register only this effect (idempotent). */
export function registerSankeyFlow(): void {
  registerEffects([effect]);
}
export { registerSankeyFlow as register };
