// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/scanline-sweep` — the `scanline-sweep` effect alone (cyber pack): `import { registerScanlineSweep } from 'motionary/effects/scanline-sweep'; registerScanlineSweep();` then <usa-fx effect="scanline-sweep"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { CYBER_FX } from '../../components/fx2/cyber';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ CYBER_FX.find((d) => d.name === 'scanline-sweep')!;
/** Register only this effect (idempotent). */
export function registerScanlineSweep(): void {
  registerEffects([effect]);
}
export { registerScanlineSweep as register };
