// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/shatter` — the `shatter` effect alone (transitions pack): `import { registerShatter } from 'motionary/effects/shatter'; registerShatter();` then <usa-fx effect="shatter"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { TRANSITIONS2_FX } from '../../components/fx2/transitions2';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ TRANSITIONS2_FX.find((d) => d.name === 'shatter')!;
/** Register only this effect (idempotent). */
export function registerShatter(): void {
  registerEffects([effect]);
}
export { registerShatter as register };
