// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/smoke` — the `smoke` effect alone (gpu pack): `import { registerSmoke } from 'motionary/effects/smoke'; registerSmoke();` then <usa-fx effect="smoke"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GPU_FX } from '../../components/fx2/gpu';

/** The effect definition. */
export const effect: EffectDefinition = GPU_FX.find((d) => d.name === 'smoke')!;
/** Register only this effect (idempotent). */
export function registerSmoke(): void {
  registerEffects([effect]);
}
export { registerSmoke as register };
