// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/snowfall` — the `snowfall` effect alone (weather pack): `import { registerSnowfall } from 'motionary/effects/snowfall'; registerSnowfall();` then <usa-fx effect="snowfall"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { WEATHER_FX } from '../../components/fx2/weather';

/** The effect definition. */
export const effect: EffectDefinition = WEATHER_FX.find((d) => d.name === 'snowfall')!;
/** Register only this effect (idempotent). */
export function registerSnowfall(): void {
  registerEffects([effect]);
}
export { registerSnowfall as register };
