// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/soft-body` — the `soft-body` effect alone (physics pack): `import { registerSoftBody } from 'motionary/effects/soft-body'; registerSoftBody();` then <usa-fx effect="soft-body"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { PHYSICS2_FX } from '../../components/fx2/physics2';

/** The effect definition. */
export const effect: EffectDefinition = PHYSICS2_FX.find((d) => d.name === 'soft-body')!;
/** Register only this effect (idempotent). */
export function registerSoftBody(): void {
  registerEffects([effect]);
}
export { registerSoftBody as register };
