// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/sound-particles` — the `sound-particles` effect alone (music pack): `import { registerSoundParticles } from 'motionary/effects/sound-particles'; registerSoundParticles();` then <usa-fx effect="sound-particles"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { MUSIC_FX } from '../../components/fx2/music';

/** The effect definition. */
export const effect: EffectDefinition = MUSIC_FX.find((d) => d.name === 'sound-particles')!;
/** Register only this effect (idempotent). */
export function registerSoundParticles(): void {
  registerEffects([effect]);
}
export { registerSoundParticles as register };
