// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/spatial-float` — the `spatial-float` effect alone (spatial pack): `import { registerSpatialFloat } from 'motionary/effects/spatial-float'; registerSpatialFloat();` then <usa-fx effect="spatial-float"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SPATIAL_FX } from '../../components/fx2/spatial';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ SPATIAL_FX.find((d) => d.name === 'spatial-float')!;
/** Register only this effect (idempotent). */
export function registerSpatialFloat(): void {
  registerEffects([effect]);
}
export { registerSpatialFloat as register };
