// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/spectrum-mirror` — the `spectrum-mirror` effect alone (music pack): `import { registerSpectrumMirror } from 'motionary/effects/spectrum-mirror'; registerSpectrumMirror();` then <usa-fx effect="spectrum-mirror"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { MUSIC_FX } from '../../components/fx2/music';

/** The effect definition. */
export const effect: EffectDefinition = MUSIC_FX.find((d) => d.name === 'spectrum-mirror')!;
/** Register only this effect (idempotent). */
export function registerSpectrumMirror(): void {
  registerEffects([effect]);
}
export { registerSpectrumMirror as register };
