// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/splash` — the `splash` effect alone (gpu pack): `import { registerSplash } from 'motionary/effects/splash'; registerSplash();` then <usa-fx effect="splash"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GPU_FX } from '../../components/fx2/gpu';

/** The effect definition. */
export const effect: EffectDefinition = GPU_FX.find((d) => d.name === 'splash')!;
/** Register only this effect (idempotent). */
export function registerSplash(): void {
  registerEffects([effect]);
}
export { registerSplash as register };
