// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/spooky-float` — the `spooky-float` effect alone (festival pack): `import { registerSpookyFloat } from 'motionary/effects/spooky-float'; registerSpookyFloat();` then <usa-fx effect="spooky-float"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { FESTIVAL_FX } from '../../components/fx2/festival';

/** The effect definition. */
export const effect: EffectDefinition = FESTIVAL_FX.find((d) => d.name === 'spooky-float')!;
/** Register only this effect (idempotent). */
export function registerSpookyFloat(): void {
  registerEffects([effect]);
}
export { registerSpookyFloat as register };
