// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/stock-pulse` — the `stock-pulse` effect alone (shop pack): `import { registerStockPulse } from 'motionary/effects/stock-pulse'; registerStockPulse();` then <usa-fx effect="stock-pulse"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SHOP_FX } from '../../components/fx2/shop';

/** The effect definition. */
export const effect: EffectDefinition = SHOP_FX.find((d) => d.name === 'stock-pulse')!;
/** Register only this effect (idempotent). */
export function registerStockPulse(): void {
  registerEffects([effect]);
}
export { registerStockPulse as register };
