// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/stream-text` — the `stream-text` effect alone (ai pack): `import { registerStreamText } from 'motionary/effects/stream-text'; registerStreamText();` then <usa-fx effect="stream-text"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { AI_FX } from '../../components/fx2/ai';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ AI_FX.find((d) => d.name === 'stream-text')!;
/** Register only this effect (idempotent). */
export function registerStreamText(): void {
  registerEffects([effect]);
}
export { registerStreamText as register };
