// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/stroke-draw` — the `stroke-draw` effect alone (morph pack): `import { registerStrokeDraw } from 'motionary/effects/stroke-draw'; registerStrokeDraw();` then <usa-fx effect="stroke-draw"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { MORPH2_FX } from '../../components/fx2/morph2';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ MORPH2_FX.find((d) => d.name === 'stroke-draw')!;
/** Register only this effect (idempotent). */
export function registerStrokeDraw(): void {
  registerEffects([effect]);
}
export { registerStrokeDraw as register };
