// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/success-check` — the `success-check` effect alone (focus pack): `import { registerSuccessCheck } from 'motionary/effects/success-check'; registerSuccessCheck();` then <usa-fx effect="success-check"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { FOCUS_FX } from '../../components/fx2/focus';

/** The effect definition. */
export const effect: EffectDefinition = FOCUS_FX.find((d) => d.name === 'success-check')!;
/** Register only this effect (idempotent). */
export function registerSuccessCheck(): void {
  registerEffects([effect]);
}
export { registerSuccessCheck as register };
