// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/swipe-hint` — the `swipe-hint` effect alone (gesture3 pack): `import { registerSwipeHint } from 'motionary/effects/swipe-hint'; registerSwipeHint();` then <usa-fx effect="swipe-hint"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GESTURE3_FX } from '../../components/fx2/gesture3';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ GESTURE3_FX.find((d) => d.name === 'swipe-hint')!;
/** Register only this effect (idempotent). */
export function registerSwipeHint(): void {
  registerEffects([effect]);
}
export { registerSwipeHint as register };
