// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/text-trail` — the `text-trail` effect alone (text pack): `import { registerTextTrail } from 'motionary/effects/text-trail'; registerTextTrail();` then <usa-fx effect="text-trail"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { TEXT3_FX } from '../../components/fx2/text3';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ TEXT3_FX.find((d) => d.name === 'text-trail')!;
/** Register only this effect (idempotent). */
export function registerTextTrail(): void {
  registerEffects([effect]);
}
export { registerTextTrail as register };
