// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/thinking-glow` — the `thinking-glow` effect alone (ai pack): `import { registerThinkingGlow } from 'motionary/effects/thinking-glow'; registerThinkingGlow();` then <usa-fx effect="thinking-glow"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { AI_FX } from '../../components/fx2/ai';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ AI_FX.find((d) => d.name === 'thinking-glow')!;
/** Register only this effect (idempotent). */
export function registerThinkingGlow(): void {
  registerEffects([effect]);
}
export { registerThinkingGlow as register };
