// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/tilt-wobble` — the `tilt-wobble` effect alone (gesture3 pack): `import { registerTiltWobble } from 'motionary/effects/tilt-wobble'; registerTiltWobble();` then <usa-fx effect="tilt-wobble"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GESTURE3_FX } from '../../components/fx2/gesture3';

/** The effect definition. */
export const effect: EffectDefinition = GESTURE3_FX.find((d) => d.name === 'tilt-wobble')!;
/** Register only this effect (idempotent). */
export function registerTiltWobble(): void {
  registerEffects([effect]);
}
export { registerTiltWobble as register };
