// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/typing-dots` — the `typing-dots` effect alone (social pack): `import { registerTypingDots } from 'motionary/effects/typing-dots'; registerTypingDots();` then <usa-fx effect="typing-dots"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SOCIAL_FX } from '../../components/fx2/social';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ SOCIAL_FX.find((d) => d.name === 'typing-dots')!;
/** Register only this effect (idempotent). */
export function registerTypingDots(): void {
  registerEffects([effect]);
}
export { registerTypingDots as register };
