// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/underline-sweep` — the `underline-sweep` effect alone (safe pack): `import { registerUnderlineSweep } from 'motionary/effects/underline-sweep'; registerUnderlineSweep();` then <usa-fx effect="underline-sweep"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { SAFE_FX } from '../../components/fx2/safemotion';

/** The effect definition. */
export const effect: EffectDefinition = SAFE_FX.find((d) => d.name === 'underline-sweep')!;
/** Register only this effect (idempotent). */
export function registerUnderlineSweep(): void {
  registerEffects([effect]);
}
export { registerUnderlineSweep as register };
