// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/vhs-glitch` — the `vhs-glitch` effect alone (retro pack): `import { registerVhsGlitch } from 'motionary/effects/vhs-glitch'; registerVhsGlitch();` then <usa-fx effect="vhs-glitch"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { RETRO_FX } from '../../components/fx2/retro2';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ RETRO_FX.find((d) => d.name === 'vhs-glitch')!;
/** Register only this effect (idempotent). */
export function registerVhsGlitch(): void {
  registerEffects([effect]);
}
export { registerVhsGlitch as register };
