// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/vine-grow` — the `vine-grow` effect alone (organic pack): `import { registerVineGrow } from 'motionary/effects/vine-grow'; registerVineGrow();` then <usa-fx effect="vine-grow"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { ORGANIC_FX } from '../../components/fx2/organic';

/** The effect definition. */
export const effect: EffectDefinition = ORGANIC_FX.find((d) => d.name === 'vine-grow')!;
/** Register only this effect (idempotent). */
export function registerVineGrow(): void {
  registerEffects([effect]);
}
export { registerVineGrow as register };
