// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/vinyl-spin` — the `vinyl-spin` effect alone (music pack): `import { registerVinylSpin } from 'motionary/effects/vinyl-spin'; registerVinylSpin();` then <usa-fx effect="vinyl-spin"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { MUSIC_FX } from '../../components/fx2/music';

/** The effect definition. */
export const effect: EffectDefinition = MUSIC_FX.find((d) => d.name === 'vinyl-spin')!;
/** Register only this effect (idempotent). */
export function registerVinylSpin(): void {
  registerEffects([effect]);
}
export { registerVinylSpin as register };
