// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/voice-wave` — the `voice-wave` effect alone (ai pack): `import { registerVoiceWave } from 'motionary/effects/voice-wave'; registerVoiceWave();` then <usa-fx effect="voice-wave"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { AI_FX } from '../../components/fx2/ai';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ AI_FX.find((d) => d.name === 'voice-wave')!;
/** Register only this effect (idempotent). */
export function registerVoiceWave(): void {
  registerEffects([effect]);
}
export { registerVoiceWave as register };
