// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/water-drop` — the `water-drop` effect alone (organic pack): `import { registerWaterDrop } from 'motionary/effects/water-drop'; registerWaterDrop();` then <usa-fx effect="water-drop"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { ORGANIC_FX } from '../../components/fx2/organic';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ ORGANIC_FX.find((d) => d.name === 'water-drop')!;
/** Register only this effect (idempotent). */
export function registerWaterDrop(): void {
  registerEffects([effect]);
}
export { registerWaterDrop as register };
