// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/watercolor` — the `watercolor` effect alone (paper pack): `import { registerWatercolor } from 'motionary/effects/watercolor'; registerWatercolor();` then <usa-fx effect="watercolor"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { PAPER_FX } from '../../components/fx2/paper';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ PAPER_FX.find((d) => d.name === 'watercolor')!;
/** Register only this effect (idempotent). */
export function registerWatercolor(): void {
  registerEffects([effect]);
}
export { registerWatercolor as register };
