// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/waveform-scope` — the `waveform-scope` effect alone (music pack): `import { registerWaveformScope } from 'motionary/effects/waveform-scope'; registerWaveformScope();` then <usa-fx effect="waveform-scope"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { MUSIC_FX } from '../../components/fx2/music';

/** The effect definition. */
export const effect: EffectDefinition = MUSIC_FX.find((d) => d.name === 'waveform-scope')!;
/** Register only this effect (idempotent). */
export function registerWaveformScope(): void {
  registerEffects([effect]);
}
export { registerWaveformScope as register };
