// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/xmas-snow` — the `xmas-snow` effect alone (festival pack): `import { registerXmasSnow } from 'motionary/effects/xmas-snow'; registerXmasSnow();` then <usa-fx effect="xmas-snow"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { FESTIVAL_FX } from '../../components/fx2/festival';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ FESTIVAL_FX.find((d) => d.name === 'xmas-snow')!;
/** Register only this effect (idempotent). */
export function registerXmasSnow(): void {
  registerEffects([effect]);
}
export { registerXmasSnow as register };
