// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/xp-gain` — the `xp-gain` effect alone (game pack): `import { registerXpGain } from 'motionary/effects/xp-gain'; registerXpGain();` then <usa-fx effect="xp-gain"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { GAME_FX } from '../../components/fx2/game';

/** The effect definition. */
export const effect: EffectDefinition = GAME_FX.find((d) => d.name === 'xp-gain')!;
/** Register only this effect (idempotent). */
export function registerXpGain(): void {
  registerEffects([effect]);
}
export { registerXpGain as register };
