// Generated by scripts/gen-entries.mjs — do not edit.
/** `motionary/effects/y2k-shine` — the `y2k-shine` effect alone (retro pack): `import { registerY2kShine } from 'motionary/effects/y2k-shine'; registerY2kShine();` then <usa-fx effect="y2k-shine"> (defineFx from motionary/components/fx). */
import { registerEffects, type EffectDefinition } from '../../components/fx/registry';
import { RETRO_FX } from '../../components/fx2/retro2';

/** The effect definition. */
export const effect: EffectDefinition = /*#__PURE__*/ RETRO_FX.find((d) => d.name === 'y2k-shine')!;
/** Register only this effect (idempotent). */
export function registerY2kShine(): void {
  registerEffects([effect]);
}
export { registerY2kShine as register };
