import { C, K } from './make.js';

export const category = K('cards', '▭', 'Card effects', '卡片效果',
  'One <usa-card> with combinable effects — flip, holographic foil, glass, glowing and conic borders, lift, spotlight, sheen, parallax layers, expand to detail — plus swipeable decks, sticky stacks and a 3D carousel.',
  '一个 <usa-card>，效果可自由组合——翻转、全息镭射、玻璃、发光与流光边框、悬浮、聚光、扫光、视差分层、展开详情——另有可滑动卡堆、滚动堆叠与 3D 轮播。');

const face = (t, cls = 'demo-face') => `<div class="${cls}">${t}</div>`;

export const components = [
  C('usa-card', 'cards', 'Card', '卡片',
    'Ten card effects you can combine (effect="lift sheen"): flip (hover or click, x/y axis), holo, glass, border-glow, conic-border, lift, spotlight, sheen, parallax-layers and expand (card → detail with FLIP + spring).',
    '十种可组合的卡片效果（effect="lift sheen"）：翻转（悬停或点击，X/Y 轴）、全息、玻璃、边框光晕、流光边框、悬浮、聚光、扫光、视差分层、展开详情（FLIP + 弹簧）。',
    ['flip', 'holo', 'glass', 'expand', 'combinable'],
    '<usa-card effect="lift sheen">\n  <h3>Pro plan</h3>\n</usa-card>\n<usa-card effect="flip" trigger="click">\n  <div data-front>Front</div>\n  <div data-back>Back</div>\n</usa-card>\n<usa-card effect="expand">\n  <h3>Title</h3>\n  <div data-detail>Long text… <button data-close>Close</button></div>\n</usa-card>',
    `<usa-card class="demo-card" effect="lift sheen">${face('Hover me')}</usa-card>`,
    { controls: [{ key: 'effect', values: ['lift sheen', 'holo', 'glass', 'border-glow', 'conic-border', 'spotlight', 'parallax-layers', 'lift', 'sheen'] }] }),
  C('usa-card', 'cards', 'Flip card', '翻转卡片',
    'Front and back faces ([data-front] / [data-back]) flip in 3D on hover, or on click / Enter with trigger="click". axis="x" flips vertically. Reduced motion cross-fades.',
    '正反两面（[data-front] / [data-back]）在悬停时 3D 翻转，trigger="click" 时点击或回车翻转。axis="x" 为纵向翻转。减少动态效果时为淡入淡出。',
    ['flip', '3D', 'keyboard'],
    '<usa-card effect="flip" trigger="click" axis="y">\n  <div data-front>Front</div>\n  <div data-back>Back</div>\n</usa-card>',
    `<usa-card class="demo-card" effect="flip" trigger="click">${face('Click to flip', 'demo-face')}<div class="demo-face demo-face-back" data-back>Back ✦</div></usa-card>`.replace('<div class="demo-face">Click', '<div class="demo-face" data-front>Click'),
    { id: 'card-flip', controls: [{ key: 'axis', values: ['y', 'x'] }] }),
  C('usa-card', 'cards', 'Expand to detail', '展开详情',
    'Click a card and it grows into a full detail view with a spring (FLIP); [data-detail] content appears. Esc, the backdrop or [data-close] collapses it back into place.',
    '点击卡片，它会以弹簧（FLIP）放大为完整详情视图并显示 [data-detail] 内容；按 Esc、点击背景或 [data-close] 收回原位。',
    ['FLIP', 'spring', 'detail'],
    '<usa-card effect="expand">\n  <h3>Title</h3>\n  <div data-detail>…<button data-close>Close</button></div>\n</usa-card>',
    `<usa-card class="demo-card" effect="expand lift"><div class="demo-face">Open me ⤢</div><div data-detail class="demo-detail-body"><p>Detail view. Press Esc or</p><button class="demo-btn" type="button" data-close>Close</button></div></usa-card>`,
    { id: 'card-expand' }),
  C('usa-card-stack', 'cards', 'Swipe stack', '滑动卡堆',
    'A deck where the top card swipes away left or right (pointer, touch, arrow keys) and the next springs forward. loop sends cards to the back.',
    '卡堆顶部的卡片可向左或向右滑走（指针、触摸、方向键），下一张以弹簧前移。loop 让卡片回到底部循环。',
    ['swipe', 'tinder', 'spring'],
    '<usa-card-stack loop>\n  <article>1</article>\n  <article>2</article>\n  <article>3</article>\n</usa-card-stack>',
    `<usa-card-stack class="demo-deck" loop>${['A', 'B', 'C', 'D'].map((t) => face(t, 'demo-face demo-face-' + t.toLowerCase())).join('')}</usa-card-stack>`),
  C('usa-sticky-stack', 'cards', 'Sticky stack', '滚动堆叠',
    'Cards stick while you scroll and the covered ones shrink and dim as the next slides over them.',
    '滚动时卡片吸顶，被覆盖的卡片随下一张滑上来而缩小变暗。',
    ['sticky', 'scroll'],
    '<usa-sticky-stack top="80">\n  <section>One</section>\n  <section>Two</section>\n  <section>Three</section>\n</usa-sticky-stack>',
    '<a class="demo-jump" href="#sticky-demo"><span>Live demo below</span><b aria-hidden="true">↓</b></a>'),
  C('usa-carousel-3d', 'cards', '3D carousel', '3D 轮播',
    'Items on a 3D ring, rotated by drag, arrow keys, clicks or autoplay — with spring motion. Reduced motion shows one flat item at a time.',
    '元素排列在 3D 圆环上，可拖拽、方向键、点击或自动播放旋转，带弹簧运动。减少动态效果时一次只显示一个平面元素。',
    ['3D', 'carousel', 'spring'],
    '<usa-carousel-3d autoplay="3000">\n  <img src="1.jpg" alt="">\n  <img src="2.jpg" alt="">\n  …\n</usa-carousel-3d>',
    `<usa-carousel-3d class="demo-c3d">${['1', '2', '3', '4', '5', '6'].map((t) => face(t, 'demo-face demo-face-sm')).join('')}</usa-carousel-3d>`),
];
