import { C, H, K } from './make.js';

export const category = K('fx', '✨', 'Effects (plugin API)', '特效（插件 API）',
  'One way to register and play every effect (5.0): registerEffect({ name, kind, run }), playEffect(el, name), bindEffect(el, name, { trigger }) or <usa-fx effect trigger>. Built-ins: every timeline entrance, attention seekers and click effects — reduced-motion safe.',
  '统一的效果注册与播放方式（5.0）：registerEffect({ name, kind, run })、playEffect(el, name)、bindEffect(el, name, { trigger }) 或 <usa-fx effect trigger>。内置：全部时间线入场效果、吸引注意效果与点击效果 —— 兼容“减少动态效果”。');

const FX = (id, en, zh, descEn, descZh, tags, usage, demo, controls, pack) => C('usa-fx', 'fx', en, zh, descEn, descZh, tags, usage, demo, { id, define: 'defineFx', controls, pack });
/** A 5.x effect-pack card (registers motionary/components/effects in its code). */
const PK = (id, en, zh, descEn, descZh, tags, usage, demo, controls) => FX(id, en, zh, descEn, descZh, tags, usage, demo, controls, true);
/** A 5.4 <usa-story> card (defineStory from motionary/components/effects). */
/** A 5.6 <usa-audio> card (defineAudio from motionary/components/effects). */
const AU = (id, en, zh, descEn, descZh, tags, usage, demo, controls) => C('usa-audio', 'fx', en, zh, descEn, descZh, tags, usage, demo, { id, define: 'defineAudio', entry: 'effects', pack: true, controls });
/** A 5.7 <usa-gesture-fx> card. */
const GX = (id, en, zh, descEn, descZh, tags, usage, demo, controls) => C('usa-gesture-fx', 'fx', en, zh, descEn, descZh, tags, usage, demo, { id, define: 'defineGestureFx', entry: 'effects', pack: true, controls });
/** A 5.8 <usa-motion-theme> card. */
const TH = (id, en, zh, descEn, descZh, tags, usage, demo, controls) => C('usa-motion-theme', 'fx', en, zh, descEn, descZh, tags, usage, demo, { id, define: 'defineTheme', entry: 'effects', pack: true, controls });
/** A 5.9 <usa-player> card. */
const PL = (id, en, zh, descEn, descZh, tags, usage, demo, controls) => C('usa-player', 'fx', en, zh, descEn, descZh, tags, usage, demo, { id, define: 'definePlayer', entry: 'effects', pack: true, controls });
const SC = (id, en, zh, descEn, descZh, tags, usage, demo, controls) => C('usa-story', 'fx', en, zh, descEn, descZh, tags, usage, demo, { id, define: 'defineStory', entry: 'effects', pack: true, controls });

export const components = [
  FX('fx', 'Attention seekers', '吸引注意', 
    '<usa-fx> plays any registered effect on its child: pulse, pop, jelly, wiggle, heartbeat, bounce, flash (≤ 2 per second), tada, shake. Click the button.',
    '<usa-fx> 在子元素上播放任意已注册效果：脉冲、弹出、果冻、摇摆、心跳、弹跳、闪烁（每秒 ≤ 2 次）、庆祝、抖动。点击按钮试试。',
    ['attention', 'pulse', 'jelly', 'bounce', 'tada'],
    '<usa-fx effect="jelly" trigger="click">\n  <button>Press me</button>\n</usa-fx>',
    '<usa-fx effect="jelly" trigger="click"><button type="button" class="demo-btn">Press me</button></usa-fx>',
    [{ key: 'effect', values: ['jelly', 'pop', 'pulse', 'wiggle', 'heartbeat', 'bounce', 'flash', 'tada', 'shake'] }]),
  FX('fx-click', 'Click effects', '点击特效',
    'Registered click effects — burst, confetti and ink ripple — start at the pointer.',
    '已注册的点击效果 —— 粒子爆裂、彩带与墨水涟漪 —— 从指针位置开始。',
    ['click', 'burst', 'confetti', 'ripple'],
    '<usa-fx effect="confetti">\n  <button>Celebrate</button>\n</usa-fx>',
    '<usa-fx effect="burst" trigger="click"><button type="button" class="demo-btn">Click</button></usa-fx>',
    [{ key: 'effect', values: ['burst', 'confetti', 'ripple'] }]),
  FX('fx-enter', 'Entrances on scroll', '滚动入场',
    'Every timeline preset is also an enter effect: trigger="enter" plays it when the element scrolls into view (once).',
    '每个时间线预设同时也是入场效果：trigger="enter" 在元素滚动进入视口时播放（一次）。',
    ['enter', 'reveal', 'fade-up', 'clip'],
    '<usa-fx effect="fade-up" trigger="enter">\n  <h2>Hello</h2>\n</usa-fx>',
    '<usa-fx effect="clip-up" trigger="enter"><div class="demo-tile">Hello</div></usa-fx>',
    [{ key: 'effect', values: ['clip-up', 'fade-up', 'fade-left', 'scale', 'blur', 'rotate', 'clip-right'] }]),
  PK('fx-holo', 'Holographic card', '全息镭射卡',
    '5.1: a rainbow foil sheen and 3D tilt follow the pointer (trigger="load" keeps it on). Under reduced motion the sheen stays static.',
    '5.1：彩虹镭射光泽与 3D 倾斜跟随指针（trigger="load" 常驻）。减少动态效果时光泽静止。',
    ['card', 'holographic', 'foil', 'tilt'],
    '<usa-fx effect="holo" trigger="load">\n  <article class="card">…</article>\n</usa-fx>',
    '<usa-fx effect="holo" trigger="load"><div class="demo-tile demo-holo">✦ Rare card</div></usa-fx>'),
  PK('fx-card-moves', 'Card moves', '卡片动作',
    '5.1: glare sweep, book-open peek, card fan (children spread like a hand of cards), topple-and-spring — hover the card.',
    '5.1：扫光、翻书窥视、卡牌扇形展开（子元素像手牌一样散开）、倾倒回弹 —— 悬停卡片试试。',
    ['card', 'glare', 'book', 'fan', 'topple'],
    '<usa-fx effect="glare-sweep" trigger="hover">\n  <article class="card">…</article>\n</usa-fx>',
    '<usa-fx effect="card-fan" trigger="hover"><div class="demo-row demo-fan"><span class="demo-pill">A</span><span class="demo-pill">K</span><span class="demo-pill">Q</span><span class="demo-pill">J</span></div></usa-fx>',
    [{ key: 'effect', values: ['card-fan', 'glare-sweep', 'book-open', 'topple', 'jelly', 'tada'] }]),
  PK('fx-click2', 'Click effects 2.0', '点击特效 2.0',
    '5.1: shockwave rings, ink splash, spinning star burst, jelly press, water ring ripple and emoji rain — all from the click point.',
    '5.1：冲击波环、墨水飞溅、旋转星星爆裂、果冻按压、水波环涟漪与表情雨 —— 全部从点击处发出。',
    ['click', 'shockwave', 'ink', 'stars', 'emoji'],
    '<usa-fx effect="shockwave">\n  <button>Boom</button>\n</usa-fx>',
    '<usa-fx effect="shockwave"><button type="button" class="demo-btn">Click me</button></usa-fx>',
    [{ key: 'effect', values: ['shockwave', 'ink-splash', 'star-burst', 'jelly-press', 'ring-ripple', 'emoji-rain'] }]),
  PK('fx-physics', 'Bounce & physics', '弹跳与物理',
    '5.2: spring-solved bounce-in, rubber band, drop-and-bounce under gravity, damped bell swing — click the button.',
    '5.2：弹簧求解的弹入、橡皮筋、重力掉落回弹、阻尼摇摆铃铛 —— 点击按钮试试。',
    ['physics', 'spring', 'bounce', 'gravity', 'bell'],
    '<usa-fx effect="drop-bounce" trigger="enter">\n  <img src="badge.svg" alt="New">\n</usa-fx>',
    '<usa-fx effect="bounce-in"><button type="button" class="demo-btn">🔔 Play</button></usa-fx>',
    [{ key: 'effect', values: ['bounce-in', 'rubber-band', 'drop-bounce', 'bell-swing'] }]),
  PK('fx-gravity-text', 'Gravity text', '重力文字',
    '5.2: every character drops in under gravity and bounces, staggered; the text keeps an aria-label.',
    '5.2：每个字符在重力下逐个掉落并回弹；文本保留 aria-label。',
    ['text', 'gravity', 'bounce', 'stagger'],
    '<usa-fx effect="gravity-text" trigger="enter">\n  <h2>Falling letters</h2>\n</usa-fx>',
    '<usa-fx effect="gravity-text" trigger="hover"><p class="demo-split-line">Falling letters</p></usa-fx>'),
  PK('fx-spring-hover', 'Elastic hover & spring follow', '弹性悬停与弹簧跟随',
    '5.2: elastic-hover lifts with a springy overshoot; spring-follow chases the pointer across its parent (both persistent, trigger="load").',
    '5.2：elastic-hover 悬停时带弹性回弹地抬起；spring-follow 在父元素内弹簧般追随指针（均为常驻，trigger="load"）。',
    ['hover', 'spring', 'follow', 'cursor'],
    '<usa-fx effect="spring-follow" trigger="load">\n  <span class="dot"></span>\n</usa-fx>',
    '<usa-fx effect="elastic-hover" trigger="load"><div class="demo-tile">Hover me</div></usa-fx>',
    [{ key: 'effect', values: ['elastic-hover', 'spring-follow'] }]),
  PK('fx-page-transitions', 'Page transitions', '页面转场',
    '5.3: curtain, iris (closes on the click point), pixel dissolve and venetian blinds — cover the page, call onCovered() (swap your route there), then reveal. Reduced motion: a quick cross-fade.',
    '5.3：幕布、光圈（向点击处收拢）、像素溶解、百叶窗 —— 覆盖页面后调用 onCovered()（在此切换路由），再揭开。减少动态效果时为快速淡入淡出。',
    ['page', 'transition', 'curtain', 'iris', 'pixel', 'blinds'],
    "<usa-fx effect=\"iris\">\n  <a href=\"/next\">Next page</a>\n</usa-fx>\n\n<script type=\"module\">\n  playEffect(document.body, 'curtain', { onCovered: () => router.go('/next') });\n</script>",
    '<usa-fx effect="iris"><button type="button" class="demo-btn">Play transition</button></usa-fx>',
    [{ key: 'effect', values: ['iris', 'curtain', 'pixel-dissolve', 'blinds'] }]),
  PK('fx-page-scroll', 'Velocity skew & edge glow', '滚动速度倾斜与边缘光晕',
    '5.3: velocity-skew leans the element with scroll speed; edge-glow lights the viewport edge you scroll toward; spotlight dims everything but a circle at the pointer (all persistent, trigger="load") — scroll the page.',
    '5.3：velocity-skew 随滚动速度倾斜元素；edge-glow 点亮滚动方向的视口边缘；spotlight 让页面变暗、仅指针处一圈明亮（均为常驻，trigger="load"）—— 滚动页面试试。',
    ['page', 'scroll', 'velocity', 'skew', 'glow', 'spotlight'],
    '<usa-fx effect="velocity-skew" trigger="load">\n  <section class="gallery">…</section>\n</usa-fx>',
    '<usa-fx effect="velocity-skew" trigger="load"><div class="demo-tile">Scroll the page ↕</div></usa-fx>',
    [{ key: 'effect', values: ['velocity-skew', 'edge-glow'] }]),
  SC('story-compare', 'Story: before / after', '叙事：前后对比',
    '5.4: <usa-story template="compare"> wipes from before to after as you scroll; the handle is draggable and a keyboard slider (←/→, Home/End). Full-page templates (pin, gallery, zoom) live on the Scroll stories page.',
    '5.4：<usa-story template="compare"> 随滚动从“之前”擦到“之后”；分隔把手可拖动，也是键盘滑块（←/→、Home/End）。整页模板（pin、gallery、zoom）见“滚动叙事”页面。',
    ['story', 'scrollytelling', 'compare', 'before after', 'slider'],
    '<usa-story template="compare" label="2019 vs 2026">\n  <div data-sticky>\n    <img data-before src="before.jpg" alt="Before">\n    <img data-after src="after.jpg" alt="After">\n  </div>\n</usa-story>',
    '<usa-story template="compare" style="--usa-story-h:150px"><div data-sticky style="position:relative;border-radius:12px"><div data-before class="demo-tile" style="height:100%;background:#334155">Before</div><div data-after class="demo-tile" style="height:100%;background:#7c5cff;text-align:right">After</div></div></usa-story>'),
  SC('story-counter', 'Story: data counters', '叙事：数据计数器',
    '5.4: template="counter" counts every [data-count] up (easing out, separators and prefix/suffix kept) when it scrolls into view; screen readers get the final value.',
    '5.4：template="counter" 让每个 [data-count] 在进入视口时递增计数（缓出，保留千分位与前后缀）；读屏器直接读到最终值。',
    ['story', 'counter', 'numbers', 'data story'],
    '<usa-story template="counter">\n  <strong data-count="12,480">0</strong> users\n  <strong data-count="99.9%">0</strong> uptime\n</usa-story>',
    '<usa-story template="counter"><div class="demo-row"><span class="demo-pill" data-count="12,480">0</span><span class="demo-pill" data-count="99.9%">0</span><span class="demo-pill" data-count="$4.2">0</span></div></usa-story>'),
  SC('story-highlight', 'Story: step highlight', '叙事：逐段高亮',
    '5.4: template="highlight" dims every paragraph except the one crossing the viewport center (pin does the same for [data-step] sections next to a sticky [data-stage]); fires usa-story-step.',
    '5.4：template="highlight" 让穿过视口中线的段落高亮、其余变暗（pin 模板对 [data-step] 章节做同样处理，并固定 [data-stage]）；触发 usa-story-step 事件。',
    ['story', 'highlight', 'pin', 'steps', 'scrollytelling'],
    '<usa-story template="pin">\n  <figure data-stage>…chart…</figure>\n  <section data-step>Step 1</section>\n  <section data-step>Step 2</section>\n</usa-story>',
    '<usa-story template="highlight"><p class="demo-note">First, the idea.</p><p class="demo-note">Then the build.</p><p class="demo-note">Finally, the launch.</p></usa-story>'),
  PK('fx-generative', 'Generative backgrounds', '生成式背景',
    '5.5: flow field, Voronoi cells, mesh gradient, starfield, metaballs and topographic contours on Canvas 2D — rendered only while visible, with adaptive quality; one static frame under reduced motion.',
    '5.5：流场、Voronoi 细胞、网格渐变、星空、metaballs 与等高线 —— Canvas 2D 实现，仅在可见时渲染并自适应画质；减少动态效果时只绘制一帧静态画面。',
    ['background', 'generative', 'canvas', 'flow field', 'voronoi', 'mesh gradient', 'starfield', 'metaballs', 'contours'],
    '<usa-fx effect="mesh-gradient" trigger="load" self class="hero">\n  <h1>Hello</h1>\n</usa-fx>',
    '<usa-fx effect="mesh-gradient" trigger="load"><div class="demo-tile demo-gen">Generative</div></usa-fx>',
    [{ key: 'effect', values: ['mesh-gradient', 'flow-field', 'voronoi', 'starfield', 'metaballs', 'contours'] }]),
  PK('fx-audio', 'Sound-reactive backgrounds', '声音响应背景',
    '5.6: spectrum bars, pulse rings and a waveform ring driven by a Web Audio analyser (microphone, <audio>/<video> or a MediaStream via enableAudio()). They idle gently until audio is enabled; skipped under reduced motion.',
    '5.6：由 Web Audio 分析器驱动的频谱柱、脉冲光环与波形环（麦克风、<audio>/<video> 或 MediaStream，经 enableAudio() 开启）。开启音频前轻柔待机；减少动态效果时不运行。',
    ['audio', 'sound', 'music', 'spectrum', 'equalizer', 'visualizer', 'web audio', 'beat'],
    '<usa-fx effect="spectrum-bars" trigger="load" self options=\'{"mirror":true}\'>\n  <h2>Now playing</h2>\n</usa-fx>',
    '<usa-fx effect="spectrum-bars" trigger="load"><div class="demo-tile demo-gen">Sound</div></usa-fx>',
    [{ key: 'effect', values: ['spectrum-bars', 'pulse-ring', 'wave-ring'] }]),
  PK('fx-cursor', 'Cursor trails', '光标拖尾',
    '5.7: comet trail, rainbow ribbon, sparkle stars, magnetic dot grid and an easing spotlight — scoped to the element, mouse / pen only by default (touch: true to opt in), off under reduced motion.',
    '5.7：彗星拖尾、彩虹丝带、星光、磁吸点阵与缓动聚光光标 —— 仅作用于绑定元素，默认只响应鼠标 / 触控笔（touch: true 可启用触摸），减少动态效果时关闭。',
    ['cursor', 'trail', 'comet', 'sparkle', 'ribbon', 'magnetic', 'spotlight', 'pointer'],
    '<usa-fx effect="comet-trail" trigger="load" self>\n  <section class="hero">…</section>\n</usa-fx>',
    '<usa-fx effect="comet-trail" trigger="load"><div class="demo-tile demo-gen" style="background:#0b0d12">Move here</div></usa-fx>',
    [{ key: 'effect', values: ['comet-trail', 'ribbon-trail', 'sparkle-trail', 'magnetic-dots', 'spotlight-cursor'] }]),
  GX('fx-gesture', 'Gesture triggers', '手势触发',
    '5.7: <usa-gesture-fx> plays any registered effect on a fling (fast release), a two-finger twist or a long press that charges --usa-charge 0 → 1. JS: bindGesture(el, "fling", "tada").',
    '5.7：<usa-gesture-fx> 在甩动（快速松手）、双指旋转或长按蓄力（--usa-charge 0 → 1）时播放任意已注册效果。JS：bindGesture(el, "fling", "tada")。',
    ['gesture', 'fling', 'twist', 'rotate', 'long press', 'charge', 'touch'],
    '<usa-gesture-fx gesture="long-press" effect="tada">\n  <button>Hold me</button>\n</usa-gesture-fx>',
    '<usa-gesture-fx gesture="long-press" effect="tada"><button type="button" class="demo-btn demo-charge">Hold me</button></usa-gesture-fx>',
    [{ key: 'gesture', values: ['long-press', 'fling', 'twist'] }]),
  PK('fx-micro', 'Micro-interactions', '微交互',
    '5.8: 23 small interactions that also do the UI work — like / favourite / bookmark toggles (aria-pressed), copy to clipboard with "Copied ✓", password show / hide, download & submit progress (aria-busy), counters, upvote, clap, emoji reactions, refresh spin, trash, input shake (aria-invalid)…',
    '5.8：23 个同时完成界面状态的微交互 —— 点赞 / 收藏 / 书签切换（aria-pressed）、复制并显示“已复制 ✓”、密码显隐、下载与提交进度（aria-busy）、计数器、顶、鼓掌、表情回应、刷新旋转、删除、输入抖动（aria-invalid）……',
    ['micro-interaction', 'like', 'favorite', 'copy', 'password', 'download', 'progress', 'counter', 'toggle', 'shake'],
    '<usa-fx effect="like-heart" trigger="click">\n  <button aria-pressed="false">♥ <span data-count="12">12</span></button>\n</usa-fx>',
    '<usa-fx effect="like-heart" trigger="click"><button type="button" class="demo-btn" data-copy="npm i motionary">♥ <span data-count="12">12</span></button></usa-fx>',
    [{ key: 'effect', values: ['like-heart', 'favorite-star', 'bookmark-flip', 'toggle-morph', 'copy-success', 'download-progress', 'submit-loading', 'send-plane', 'add-to-cart', 'counter-bump', 'upvote', 'clap', 'emoji-react', 'refresh-spin', 'check-toggle', 'input-shake', 'error-flash', 'success-check', 'nudge-hint', 'focus-pulse', 'notify-badge'] }]),
  TH('fx-theme', 'Theme packs', '主题包',
    '5.8: <usa-motion-theme name> applies a theme pack — design tokens (--usa-theme-*), motion tokens and effect presets per role (enter / hover / click / attention / background). Neon, paper, glass, retro and brutalist; applyMotionTheme() for the whole page.',
    '5.8：<usa-motion-theme name> 应用主题包 —— 设计令牌（--usa-theme-*）、动效令牌与各角色的效果预设（入场 / 悬停 / 点击 / 吸引注意 / 背景）。霓虹、纸张、玻璃、复古、粗野主义；applyMotionTheme() 作用于整页。',
    ['theme', 'tokens', 'neon', 'paper', 'glass', 'retro', 'brutalist', 'design system'],
    '<usa-motion-theme name="neon">\n  <div class="usa-surface">\n    <button data-theme-fx="click">Tap</button>\n  </div>\n</usa-motion-theme>',
    '<usa-motion-theme name="neon" class="demo-theme"><div class="usa-surface demo-theme-card"><b class="usa-accent">Aa</b> <button type="button" class="demo-btn" data-theme-fx="click">Tap</button></div></usa-motion-theme>',
    [{ key: 'name', values: ['neon', 'paper', 'glass', 'retro', 'brutalist'] }]),
  PL('fx-player', 'JSON animation player', 'JSON 动画播放器',
    '5.9: <usa-player> plays a JSON animation — timeline presets, your own keyframes and any registered effect on a shared clock; play / pause / seek / rate / loop, scroll-scrubbing (trigger="scroll"). Export one from the Playground (<usa-player> JSON tab).',
    '5.9：<usa-player> 播放 JSON 动画 —— 时间线预设、自定义关键帧与任意已注册效果共用一个时钟；播放 / 暂停 / 跳转 / 倍速 / 循环，可随滚动拖动（trigger="scroll"）。可从动效实验室导出（<usa-player> JSON 标签）。',
    ['player', 'json', 'lottie', 'timeline', 'keyframes', 'scrub', 'export'],
    '<usa-player src="hero.json" trigger="view">\n  <h1>Title</h1>\n  <a class="cta">Start</a>\n</usa-player>',
    '<usa-player trigger="load" controls class="demo-player"><b class="pl-a">Title</b><span class="demo-btn pl-b">Button</span><i class="pl-c">subtitle</i><script type="application/json">{"format":"use-scroll-animate/animation","version":1,"loop":true,"tracks":[{"target":".pl-a","start":0,"duration":600,"preset":"fade-up"},{"target":".pl-b","start":300,"duration":600,"preset":"scale"},{"target":".pl-b","start":1000,"effect":"jelly"},{"target":".pl-c","start":700,"duration":700,"keyframes":[{"transform":"translateX(-40px)","opacity":0},{"transform":"none","opacity":1}]},{"target":":scope","start":2400,"duration":1,"preset":"fade"}]}</script></usa-player>',
    [{ key: 'trigger', values: ['load', 'click', 'view'] }]),
  AU('fx-audio-beat', 'Beat-triggered effects', '节拍触发特效',
    '5.6: <usa-audio> renders a toggle (a user gesture starts Web Audio), detects beats and plays any registered effect on children with data-usa-beat="effect". JS: bindBeat(el, "pop"). Beats play nothing under reduced motion.',
    '5.6：<usa-audio> 渲染一个开关按钮（由用户手势启动 Web Audio），检测节拍并在带 data-usa-beat="效果名" 的子元素上播放任意已注册效果。JS：bindBeat(el, "pop")。减少动态效果时节拍不触发动画。',
    ['audio', 'beat', 'microphone', 'music', 'sound', 'reactive'],
    '<audio id="track" src="song.mp3" controls></audio>\n<usa-audio source="#track" label="Play with visuals">\n  <div data-usa-beat="pop">♪</div>\n</usa-audio>',
    '<usa-audio source="mic" label="🎤 Use microphone"><div class="demo-tile" data-usa-beat="pop">♪ beat</div></usa-audio>'),
];

export const helpers = [
  H('register-effect', 'fx', 'registerEffect',
    'Add your own effect once and use it everywhere — playEffect(), bindEffect(), <usa-fx>. ctx.animate() already applies reduced motion, motion sensitivity, intensity and the animation budget.',
    '注册一次自定义效果，处处可用 —— playEffect()、bindEffect()、<usa-fx>。ctx.animate() 已自动处理减少动态效果、运动敏感度、强度与动画预算。',
    ['plugin', 'registry', 'custom effect'],
    "import { registerEffect, playEffect } from 'motionary/components/fx';\n\nregisterEffect({\n  name: 'spin-pop',\n  kind: 'attention',\n  run: (el, o, ctx) => ctx.animate(el, [{ transform: 'scale(1) rotate(0)' }, { transform: 'scale(1.2) rotate(180deg)' }, { transform: 'scale(1) rotate(360deg)' }], { duration: 700 }),\n});\nplayEffect(document.querySelector('.logo'), 'spin-pop');",
    '<div class="demo-row"><span class="demo-pill" data-fx-target>✦</span><button type="button" class="demo-link" data-fx-go>playEffect(el, "spin-pop")</button></div><p class="demo-note" data-fx-list></p>'),
];

export const wire = {
  'register-effect': (stage, lib) => {
    if (!lib.hasEffect('spin-pop'))
      lib.registerEffect({ name: 'spin-pop', kind: 'attention', run: (el, o, ctx) => ctx.animate(el, [{ transform: 'scale(1) rotate(0)' }, { transform: 'scale(1.3) rotate(180deg)' }, { transform: 'scale(1) rotate(360deg)' }], { duration: 700, easing: 'cubic-bezier(0.34,1.56,0.64,1)' }) });
    stage.querySelector('[data-fx-list]').textContent = `${lib.listEffects().length} effects registered`;
    stage.querySelector('[data-fx-go]').addEventListener('click', () => lib.playEffect(stage.querySelector('[data-fx-target]'), 'spin-pop'));
  },
};
