/**
 * 10.1+: the single source of truth for component prerequisites — Motionary's
 * own `motionary/runtime` modules and (from 10.6) official third-party runtimes
 * for formats we cannot implement ourselves. Pure data (no DOM): read by the
 * gallery cards, the Store (badge + detail), scripts/gen-runtime-docs.mjs (docs
 * pages + README section), scripts/gen-manifest.mjs (AI manifest) and
 * scripts/check-peer-docs.mjs (CI: all five places must carry every item).
 */
export const RUNTIME_CDN = 'https://cdn.jsdelivr.net/npm/motionary@11/dist/';
export const DOCS_BASE = 'https://github.com/HarrisonCN/Motionary/blob/main/';

const iife = (id) => (id === 'core' ? `${RUNTIME_CDN}runtime.iife.js` : `${RUNTIME_CDN}runtime/${id}.iife.js`);
const esm = (id) => (id === 'core' ? `${RUNTIME_CDN}runtime.js` : `${RUNTIME_CDN}runtime/${id}.js`);
const camel = (id) => id.replace(/-(\w)/g, (_, c) => c.toUpperCase());

/** A `motionary/runtime/<id>` module entry. */
const R = (id, title, summary, budget, exports, compat, example) => ({
  kind: 'runtime',
  id,
  label: id === 'core' ? 'motionary/runtime' : `motionary/runtime/${id}`,
  title,
  summary,
  install: 'npm i motionary',
  importPath: id === 'core' ? 'motionary/runtime' : `motionary/runtime/${id}`,
  import: id === 'core' ? "import { use } from 'motionary/runtime';" : `import { use } from 'motionary/runtime';\nimport { ${camel(id)} } from 'motionary/runtime/${id}';`,
  register: id === 'core' ? 'use();' : `use(${camel(id)});`,
  cdn: id === 'core' ? `<script src="${iife('core')}"></script>` : `<script src="${iife('core')}"></script>\n<script src="${iife(id)}"></script>`,
  cdnEsm: esm(id),
  order: id === 'core'
    ? 'Import motionary/runtime and call use() once at start-up, before any runtime-powered component mounts. CDN: the IIFE registers itself (window.MotionaryRuntime).'
    : `Register the core first, then the module: use(${camel(id)}) also registers the core. CDN: load runtime.iife.js, then ${id === 'core' ? '' : `runtime/${id}.iife.js`} (it registers itself).`,
  docs: `docs/runtime/${id}.md`,
  budget,
  exports,
  compat,
  example,
});

/** An official third-party runtime (optional peer dependency, lazy-loaded) — only for formats we cannot implement ourselves (10.6+). */
const P = (id, label, title, summary, install, imp, register, cdn, cdnEsm, order, why, exports, compat, example) => ({
  kind: 'peer',
  id,
  label,
  title,
  summary,
  install,
  importPath: label,
  import: imp,
  register,
  cdn,
  cdnEsm,
  order,
  why,
  docs: `docs/runtime/${id}.md`,
  budget: 0,
  exports,
  compat,
  example,
});

export const PREREQS = {
  core: R('core', 'Runtime core', 'Shared ticker (one rAF loop), tween + timeline engine with easing, module registry with clear errors.', 5632,
    ['use', 'requireModule', 'hasModule', 'getTicker', 'tween', 'timeline', 'Tween', 'Timeline', 'EASES', 'parseEase', 'cubicBezier', 'steps', 'RuntimeModuleError'],
    [
      ['Plain objects (numeric props)', 'yes', 'any numeric property'],
      ['Elements: CSS lengths, %, unitless, colours, custom properties', 'yes', 'hex, rgb(), rgba(), transparent'],
      ['Transform shorthands x y rotate scale scaleX scaleY skewX skewY', 'yes', 'composed in that order'],
      ['Timeline positions (<, >, +=, -=, labels)', 'yes', ''],
      ['repeat / yoyo / reverse / seek / timeScale', 'yes', ''],
      ['SSR / Node import', 'yes', 'no window access at import'],
      ['Web Workers', 'yes', 'ticker falls back to setTimeout without rAF'],
    ],
    "import { use, tween, timeline } from 'motionary/runtime';\nuse();\ntween('.box', { to: { x: 120, opacity: 1 }, duration: 500, ease: 'back-out' });\ntimeline().to('.a', { to: { y: -20 } }).to('.b', { to: { scale: 1.2 } }, '<+=100');"),
  'format-css': R('format-css', 'CSS @keyframes & WAAPI keyframes loader', 'Import CSS @keyframes text or live CSSKeyframesRule objects and Web Animations API keyframes (array or property-indexed) into a runtime timeline.', 2560,
    ['formatCss', 'parseKeyframes', 'fromCssRule', 'fromWaapi', 'toWaapi', 'playKeyframes'],
    [
      ['@keyframes from / to / percentages / selector lists', 'yes', 'duplicate offsets merged, later wins'],
      ['-webkit- / -moz- prefixed @keyframes', 'yes', ''],
      ['animation-timing-function per keyframe', 'yes', 'names, cubic-bezier(), steps()'],
      ['transform lists (translate / rotate / scale / skew)', 'yes', 'tweened as shorthands'],
      ['matrix() / 3D transforms', 'partial', 'switch discretely at the segment midpoint'],
      ['WAAPI array + property-indexed keyframes, offsets, easing', 'yes', 'offsets distributed like the WAAPI'],
      ['composite: add / accumulate', 'no', 'ignored (replace)'],
      ['@property typed interpolation', 'no', 'non-numeric values switch discretely'],
    ],
    "import { use } from 'motionary/runtime';\nimport { formatCss, parseKeyframes, playKeyframes } from 'motionary/runtime/format-css';\nuse(formatCss);\nconst [pulse] = parseKeyframes('@keyframes pulse { from { opacity: .4 } 50% { opacity: 1; transform: scale(1.1) } to { opacity: .4 } }');\nplayKeyframes(document.querySelector('.dot'), pulse, { duration: 1200, repeat: -1 });"),
  'format-motion': R('format-motion', 'Motion / Framer keyframe JSON loader', 'Play Motion / Framer-style { initial, animate, transition } JSON (arrays as keyframes, times, repeatType, springs) with the runtime.', 2560,
    ['formatMotion', 'fromMotion', 'playMotion', 'springEase', 'motionEase'],
    [
      ['initial / animate, arrays as keyframes, times', 'yes', ''],
      ['transition duration / delay (s), ease names + cubic arrays', 'yes', 'easeIn/Out/InOut, circ*, back*, anticipate≈back-in-out'],
      ['repeat (Infinity), repeatType loop / reverse / mirror', 'yes', 'mirror = reverse'],
      ['per-property transitions', 'yes', ''],
      ['type: "spring" (stiffness, damping, mass, bounce + duration)', 'yes', 'simulated into an easing curve'],
      ['variants, gestures (whileHover…), layout animations', 'no', 'out of scope'],
    ],
    "import { use } from 'motionary/runtime';\nimport { formatMotion, playMotion } from 'motionary/runtime/format-motion';\nuse(formatMotion);\nplayMotion(document.querySelector('.card'), { initial: { opacity: 0, y: 40 }, animate: { opacity: 1, y: 0 }, transition: { type: 'spring', stiffness: 180, damping: 14 } });"),
  scroll: R('scroll', 'Scroll scenes', 'Scroll-linked scenes: start / end rules, scrub (direct or smoothed), pin, markers, enter / leave callbacks and per-edge actions for a runtime tween or timeline.', 4608,
    ['scroll', 'scrollScene', 'ScrollScene', 'refreshScenes', 'killScenes', 'allScenes', 'parseEdge', 'resolveRule'],
    [
      ['start / end rules ("top 80%", "center center", "top top+=80", end "+=600")', 'yes', 'keywords, %, px, +=/-= offsets'],
      ['scrub: direct (true) or smoothed (ms)', 'yes', 'drives any runtime tween / timeline'],
      ['pin (fixed in the window, transform inside a scroll container)', 'yes', 'spacer keeps the layout'],
      ['markers', 'yes', 'start / end + viewport lines'],
      ['onEnter / onLeave / onEnterBack / onLeaveBack / onUpdate / onToggle', 'yes', ''],
      ['actions per edge (play pause resume reverse restart reset complete none)', 'yes', 'default "play none none reverse"'],
      ['horizontal scenes, custom scroll containers', 'yes', ''],
      ['snap, nested pins, pinned scroll containers', 'no', 'planned with the smooth module (10.4)'],
      ['SSR', 'yes', 'safe to import; scenes need a window'],
      ['Web Workers', 'no', 'needs the DOM'],
    ],
    "import { use, timeline } from 'motionary/runtime';\nimport { scroll, scrollScene } from 'motionary/runtime/scroll';\nuse(scroll);\nconst tl = timeline({ paused: true }).to('.card', { to: { x: 200, rotate: 8 } });\nscrollScene({ trigger: '.section', start: 'top 80%', end: 'bottom 20%', scrub: 120, pin: true, markers: true, animation: tl });"),
  'format-svg': R('format-svg', 'SVG loader: SMIL playback + path morphing', 'Replay SVG SMIL animations (animate, set, animateTransform, animateMotion) on the runtime timeline, morph between any two paths, and measure paths without the DOM.', 5120,
    ['formatSvg', 'playSmil', 'readSmil', 'morphPath', 'parsePath', 'flattenPath', 'pathLength', 'pointAtLength', 'samplePath', 'smilTime'],
    [
      ['<animate> from / to / by / values, keyTimes, calcMode linear / discrete / spline + keySplines', 'yes', ''],
      ['<set>', 'yes', ''],
      ['<animateTransform> translate / scale / rotate / skewX / skewY', 'yes', ''],
      ['<animateMotion> path / <mpath>, rotate auto / auto-reverse / angle', 'yes', 'paced along the path'],
      ['dur, numeric begin offsets, repeatCount (incl. indefinite), repeatDur, fill freeze', 'yes', ''],
      ['path morphing between any two paths (d attribute or morphPath())', 'yes', 'resampled to N points, start points aligned'],
      ['path parsing incl. relative commands, S/T reflections, arcs', 'yes', 'no DOM needed (SSR / workers)'],
      ['event / syncbase begin (click, a.end), accumulate, additive="sum"', 'no', 'documented gap'],
      ['CSS-animated SVG', 'yes', 'via motionary/runtime/format-css'],
    ],
    "import { use } from 'motionary/runtime';\nimport { formatSvg, playSmil, morphPath } from 'motionary/runtime/format-svg';\nuse(formatSvg);\nconst player = playSmil(document.querySelector('svg'));\nplayer.timeline.timeScale = 0.5;   // scrub / slow down / reverse like any runtime timeline\nconst f = morphPath('M0 0 L100 0 L50 80 Z', 'M50 0 A40 40 0 1 1 49.9 0 Z');\npath.setAttribute('d', f(0.5));"),
  text: R('text', 'Text splitting', 'Split text into characters (grapheme-aware), words and lines for animation while keeping it accessible (aria-label with the full text, pieces hidden from assistive tech).', 2560,
    ['text', 'splitText', 'segment'],
    [
      ['chars (grapheme clusters: emoji, combining marks, CJK)', 'yes', 'Intl.Segmenter when available, code points otherwise'],
      ['words, whitespace preserved', 'yes', ''],
      ['lines (grouped by rendered position)', 'yes', 'wrapped in line spans for flat text; data-line on words inside nested markup'],
      ['nested inline markup (a, em, strong…) kept', 'yes', ''],
      ['accessibility: aria-label + aria-hidden pieces, revert()', 'yes', ''],
      ['--i index custom property for CSS staggers', 'yes', ''],
      ['SSR / workers', 'partial', 'segment() is pure; splitText() needs a DOM'],
      ['right-to-left line detection', 'partial', 'lines by vertical position (works for RTL; bidi runs not reordered)'],
    ],
    "import { use, tween } from 'motionary/runtime';\nimport { text, splitText } from 'motionary/runtime/text';\nuse(text);\nconst { chars } = splitText(document.querySelector('h1'), { type: 'chars,words' });\ntween(chars, { from: { y: '1em', opacity: 0 }, to: { y: '0em', opacity: 1 }, stagger: 30 });"),
  'format-sprite': R('format-sprite', 'Sprite sheets & image sequences', 'Play TexturePacker / Aseprite sprite sheets and numbered image sequences on a canvas or an element background, as runtime timelines (scrubbable).', 3072,
    ['formatSprite', 'parseSpriteSheet', 'gridSheet', 'frameOrder', 'drawFrame', 'spritePlayer', 'imageSequence', 'preloadImages', 'sequencePlayer'],
    [
      ['TexturePacker JSON (hash + array)', 'yes', 'trimmed (spriteSourceSize / sourceSize) and rotated frames'],
      ['Aseprite JSON (hash + array), per-frame duration', 'yes', ''],
      ['Aseprite frameTags: forward / reverse / pingpong / pingpong_reverse', 'yes', ''],
      ['plain grid sheets', 'yes', 'gridSheet(cols, rows, w, h)'],
      ['image sequences (frame_{0001}.webp)', 'yes', 'preloading, cover-fit drawing, scrub via progress'],
      ['multipack (several atlas images)', 'no', 'load each sheet separately'],
      ['Aseprite slices / layers', 'no', 'frames only'],
      ['SSR / workers', 'partial', 'parsing is pure; players need a canvas (OffscreenCanvas works)'],
    ],
    "import { use } from 'motionary/runtime';\nimport { formatSprite, parseSpriteSheet, spritePlayer } from 'motionary/runtime/format-sprite';\nuse(formatSprite);\nconst sheet = parseSpriteSheet(await (await fetch('/slime.json')).json());\nconst img = new Image(); img.src = '/slime.png'; await img.decode();\nspritePlayer(document.querySelector('canvas'), sheet, img, { tag: 'bounce' });"),
  smooth: R('smooth', 'Smooth scrolling', 'Smooth, inertial wheel scrolling (lerp or fixed-duration glide) for the window or any scroll container, anchor links that glide, off under prefers-reduced-motion; real scroll events keep scroll scenes and observers working.', 3584,
    ['smooth', 'smoothScroll', 'SmoothScroll', 'allSmooth'],
    [
      ['wheel / trackpad smoothing (lerp, or duration + ease)', 'yes', 'frame-rate independent'],
      ['window and scroll containers (wrapper), vertical / horizontal', 'yes', ''],
      ['keyboard, scrollbar, find-in-page, assistive tech', 'yes', 'stay native; the smoothed target follows them'],
      ['touch', 'partial', 'native momentum by default; touch: true smooths it'],
      ['anchor links (#id) with offset, focus moved, URL hash kept', 'yes', ''],
      ['nested scrollables, [data-smooth-ignore], ctrl+wheel zoom', 'yes', 'left native'],
      ['prefers-reduced-motion', 'yes', 'disabled while it matches (re-enabled live)'],
      ['scroll scenes / IntersectionObserver / CSS scroll timelines', 'yes', 'real scroll events still fire'],
      ['SSR / workers', 'partial', 'import is safe; smoothScroll() needs a browser'],
    ],
    "import { use } from 'motionary/runtime';\nimport { smooth, smoothScroll } from 'motionary/runtime/smooth';\nuse(smooth);\nconst s = smoothScroll({ lerp: 0.1, anchors: { offset: -64 } });\ns.scrollTo('#pricing');"),
  'format-gif': R('format-gif', 'GIF decoder', 'Decode animated GIFs (own LZW decoder, no DOM) into composited RGBA frames and play / scrub / reverse them on a canvas as a runtime timeline.', 3072,
    ['formatGif', 'decodeGif', 'loadGif', 'lzwDecode', 'animatedImagePlayer'],
    [
      ['GIF87a / GIF89a', 'yes', ''],
      ['global + local palettes, transparency', 'yes', ''],
      ['interlaced frames', 'yes', '4-pass row order'],
      ['disposal 0–3 (none / keep / background / previous)', 'yes', 'background clears to transparent, like browsers'],
      ['frame delays, NETSCAPE2.0 / ANIMEXTS loop count', 'yes', 'delays ≤ 10 ms play at 100 ms, like browsers'],
      ['truncated files', 'partial', 'decodes what is there'],
      ['plain-text extension', 'no', 'ignored (browsers ignore it too)'],
      ['SSR / workers', 'yes', 'decoding is pure; the player needs a (Offscreen)Canvas'],
    ],
    "import { use } from 'motionary/runtime';\nimport { formatGif, loadGif, animatedImagePlayer } from 'motionary/runtime/format-gif';\nuse(formatGif);\nconst gif = await loadGif('/loader.gif');\nconst player = animatedImagePlayer(document.querySelector('canvas'), gif);\nplayer.pause(); player.progress = 0.5; // scrub"),
  'format-apng': R('format-apng', 'APNG loader', 'Split animated PNGs into standalone frame PNGs (decoded by the browser), composite them (dispose / blend) and play them on a canvas as a runtime timeline.', 3072,
    ['formatApng', 'parseApng', 'apngFramePngs', 'decodeApng', 'loadApng', 'animatedImagePlayer'],
    [
      ['acTL / fcTL / fdAT, frame offsets and delays', 'yes', ''],
      ['dispose_op none / background / previous', 'yes', 'first-frame previous → background (spec)'],
      ['blend_op source / over', 'yes', ''],
      ['hidden default image (IDAT not part of the animation)', 'yes', ''],
      ['palette / tRNS / gAMA / iCCP / sRGB / sBIT copied into frames', 'yes', ''],
      ['plain (non-animated) PNG', 'yes', 'one frame'],
      ['decoding', 'yes', "the browser's PNG decoder (createImageBitmap), or your own { decode }"],
      ['SSR / workers', 'partial', 'parsing is pure; decoding needs createImageBitmap (workers OK) or { decode }'],
    ],
    "import { use } from 'motionary/runtime';\nimport { formatApng, loadApng, animatedImagePlayer } from 'motionary/runtime/format-apng';\nuse(formatApng);\nconst anim = await loadApng('/sticker.png');\nanimatedImagePlayer(document.querySelector('canvas'), anim);"),
  'format-webp': R('format-webp', 'Animated WebP loader', 'Split animated WebP files (ANIM / ANMF) into standalone frames (decoded by the browser), composite them (blend / dispose) and play them on a canvas as a runtime timeline.', 3072,
    ['formatWebp', 'parseWebp', 'webpFrameFiles', 'decodeWebp', 'loadWebp', 'animatedImagePlayer'],
    [
      ['VP8X + ANIM + ANMF frames, offsets, durations, loop count', 'yes', ''],
      ['lossy (VP8) with alpha (ALPH) and lossless (VP8L) frames', 'yes', 'lossy + alpha frames get their own VP8X header'],
      ['blending on / off, dispose none / background', 'yes', 'composited on transparent, like browsers'],
      ['still WebP (simple and extended)', 'yes', 'one frame'],
      ['ICC / EXIF / XMP metadata', 'no', 'ignored'],
      ['browsers without WebP decoding', 'no', 'fall back to <img>'],
      ['SSR / workers', 'partial', 'parsing is pure; decoding needs createImageBitmap (workers OK) or { decode }'],
    ],
    "import { use } from 'motionary/runtime';\nimport { formatWebp, loadWebp, animatedImagePlayer } from 'motionary/runtime/format-webp';\nuse(formatWebp);\nconst anim = await loadWebp('/hero.webp');\nconst p = animatedImagePlayer(document.querySelector('canvas'), anim, { speed: 0.5 });"),
  gl: R('gl', 'WebGL2 scene renderer', 'A small WebGL2 renderer with its own API: scene graph, camera, lights, box / plane / sphere / torus, PBR-style materials, shader materials, image and video textures, orbit controls — not a Three.js clone.', 9216,
    ['gl', 'createRenderer', 'Scene', 'Camera', 'GlNode', 'box', 'plane', 'sphere', 'torus', 'standardMaterial', 'unlitMaterial', 'shaderMaterial', 'texture', 'orbitControls', 'frameNode', 'bounds', 'scrubVideo', 'mat4', 'quatFromEuler', 'quatSlerp'],
    [
      ['scene graph: nodes, TRS / matrix, hierarchy, bounds, frameNode()', 'yes', ''],
      ['perspective camera, orbit controls (drag / wheel / pinch / arrow keys)', 'yes', 'auto-rotate off under reduced motion'],
      ['ambient + up to 4 directional / point lights', 'yes', ''],
      ['standard material (metallic-roughness approximation), unlit, shader', 'yes', 'sRGB in/out, Reinhard tone mapping'],
      ['image / canvas / ImageBitmap / raw RGBA textures, mipmaps (power of two)', 'yes', ''],
      ['video textures (MP4 / WebM), scroll-scrubbed video (scrubVideo)', 'yes', 'requestVideoFrameCallback; codecs depend on the browser'],
      ['shadows, normal / occlusion / metallic-roughness maps, IBL', 'no', 'planned work beyond 11.0'],
      ['WebGL1 / no WebGL2', 'no', 'createRenderer() throws a clear error'],
      ['SSR / workers', 'partial', 'math / geometry / scene graph are pure; rendering needs WebGL2 (OffscreenCanvas works)'],
    ],
    "import { use } from 'motionary/runtime';\nimport { gl, createRenderer, Scene, Camera, GlNode, torus, standardMaterial } from 'motionary/runtime/gl';\nuse(gl);\nconst r = createRenderer(canvas);\nconst scene = new Scene();\nscene.add(new GlNode('donut', { geometry: torus(), material: standardMaterial({ color: [0.5, 0.55, 1, 1] }) }));\nr.resize(); r.render(scene, new Camera({ position: [0, 0.5, 3] }));"),
  'format-gltf': R('format-gltf', 'glTF 2.0 / GLB loader', 'Load glTF 2.0 (.gltf with external or data: buffers, .glb) into motionary/runtime/gl nodes: node hierarchy, meshes, PBR metallic-roughness materials, embedded / external images.', 6144,
    ['formatGltf', 'loadGltf', 'parseGlb', 'gltfToNode', 'readAccessor', 'SUPPORTED_EXTENSIONS'],
    [
      ['.gltf (external + data: URI buffers / images) and .glb', 'yes', ''],
      ['scenes, node hierarchy, TRS and matrix transforms', 'yes', ''],
      ['POSITION / NORMAL / TEXCOORD_0, indices, all component types, normalised ints, byteStride', 'yes', 'missing normals computed (flat)'],
      ['primitive modes points / lines / triangles / strips / fans', 'yes', 'strips and fans converted to triangles'],
      ['PBR metallic-roughness factors, base colour texture, emissive, alpha blend, double-sided', 'yes', 'KHR_materials_emissive_strength, KHR_materials_unlit'],
      ['skins, morph targets, animations', 'yes', 'data kept on the nodes / geometry; played by motionary/runtime/gltf-anim (10.8)'],
      ['sparse accessors', 'yes', '10.8'],
      ['Draco / KTX2 (Basis) compression', 'yes', '10.9: through the official decoders (draco3d, Basis Universal transcoder) — motionary/runtime/gltf-decoders + <usa-gl-model>'],
      ['meshopt compression (EXT_meshopt_compression)', 'no', 'files that require it fail with a clear error'],
      ['cameras, KHR_lights_punctual, texture transforms', 'no', 'ignored'],
      ['SSR / workers', 'partial', 'parseGlb / gltfToNode are pure; loadGltf decodes images with createImageBitmap'],
    ],
    "import { use } from 'motionary/runtime';\nimport { gl, createRenderer, Scene, Camera, frameNode } from 'motionary/runtime/gl';\nimport { formatGltf, loadGltf } from 'motionary/runtime/format-gltf';\nuse(gl, formatGltf);\nconst model = await loadGltf('/models/chair.glb');\nconst scene = new Scene().add(model), cam = new Camera();\nframeNode(cam, model);\nconst r = createRenderer(canvas); r.resize(); r.render(scene, cam);"),
  'format-obj': R('format-obj', 'OBJ / MTL loader', 'Load Wavefront OBJ (+ MTL materials and diffuse textures) into motionary/runtime/gl nodes: polygons triangulated, groups, per-material meshes.', 3072,
    ['formatObj', 'loadObj', 'parseObj', 'parseMtl', 'objToNode', 'objMaterial'],
    [
      ['v / vt / vn, faces with any vertex count (fan-triangulated), negative indices', 'yes', ''],
      ['o / g groups, usemtl (one mesh per material), mtllib', 'yes', ''],
      ['MTL Kd, Ks + Ns (→ roughness), Ke, d / Tr, map_Kd (options stripped)', 'yes', ''],
      ['missing normals', 'yes', 'computed (flat)'],
      ['smoothing groups (s), lines (l), free-form curves / surfaces', 'no', 'ignored'],
      ['bump / normal / specular maps, PBR MTL extensions', 'no', 'ignored'],
      ['SSR / workers', 'partial', 'parsing is pure; loadObj fetches files and decodes textures with createImageBitmap'],
    ],
    "import { use } from 'motionary/runtime';\nimport { gl, Scene } from 'motionary/runtime/gl';\nimport { formatObj, loadObj } from 'motionary/runtime/format-obj';\nuse(gl, formatObj);\nconst cube = await loadObj('/models/cube.obj'); // + cube.mtl + textures next to it\nnew Scene().add(cube);"),
  vector: R('vector', 'Lottie + dotLottie player', 'Plays Lottie (bodymovin JSON) and dotLottie (.lottie) files on Canvas 2D with Motionary’s own renderer (no lottie-web code): shapes, gradients, trim paths, masks, track mattes, precomps, images; a runtime timeline you can seek, reverse and scrub.', 12288,
    ['vector', 'evalExpression', 'loadLottie', 'parseDotLottie', 'unzipEntries', 'lottiePlayer', 'renderLottieFrame', 'inspectLottie', 'propValue', 'transformAt', 'trimContours', 'loadLottieImages'],
    [
      ['shape, solid, null, image and precomp layers; parenting; in / out points', 'yes', 'precomp time stretch + time remap'],
      ['transforms: anchor, position (split X / Y, spatial bezier), scale, rotation, skew, opacity', 'yes', ''],
      ['paths, rectangles (rounded), ellipses, stars / polygons, groups', 'yes', ''],
      ['fills (non-zero / even-odd), strokes (caps, joins, dashes)', 'yes', ''],
      ['linear + radial gradient fills / strokes', 'yes', 'highlight length / angle ignored'],
      ['trim paths (individually / simultaneously)', 'yes', ''],
      ['masks: add, subtract, intersect, inverted, opacity', 'yes', ''],
      ['track mattes: alpha, alpha inverted', 'yes', 'luma mattes approximated by alpha'],
      ['keyframes: per-dimension bezier easing, hold keyframes, v4 + v5 files', 'yes', ''],
      ['dotLottie (.lottie): stored + deflate entries, manifest v1 / v2, several animations, embedded images', 'yes', 'deflate needs the native DecompressionStream'],
      ['dotLottie themes + state machines', 'yes', '10.9: motionary/runtime/lottie-state + <usa-dotlottie> (subset)'],
      ['markers → named segments', 'yes', ''],
      ['text layers: fonts by family + style, justification, tracking, line height, fill / stroke, box text (wrapping), source-text keyframes', 'yes', '10.8; system / page fonts (glyph outlines in chars are not used); text animators not supported'],
      ['expressions: time, value, wiggle, loopOut / loopIn (cycle, pingpong, offset, continue), linear / ease, valueAtTime, Math, arithmetic, var / $bm_rt', 'yes', '10.8 subset, own interpreter (no eval; CSP-safe); other expressions keep the keyframed value and are listed by inspectLottie()'],
      ['3D layers, layer effects, merge paths, repeaters', 'no', 'listed by inspectLottie() / el.unsupported'],
      ['dotLottie themes / state machines', 'no', 'planned for 10.9 (subset)'],
      ['SSR / workers', 'partial', 'parsing + unzip are pure; rendering needs a 2D canvas (OffscreenCanvas works)'],
    ],
    "import { use } from 'motionary/runtime';\nimport { vector, loadLottie, lottiePlayer } from 'motionary/runtime/vector';\nuse(vector);\nconst { animation } = await loadLottie('/anim/hero.lottie');\nconst player = lottiePlayer(canvas, animation, { loop: true });\nplayer.play();"),
  rive: P('rive', '@rive-app/canvas', 'Official Rive runtime', 'The official MIT-licensed Rive runtime, used by <usa-rive> to play .riv files (artboards, animations, state machines with inputs). Optional peer dependency: lazy-loaded on first use, never bundled into Motionary.',
    'npm i @rive-app/canvas',
    "import { provideRiveRuntime } from 'motionary/components/widgets';",
    "provideRiveRuntime(() => import('@rive-app/canvas')); // lazy: fetched when the first <usa-rive> mounts",
    '<script src="https://unpkg.com/@rive-app/canvas@2.44.1/rive.js"></script>',
    'https://cdn.jsdelivr.net/npm/@rive-app/canvas@2.44.1/+esm',
    'Install the official runtime next to motionary, then hand <usa-rive> a lazy loader with provideRiveRuntime(() => import(\'@rive-app/canvas\')) before the element mounts — your bundler splits the runtime into its own chunk, fetched only when the first <usa-rive> appears. Without a bundler: load the official rive.js from a CDN before the component bundles (window.rive), use an import map, or set runtime-src on the element. Missing → a clear message in place + usa:runtime-missing.',
    '.riv is Rive’s proprietary binary format with a state-machine runtime; the official runtime is the only faithful player, so Motionary does not reimplement it',
    ['provideRiveRuntime', 'loadRiveRuntime', 'RIVE_PEER', 'RIVE_CDN'],
    [
      ['.riv files: artboards, linear animations', 'yes', 'played by the official runtime'],
      ['state machines + inputs (boolean, number, trigger)', 'yes', 'el.input(name)'],
      ['fit: contain, cover, fill, fitWidth, fitHeight, none', 'yes', ''],
      ['lazy loading, clear error when the runtime is missing', 'yes', 'usa:runtime-missing'],
      ['reduced motion', 'yes', 'no autoplay (first frame)'],
      ['WebGL2 renderer (@rive-app/webgl2)', 'partial', 'pass its URL as runtime-src or provideRiveRuntime(() => import(\'@rive-app/webgl2\'))'],
      ['SSR', 'yes', 'nothing loads until the element mounts in a browser'],
    ],
    "// npm i @rive-app/canvas\nimport { defineRive } from 'motionary/components/widgets';\ndefineRive();\n// <usa-rive src=\"/anim/icon.riv\" state-machine=\"State Machine 1\" autoplay></usa-rive>"),
  physics: R('physics', '2D rigid-body physics', 'A small 2D rigid-body engine written for Motionary (own implementation and API — no Matter.js / Box2D code): circles, boxes and convex polygons, mass from density, restitution, friction, sensors, collision groups, sleeping, distance / spring / pin constraints, pointer drag, a fixed time step on the shared ticker.', 10240,
    ['physics', 'createWorld', 'World', 'Body', 'Constraint', 'collide', 'dragConstraint'],
    [
      ['bodies: circle, box, convex polygon (any winding, made convex)', 'yes', 'concave shapes: split them into convex parts'],
      ['static, dynamic and kinematic bodies; density / mass, inertia, fixed rotation', 'yes', ''],
      ['collisions: sort-and-sweep broad phase, SAT narrow phase, up to 2 contact points', 'yes', 'no continuous collision detection: very fast small bodies can tunnel'],
      ['restitution, Coulomb friction, warm-started accumulated impulses', 'yes', ''],
      ['constraints: distance (rigid or spring with stiffness / damping), pin, pointer drag', 'yes', 'no revolute motors / joint limits'],
      ['sensors, collision categories / masks, collision events, sleeping', 'yes', ''],
      ['fixed time step + accumulator (same result at any frame rate)', 'yes', ''],
      ['SSR / workers', 'yes', 'pure maths; world.run() needs the runtime ticker'],
    ],
    "import { use } from 'motionary/runtime';\nimport { physics, createWorld } from 'motionary/runtime/physics';\nuse(physics);\nconst world = createWorld({ gravity: [0, 980] });\nworld.bounds(600, 400);\nconst ball = world.body({ shape: 'circle', x: 300, y: 40, radius: 20, restitution: 0.7 });\nworld.run(); // steps on the shared ticker"),
  'format-scene': R('format-scene', 'Scene JSON (motionary-scene@1)', 'The versioned motionary-scene@1 format: a JSON description of a 2D physics scene (world, named materials, bodies, constraints, per-body style) — validate, migrate older drafts, load into a physics world and save one back.', 3072,
    ['formatScene', 'SCENE_FORMAT', 'migrateScene', 'validateScene', 'parseScene', 'sceneToWorld', 'worldToScene'],
    [
      ['world: size, gravity, walls (with or without a top), solver iterations', 'yes', ''],
      ['named materials (restitution, friction, density), per-body overrides', 'yes', ''],
      ['bodies: circle / box / polygon, static / kinematic, velocity, angle, sensor, style', 'yes', ''],
      ['constraints: distance / spring / pin between bodies or to a world point', 'yes', ''],
      ['validation (lists every problem, never throws) + parseScene (throws one error)', 'yes', ''],
      ['migration: unversioned scenes and the motionary-scene@0 draft → @1, with a change list', 'yes', ''],
      ['save: worldToScene() (walls made by bounds() are left out)', 'yes', ''],
    ],
    "import { use } from 'motionary/runtime';\nimport { physics } from 'motionary/runtime/physics';\nimport { formatScene, sceneToWorld } from 'motionary/runtime/format-scene';\nuse(physics, formatScene);\nconst { world, bodies } = sceneToWorld(await (await fetch('/scenes/stack.json')).json());\nworld.run();"),
  'drag-snap': R('drag-snap', 'Drag, inertia and snap points', 'Pointer drag along one axis with velocity tracking, inertial throws, rubber-band edges and spring-animated snap points on the shared ticker — the engine of <usa-snap-carousel>, usable for sheets, sliders and pickers (own implementation).', 4096,
    ['dragSnap', 'createDragSnap', 'projectThrow', 'nearestSnap', 'rubberband', 'springStep', 'velocityTracker'],
    [
      ['pointer, touch and pen (Pointer Events), drag threshold, pointer capture, touch-action for the other axis', 'yes', 'one axis per controller (x or y)'],
      ['velocity from the last 100 ms, inertial throw with constant deceleration', 'yes', 'off under reduced motion'],
      ['snap points: nearest to the projected throw, a fast flick moves at least one point', 'yes', ''],
      ['critically damped spring to the snap point (shared ticker)', 'yes', 'instant under reduced motion'],
      ['bounds with rubber-band resistance', 'yes', ''],
      ['clicks inside are kept; the click that ends a drag is swallowed', 'yes', ''],
      ['free 2D dragging, scroll-linked snapping (CSS scroll-snap)', 'no', 'use two controllers / native scroll-snap'],
      ['SSR / workers', 'partial', 'the maths (projectThrow, nearestSnap, rubberband, springStep, velocityTracker) is pure'],
    ],
    "import { use } from 'motionary/runtime';\nimport { dragSnap, createDragSnap } from 'motionary/runtime/drag-snap';\nuse(dragSnap);\nconst track = document.querySelector('.track');\nconst ds = createDragSnap(track, { axis: 'x', snap: [0, -320, -640], onUpdate: (x) => (track.style.transform = `translateX(${x}px)`) });\nds.snapTo(1);"),
  'gltf-anim': R('gltf-anim', 'glTF animation, skinning and morph targets', 'Plays glTF 2.0 animations on models loaded by motionary/runtime/format-gltf: translation / rotation / scale / weights channels with LINEAR, STEP and CUBICSPLINE samplers, skins (4 joints per vertex) and morph targets, deformed on the CPU and re-uploaded to motionary/runtime/gl (own implementation).', 4608,
    ['gltfAnim', 'gltfAnimator', 'gltfClips', 'sampleChannel', 'applyClip', 'deformModel', 'deformGeometry'],
    [
      ['animation channels: translation, rotation, scale, weights', 'yes', 'KHR_animation_pointer is ignored'],
      ['samplers: LINEAR (quaternions slerped), STEP, CUBICSPLINE (Hermite, in / out tangents)', 'yes', ''],
      ['skins: joint hierarchy, inverse bind matrices, JOINTS_0 / WEIGHTS_0 (4 influences)', 'yes', 'CPU skinning; JOINTS_1 / WEIGHTS_1 (8 influences) not used'],
      ['morph targets: POSITION + NORMAL deltas, mesh / node default weights, animated weights', 'yes', 'TANGENT / TEXCOORD / COLOR targets ignored'],
      ['sparse accessors (common for morph targets)', 'yes', 'read by format-gltf'],
      ['clip player: by name or index, loop, speed, seek, update(dt) or the shared ticker', 'yes', 'one clip at a time (no blending)'],
      ['GPU skinning, animation blending / cross-fades, a mesh shared by several skinned nodes', 'no', 'planned work beyond 11.0'],
      ['SSR / workers', 'yes', 'sampling and deformation are pure; play() needs the runtime ticker'],
    ],
    "import { use } from 'motionary/runtime';\nimport { gl } from 'motionary/runtime/gl';\nimport { formatGltf, loadGltf } from 'motionary/runtime/format-gltf';\nimport { gltfAnim, gltfAnimator } from 'motionary/runtime/gltf-anim';\nuse(gl, formatGltf, gltfAnim);\nconst model = await loadGltf('/models/robot.glb');\nconst anim = gltfAnimator(model, { clip: 'walk' });\nanim.play(); // or anim.update(dt) in your own loop"),
  'lottie-state': R('lottie-state', 'dotLottie themes + state machines', 'Resolves Lottie slots with dotLottie themes (Color / Scalar / Vector / Text rules, static or keyframed) and runs a subset of dotLottie state machines (playback states, Event / Numeric / String / Boolean guards, pointer + completion interactions, input / theme / frame actions) for motionary/runtime/vector — own implementation, used by <usa-dotlottie>.', 3584,
    ['lottieState', 'applyTheme', 'ruleProp', 'createStateMachine', 'inspectStateMachine', 'compare'],
    [
      ['themes: slots ("sid") + the animation’s default slot values', 'yes', ''],
      ['theme rules: Color, Scalar, Vector / Position, Text; static value or keyframes; per-animation rules', 'yes', 'Image rules are ignored'],
      ['state machines: initial state, PlaybackState (animation, autoplay, loop, speed, mode, marker segment), GlobalState transitions', 'yes', 'subset'],
      ['guards: Numeric / String / Boolean (Equal, NotEqual, GreaterThan(OrEqual), LessThan(OrEqual)), Event', 'yes', ''],
      ['interactions: PointerDown / Up / Enter / Exit, Click, OnComplete (+ keyboard Enter / Space in <usa-dotlottie>)', 'yes', 'layerName hit-testing is not done: layer-bound interactions fire for the whole canvas'],
      ['actions: Fire, Set*, Toggle, Increment, Decrement, Reset, SetTheme, SetFrame, SetProgress, FireCustomEvent', 'yes', ''],
      ['OpenUrl, blend / tweened transitions, pointer position inputs', 'no', 'OpenUrl is refused on purpose (a file must not navigate the page); listed by inspectStateMachine()'],
      ['SSR / workers', 'yes', 'pure data + logic'],
    ],
    "import { use } from 'motionary/runtime';\nimport { vector, loadLottie } from 'motionary/runtime/vector';\nimport { lottieState, applyTheme, createStateMachine } from 'motionary/runtime/lottie-state';\nuse(vector, lottieState);\nconst { animation, dotLottie } = await loadLottie('/anim/button.lottie');\nconst themed = applyTheme(animation, dotLottie.themes.dark);\nconst sm = createStateMachine(dotLottie.stateMachines.toggle, { onState: (s) => console.log(s.name) });\nsm.fire('tap');"),
  'gltf-decoders': R('gltf-decoders', 'glTF decoder hooks (Draco, KTX2)', 'Lets motionary/runtime/format-gltf load KHR_draco_mesh_compression meshes and KHR_texture_basisu (KTX2) textures through the official decoders — Google draco3d and the Basis Universal transcoder — registered as lazy loaders; Motionary does not reimplement them.', 3072,
    ['gltfDecoders', 'provideGltfDecoder', 'providedDecoders', 'prepareGltf', 'decodeDraco', 'transcodeKtx2', 'DECODER_EXTENSIONS'],
    [
      ['KHR_draco_mesh_compression (POSITION, NORMAL, TEXCOORD_0, JOINTS / WEIGHTS …, indices)', 'yes', 'decoded by the official draco3d decoder (optional peer)'],
      ['KHR_texture_basisu (KTX2 / Basis Universal ETC1S + UASTC)', 'yes', 'transcoded to RGBA8 by the official Basis Universal transcoder (optional peer); GPU-compressed upload is not used'],
      ['lazy loading: a decoder is fetched only when a file needs it', 'yes', 'provideGltfDecoder(kind, loader)'],
      ['missing decoder', 'yes', 'clear error naming the extension, the package and the provide line'],
      ['EXT_meshopt_compression, KHR_mesh_quantization', 'no', 'files that require them fail with a clear error'],
      ['SSR / workers', 'partial', 'Draco decoding works in Node / workers; KTX2 images need ImageData (or the raw RGBA)'],
    ],
    "import { use } from 'motionary/runtime';\nimport { gl } from 'motionary/runtime/gl';\nimport { formatGltf, loadGltf } from 'motionary/runtime/format-gltf';\nimport { gltfDecoders, provideGltfDecoder, prepareGltf } from 'motionary/runtime/gltf-decoders';\nuse(gl, formatGltf, gltfDecoders);\nprovideGltfDecoder('draco', () => import('draco3d'));\nconst model = await loadGltf('/models/robot-draco.glb', { prepare: prepareGltf });"),
  draco3d: P('draco3d', 'draco3d', 'Official Draco decoder (Google)', 'Google’s official Draco geometry decoder (Apache-2.0, WASM / JS), used by motionary/runtime/gltf-decoders for KHR_draco_mesh_compression meshes. Optional peer dependency: lazy-loaded when the first Draco file is opened, never bundled into Motionary.',
    'npm i draco3d',
    "import { provideGltfDecoder } from 'motionary/runtime/gltf-decoders';",
    "provideGltfDecoder('draco', () => import('draco3d')); // lazy: fetched when the first Draco-compressed model loads",
    '<script src="https://www.gstatic.com/draco/versioned/decoders/1.5.7/draco_decoder.js"></script>',
    'https://cdn.jsdelivr.net/npm/draco3d@1.5.7/+esm',
    "Install draco3d next to motionary, then register the lazy loader with provideGltfDecoder('draco', () => import('draco3d')) before a compressed model loads. Without a bundler: load Google’s draco_decoder.js from gstatic (window.DracoDecoderModule) and provideGltfDecoder('draco', () => window.DracoDecoderModule). Missing → a clear error naming the extension and this line.",
    'Draco is a specialised geometry codec with a large reference decoder (WASM); the official decoder is the only safe, maintained implementation, so Motionary does not reimplement it',
    ['provideGltfDecoder'],
    [
      ['Draco meshes in glTF (KHR_draco_mesh_compression)', 'yes', 'decoded by draco3d 1.5.x'],
      ['point clouds', 'no', 'triangle meshes only'],
    ],
    "import { provideGltfDecoder } from 'motionary/runtime/gltf-decoders';\nprovideGltfDecoder('draco', () => import('draco3d'));"),
  'basis-transcoder': P('basis-transcoder', 'basis_transcoder.js', 'Official Basis Universal transcoder (Binomial)', 'Binomial’s official Basis Universal transcoder (Apache-2.0, basis_transcoder.js + .wasm from the basis_universal repository), used by motionary/runtime/gltf-decoders for KHR_texture_basisu (KTX2) textures. Optional: lazy-loaded when the first KTX2 texture is decoded, never bundled into Motionary.',
    'curl -LO https://cdn.jsdelivr.net/gh/BinomialLLC/basis_universal@1.16.4/webgl/transcoder/build/basis_transcoder.js -LO https://cdn.jsdelivr.net/gh/BinomialLLC/basis_universal@1.16.4/webgl/transcoder/build/basis_transcoder.wasm',
    "import { provideGltfDecoder } from 'motionary/runtime/gltf-decoders';",
    "provideGltfDecoder('ktx2', () => import('/vendor/basis_transcoder.js').then((m) => m.default || window.BASIS)); // lazy: fetched with the first KTX2 texture",
    '<script src="https://cdn.jsdelivr.net/gh/BinomialLLC/basis_universal@1.16.4/webgl/transcoder/build/basis_transcoder.js"></script>',
    'https://cdn.jsdelivr.net/gh/BinomialLLC/basis_universal@1.16.4/webgl/transcoder/build/basis_transcoder.js',
    "The transcoder is not published on npm by Binomial: copy basis_transcoder.js + basis_transcoder.wasm (same folder) into your static files, then provideGltfDecoder('ktx2', …) before a KTX2 model loads; or load it from the CDN (window.BASIS) and provideGltfDecoder('ktx2', () => window.BASIS). Missing → a clear error naming the extension and this line.",
    'KTX2 / Basis Universal is a supercompressed GPU texture format with a complex reference transcoder; the official transcoder is the only safe implementation, so Motionary does not reimplement it',
    ['provideGltfDecoder'],
    [
      ['KTX2 textures (ETC1S / UASTC) in glTF (KHR_texture_basisu)', 'yes', 'transcoded to RGBA8'],
      ['standalone .basis / .ktx2 files outside glTF', 'no', 'use the transcoder directly'],
    ],
    "import { provideGltfDecoder } from 'motionary/runtime/gltf-decoders';\nprovideGltfDecoder('ktx2', () => window.BASIS);"),
};

/** `Requires: motionary/runtime + …` */
export const requiresLabel = (ids = []) => (ids.length ? 'Requires: ' + ids.map((id) => PREREQS[id]?.label || id).join(' + ') : '');

/** The four prerequisite items for a component card (install, import + registration order, CDN, minimal example). */
export function prereqFor(item) {
  const mods = (item.requires || []).map((id) => {
    const p = PREREQS[id];
    if (!p) throw new Error(`unknown prerequisite "${id}" on ${item.tag || item.id}`);
    return p;
  });
  if (!mods.length) return null;
  const runtime = mods.filter((m) => m.kind === 'runtime');
  const peers = mods.filter((m) => m.kind === 'peer');
  const install = [...new Set(mods.map((m) => m.install))].join(' && ');
  const imports = [...new Set(mods.flatMap((m) => m.import.split('\n')))];
  const regs = runtime.length ? [`use(${runtime.filter((m) => m.id !== 'core').map((m) => camel(m.id)).join(', ')});`] : [];
  for (const p of peers) regs.push(p.register);
  const define = item.define ? `import { ${item.define} } from 'motionary/components/${item.entry || item.category}';` : '';
  const code = [...imports, define, '', ...regs, item.define ? `${item.define}(); // registers <${item.tag}> — after the prerequisites` : ''].filter((l, i, a) => l || a[i - 1]).join('\n').trim();
  const cdnLines = [...new Set(mods.flatMap((m) => m.cdn.split('\n')))];
  return {
    badge: requiresLabel(item.requires),
    modules: mods.map((m) => m.label),
    install,
    importAndRegister: code,
    order: mods.map((m) => m.order).join(' '),
    cdn: [...cdnLines, '<!-- then the component bundles -->', `<script src="https://unpkg.com/motionary@11/dist/components.umd.js"></script>`, `<script src="https://unpkg.com/motionary@11/dist/widgets.umd.js"></script>`].join('\n'),
    example: item.usage,
    docs: mods.map((m) => DOCS_BASE + m.docs),
  };
}
