import { C } from './make.js';

/**
 * 6.x gallery cards: widgets (motionary/components/widgets) shown in their
 * natural categories, and the 6.x effect packs (one entry each) under "fx".
 * No own category: the gallery categories mirror src/components categories.
 */
/** A 6.x widget card (entry motionary/components/widgets). */
const W = (tag, cat, en, zh, descEn, descZh, tags, usage, demo, controls, extra = {}) => C(tag, cat, en, zh, descEn, descZh, tags, usage, demo, { entry: 'widgets', since: extra.since || '6.2', controls, ...extra });
/** A 6.x effect-pack card: <usa-fx> + register<Pack>Effects() from its own entry. */
const X = (id, reg, en, zh, descEn, descZh, tags, usage, demo, controls, since) => C('usa-fx', 'fx', en, zh, descEn, descZh, tags, usage, demo, { id, define: 'defineFx', reg, controls, since });

const slides = (n, words = ['Aurora', 'Nebula', 'Lagoon', 'Ember', 'Glacier']) => Array.from({ length: n }, (_, i) => `<div class="demo-slide demo-slide-${i % 5}">${words[i % words.length]}</div>`).join('');

export const components = [
  // ---- 6.2 -------------------------------------------------------------
  W('usa-carousel', 'ui', 'Carousel / slider', '轮播 / 滑块',
    '6.2: swipe, drag, arrow keys, dots and autoplay (pauses on hover, focus, off screen). Four transitions — slide, fade, scale and a 3D "cards" coverflow. Reduced motion: slides switch without movement.',
    '6.2：滑动、拖拽、方向键、圆点与自动播放（悬停、聚焦、离开视口时暂停）。四种切换 —— 平移、淡入、缩放与 3D “卡片”封面流。减少动态效果时直接切换。',
    ['carousel', 'slider', 'swipe', 'coverflow', 'autoplay'],
    '<usa-carousel effect="cards" loop autoplay="4000" label="Featured">\n  <img src="a.jpg" alt="…">\n  <img src="b.jpg" alt="…">\n  <img src="c.jpg" alt="…">\n</usa-carousel>',
    `<usa-carousel effect="cards" loop class="demo-carousel">${slides(5)}</usa-carousel>`,
    [{ key: 'effect', values: ['cards', 'slide', 'fade', 'scale'] }]),
  W('usa-tab-bar', 'ui', 'Tabs with animated indicator', '动画指示器标签页',
    '6.2: the indicator stretches from the old tab to the new one (leading edge first) and the panel slides in from the side of travel. Pill, underline, glow or gooey; full tablist keyboard support.',
    '6.2：指示器从旧标签“拉伸”到新标签（前缘先到），面板从移动方向滑入。胶囊、下划线、发光或粘滞四种样式；完整的 tablist 键盘支持。',
    ['tabs', 'indicator', 'segmented', 'underline', 'pill'],
    '<usa-tab-bar indicator="pill">\n  <button>Overview</button>\n  <button>Specs</button>\n  <button>Reviews</button>\n  <div data-panel>…</div>\n  <div data-panel>…</div>\n  <div data-panel>…</div>\n</usa-tab-bar>',
    '<usa-tab-bar indicator="pill" class="demo-tabbar"><button>Overview</button><button>Specs</button><button>Reviews</button><div data-panel>Fast, light, dependency-free.</div><div data-panel>8 kB gzip · Web Components.</div><div data-panel>★★★★★ “Buttery.”</div></usa-tab-bar>',
    [{ key: 'indicator', values: ['pill', 'underline', 'glow', 'gooey'] }]),
  W('usa-disclosure', 'transitions', 'Accordion 2.0', '手风琴 2.0',
    '6.2: native <details> that spring open and closed (height + fade) with an overshooting chevron; one open at a time unless multiple. Find-in-page and keyboard keep working.',
    '6.2：基于原生 <details>，以弹簧动画展开 / 收起（高度 + 淡入），箭头带回弹翻转；默认一次只展开一项（multiple 可多开）。页内查找与键盘操作保持可用。',
    ['accordion', 'details', 'collapse', 'faq', 'spring'],
    '<usa-disclosure variant="cards">\n  <details><summary>Shipping</summary><p>…</p></details>\n  <details><summary>Returns</summary><p>…</p></details>\n</usa-disclosure>',
    '<usa-disclosure variant="cards" class="demo-disclosure"><details open><summary>Is it free?</summary><p>Yes — MIT licensed, no dependencies.</p></details><details><summary>Does it work in React?</summary><p>Every widget is a Web Component, so it works anywhere.</p></details><details><summary>Reduced motion?</summary><p>Panels open instantly when the OS asks for less motion.</p></details></usa-disclosure>',
    [{ key: 'variant', values: ['cards', ''] }]),
  W('usa-stories', 'ui', 'Stories viewer', '快拍（Stories）浏览器',
    '6.2: segmented progress bars, auto-advance, tap left / right to step, press and hold to pause, plus a pause button. Under reduced motion it waits for the user instead of advancing.',
    '6.2：分段进度条、自动前进，点击左 / 右侧切换，长按暂停，并带暂停按钮。减少动态效果时不会自动前进。',
    ['stories', 'instagram', 'progress', 'autoplay', 'tap'],
    '<usa-stories duration="5000" loop>\n  <img src="1.jpg" alt="…">\n  <img src="2.jpg" alt="…">\n</usa-stories>',
    `<usa-stories duration="3000" loop class="demo-stories">${slides(4, ['Day 1', 'Day 2', 'Day 3', 'Day 4'])}</usa-stories>`),
  X('fx-gpu', ['fx-gpu', 'registerGpuEffects'], 'GPU backgrounds', 'GPU 背景',
    '6.2: WebGL2 shaders — fluid (swirls around the pointer), smoke, fire, ink in water and fireflies — with a Canvas 2D fallback when WebGL2 is missing or the context is lost. Renders only while visible, adapts its resolution; one still frame under reduced motion.',
    '6.2：WebGL2 着色器 —— 流体（围绕指针旋转）、烟雾、火焰、水中墨迹与萤火虫；没有 WebGL2 或上下文丢失时回退到 Canvas 2D。仅在可见时渲染并自适应分辨率；减少动态效果时只绘制一帧静态画面。',
    ['webgl2', 'shader', 'fluid', 'smoke', 'fire', 'ink', 'fireflies', 'gpu'],
    '<usa-fx effect="fluid" trigger="load" self class="hero">\n  <h1>Hello</h1>\n</usa-fx>',
    '<usa-fx effect="fluid" trigger="load"><div class="demo-tile demo-gen">GPU</div></usa-fx>',
    [{ key: 'effect', values: ['fluid', 'smoke', 'fire', 'ink', 'fireflies'] }], '6.2'),
  X('fx-nature', ['fx-gpu', 'registerGpuEffects'], 'Sakura, leaves & splash', '樱花、落叶与水花',
    '6.2: cherry-blossom petals and autumn leaves drift down behind the content (Canvas 2D), and splash throws water droplets from the click point.',
    '6.2：樱花花瓣与秋叶在内容后方飘落（Canvas 2D）；splash 从点击处溅起水滴。',
    ['sakura', 'petals', 'leaves', 'autumn', 'splash', 'water', 'particles'],
    '<usa-fx effect="sakura" trigger="load" self class="hero">\n  <h1>Spring</h1>\n</usa-fx>',
    '<usa-fx effect="sakura" trigger="load"><div class="demo-tile demo-gen demo-sky">Seasons</div></usa-fx>',
    [{ key: 'effect', values: ['sakura', 'leaves'] }], '6.2'),
  X('fx-splash', ['fx-gpu', 'registerGpuEffects'], 'Splash click', '水花点击',
    '6.2: a ring plus droplets that arc out of the click point and fall with gravity.',
    '6.2：一圈水环加上从点击处抛出、受重力下落的水滴。',
    ['click', 'splash', 'water', 'droplets'],
    '<usa-fx effect="splash">\n  <button>Splash</button>\n</usa-fx>',
    '<usa-fx effect="splash" trigger="click"><button type="button" class="demo-btn">Splash</button></usa-fx>', undefined, '6.2'),
  // ---- 6.3 -------------------------------------------------------------
  W('usa-toast-stack', 'feedback', 'Toast stack', '通知（Toast）堆叠',
    '6.3: toasts pile up into a collapsed stack (newest in front, older ones peeking behind), fan out on hover or focus, auto-dismiss (paused while hovered) and swipe away. Six positions, a polite live region, stackToast() helper and data-usa-toast triggers.',
    '6.3：通知叠成一摞（最新的在最前，旧的在后方露出），悬停或聚焦时展开成列表；自动消失（悬停时暂停），可滑动关闭。六种位置、礼貌型实时区域、stackToast() 辅助函数与 data-usa-toast 触发器。',
    ['toast', 'notification', 'snackbar', 'stack', 'swipe'],
    '<button data-usa-toast="Saved to your library" data-usa-toast-type="success">Save</button>\n<usa-toast-stack position="bottom-right" duration="4000" max="3"></usa-toast-stack>\n<!-- or from JS: stackToast({ title: \'Done\', message: \'Saved\', type: \'success\' }) -->',
    '<button type="button" class="demo-btn" data-usa-toast="Saved to your library" data-usa-toast-title="Done" data-usa-toast-type="success" data-usa-target="demo-toasts">Show toast</button><usa-toast-stack id="demo-toasts" contained position="bottom-center" duration="3500"></usa-toast-stack>',
    [{ key: 'position', values: ['bottom-center', 'top-center', 'bottom-right', 'top-left'] }], { since: '6.3' }),
  W('usa-modal', 'transitions', 'Modal dialog', '模态对话框',
    '6.3: native <dialog> (top layer, focus trap, Esc) with animated open / close and a blurred backdrop — scale, slide-up, flip, or origin: it grows out of the button that opened it. Focus returns to the opener.',
    '6.3：基于原生 <dialog>（顶层、焦点约束、Esc 关闭），带开合动画与模糊遮罩 —— 缩放、上滑、翻转，或 origin：从触发按钮处“长出来”。关闭后焦点回到触发按钮。',
    ['modal', 'dialog', 'popup', 'backdrop', 'focus-trap'],
    '<button data-usa-open="welcome">Open</button>\n<usa-modal id="welcome" effect="origin" label="Welcome">\n  <h2>Hello 👋</h2>\n  <p>…</p>\n  <button data-usa-close="ok">Got it</button>\n</usa-modal>',
    '<button type="button" class="demo-btn" data-usa-open="demo-modal">Open dialog</button><usa-modal id="demo-modal" effect="origin" label="Welcome"><h3 style="margin:0 0 8px">Hello 👋</h3><p style="margin:0 0 16px">This dialog grew out of the button. Press Esc or click outside to close.</p><button type="button" class="demo-btn" data-usa-close="ok">Got it</button></usa-modal>',
    [{ key: 'effect', values: ['origin', 'scale', 'slide-up', 'flip'] }], { since: '6.3' }),
  W('usa-sheet', 'transitions', 'Drawer / bottom sheet', '抽屉 / 底部面板',
    '6.3: a side sheet from the right, left, top or bottom with a blurred backdrop; the bottom sheet can be dragged down to dismiss and springs back otherwise. Native <dialog> underneath.',
    '6.3：从右、左、上或下方滑出的面板，带模糊遮罩；底部面板可向下拖动关闭，未达阈值时弹回。底层为原生 <dialog>。',
    ['drawer', 'sheet', 'bottom-sheet', 'sidebar', 'drag'],
    '<button data-usa-open="cart">Cart</button>\n<usa-sheet id="cart" side="right" label="Cart">\n  <h2>Your cart</h2>\n  …\n  <button data-usa-close>Close</button>\n</usa-sheet>',
    '<button type="button" class="demo-btn" data-usa-open="demo-sheet">Open drawer</button><usa-sheet id="demo-sheet" side="bottom" label="Share"><h3 style="margin:0 0 10px">Share</h3><p style="margin:0 0 16px">Drag the handle down to dismiss.</p><button type="button" class="demo-btn" data-usa-close>Close</button></usa-sheet>',
    [{ key: 'side', values: ['bottom', 'right', 'left', 'top'] }], { since: '6.3' }),
  W('usa-menu', 'ui', 'Dropdown menu', '下拉菜单',
    '6.3: the list scales (or folds / slides) out of its button and the items cascade in. Full menu keyboard support — arrows, Home / End, Esc, Tab — and outside clicks close it.',
    '6.3：菜单从按钮处缩放（或折叠 / 滑出）展开，菜单项依次落下。完整菜单键盘支持 —— 方向键、Home / End、Esc、Tab —— 点击外部关闭。',
    ['menu', 'dropdown', 'context', 'popover', 'keyboard'],
    '<usa-menu placement="bottom-start" effect="scale">\n  <button>Actions ▾</button>\n  <button>Edit</button>\n  <button>Duplicate</button>\n  <hr>\n  <button>Delete</button>\n</usa-menu>',
    '<usa-menu placement="bottom-start" class="demo-menu"><button class="demo-btn">Actions ▾</button><button>✏️ Edit</button><button>📄 Duplicate</button><hr><button>🗑️ Delete</button></usa-menu>',
    [{ key: 'effect', values: ['scale', 'fold', 'slide'] }], { since: '6.3' }),
  X('fx-text', ['fx-text', 'registerTextEffects3'], 'Text effects 3.0', '文字特效 3.0',
    '6.3: flip-chars (per-character 3D flip), neon-write (a neon sign switching on letter by letter), particle-text (particles assemble into the glyphs) and glitch-text (RGB-split slices). Screen readers get the plain text.',
    '6.3：flip-chars（逐字 3D 翻转）、neon-write（霓虹灯逐字点亮）、particle-text（粒子聚合成文字）与 glitch-text（RGB 分离故障切片）。屏幕阅读器读取原始文本。',
    ['text', 'flip', 'neon', 'particles', 'glitch', '3d'],
    '<usa-fx effect="flip-chars" trigger="enter">\n  <h1>Motionary</h1>\n</usa-fx>',
    '<usa-fx effect="flip-chars" trigger="enter"><h3 class="demo-word">Motionary</h3></usa-fx>',
    [{ key: 'effect', values: ['flip-chars', 'neon-write', 'particle-text', 'glitch-text'] }], '6.3'),
  X('fx-text-loop', ['fx-text', 'registerTextEffects3'], 'Liquid & breathing text', '液态与呼吸文字',
    '6.3: liquid-text ripples the glyphs with an animated SVG displacement filter; font-breathe sends a variable-font weight wave through the text. Both are skipped under reduced motion.',
    '6.3：liquid-text 用动画 SVG 位移滤镜让文字像液体一样波动；font-breathe 让可变字体的字重像呼吸一样逐字起伏。减少动态效果时不播放。',
    ['liquid', 'variable font', 'breathing', 'svg filter', 'loop'],
    '<usa-fx effect="liquid-text" trigger="loop">\n  <h1>Liquid</h1>\n</usa-fx>',
    '<usa-fx effect="font-breathe" trigger="loop"><h3 class="demo-word">Breathe</h3></usa-fx>',
    [{ key: 'effect', values: ['font-breathe', 'liquid-text'] }], '6.3'),
  X('fx-text-trail', ['fx-text', 'registerTextEffects3'], 'Text cursor trail', '文字光标拖尾',
    '6.3: the letters of a word fall off the pointer as it moves over the element (option text, color, spacing).',
    '6.3：指针在元素上移动时，一个单词的字母依次从指针处飘落（可设 text、color、spacing）。',
    ['cursor', 'trail', 'letters', 'pointer'],
    '<usa-fx effect="text-trail" trigger="load" options=\'{"text":"HELLO"}\'>\n  <section class="hero">…</section>\n</usa-fx>',
    '<usa-fx effect="text-trail" trigger="load"><div class="demo-tile demo-trail">Move here</div></usa-fx>', undefined, '6.3'),
  // ---- 6.4 -------------------------------------------------------------
  W('usa-progress-ring', 'feedback', 'Progress ring / bar / gauge', '进度环 / 进度条 / 仪表',
    '6.4: the arc eases to every new value with a little overshoot while the label counts up; ring, bar or semicircle gauge, gradient strokes, indeterminate spinner without a value. role="progressbar", usa:complete at 100%.',
    '6.4：进度弧以轻微回弹缓动到新数值，中间数字同步滚动；环形、条形或半圆仪表，支持渐变描边，无 value 时为不确定进度。role="progressbar"，满 100% 触发 usa:complete。',
    ['progress', 'ring', 'gauge', 'loader', 'percent'],
    '<usa-progress-ring value="72" gradient="#7c5cff,#22d3ee"></usa-progress-ring>\n<usa-progress-ring variant="bar" value="40"></usa-progress-ring>\n<usa-progress-ring variant="semi" value="88"></usa-progress-ring>\n<!-- el.value = 90 animates to the new value -->',
    '<div class="demo-row"><usa-progress-ring value="72" gradient="#7c5cff,#22d3ee" class="demo-pr"></usa-progress-ring><button type="button" class="demo-btn" data-pr-step>+ 20%</button></div>',
    [{ key: 'variant', values: ['ring', 'semi', 'bar'] }], { since: '6.4' }),
  W('usa-odometer', 'text', 'Odometer counter', '里程表计数器',
    '6.4: rolling digit wheels — every digit spins forward to its new value, new digits slide in, locale grouping via Intl.NumberFormat, decimals, prefix / suffix. The accessible name is the formatted number.',
    '6.4：滚轮式数字 —— 每一位向前滚动到新数字，新增位滑入；通过 Intl.NumberFormat 按地区分组，支持小数、前缀 / 后缀。可访问名称即格式化后的数字。',
    ['odometer', 'counter', 'number', 'digits', 'rolling'],
    '<usa-odometer value="1284" locale="en-US" prefix="$"></usa-odometer>\n<!-- el.value = 2048 rolls every digit -->',
    '<div class="demo-row"><usa-odometer value="1284" prefix="$" class="demo-odo"></usa-odometer><button type="button" class="demo-btn" data-odo-step>Count</button></div>',
    [{ key: 'locale', values: ['en-US', 'de-DE', 'hi-IN'] }], { since: '6.4' }),
  W('usa-skeleton-reveal', 'feedback', 'Skeleton → content reveal', '骨架屏 → 内容揭示',
    '6.4: the skeleton is generated from the real content — one bar per rendered text line, blocks for images and marked elements — with one synchronized shimmer (wave, pulse or glow). Remove loading and the bars dissolve top-to-bottom while the content fades in from a blur.',
    '6.4：骨架由真实内容自动生成 —— 每一行文字一条、图片与标记元素各一块 —— 共享同步闪光（wave、pulse、glow）。移除 loading 后骨架自上而下溶解，内容从模糊中淡入。',
    ['skeleton', 'loading', 'shimmer', 'placeholder', 'reveal'],
    '<usa-skeleton-reveal loading variant="wave">\n  <img src="avatar.jpg" alt="" data-skeleton="circle">\n  <h3>Ada Lovelace</h3>\n  <p>…</p>\n</usa-skeleton-reveal>\n<!-- el.loading = false (or el.reveal()) when the data arrived -->',
    '<div class="demo-col"><usa-skeleton-reveal loading class="demo-skr"><div class="demo-skr-row"><span class="demo-skr-av" data-skeleton="circle">AL</span><strong>Ada Lovelace</strong></div><p>First programmer — wrote the first published algorithm for a machine.</p></usa-skeleton-reveal><button type="button" class="demo-btn" data-skr-toggle>Reveal</button></div>',
    [{ key: 'variant', values: ['wave', 'pulse', 'glow'] }], { since: '6.4' }),
  W('usa-star-rating', 'click', 'Star rating 2.0', '评分星 2.0',
    '6.4: the fill follows the pointer (half stars with step="0.5"), a click pops the chosen star with a sparkle burst while the others ripple; stars or hearts; a keyboard slider (arrows, Home / End); readonly mode.',
    '6.4：填充跟随指针（step="0.5" 支持半星），点击时所选星星弹跳并迸出火花，其余星星依次波动；星星或爱心；键盘滑块（方向键、Home / End）；只读模式。',
    ['rating', 'stars', 'review', 'slider', 'feedback'],
    '<usa-star-rating value="3.5" step="0.5" label="Your rating"></usa-star-rating>\n<usa-star-rating value="4" readonly></usa-star-rating>',
    '<usa-star-rating value="3.5" step="0.5" label="Your rating"></usa-star-rating>',
    [{ key: 'icon', values: ['star', 'heart'] }], { since: '6.4' }),
  X('fx-light', ['fx-light', 'registerLightEffects'], 'Dynamic light, lens & shadow', '动态光源、透镜与阴影',
    '6.4: light-follow (a point light with a specular hot spot), refraction (a glass lens that bends and magnifies what is behind it) and pointer-shadow (the pointer is the light — a real-time cast shadow). Fixed lighting under reduced motion.',
    '6.4：light-follow（带高光点的点光源跟随指针）、refraction（玻璃透镜折射并放大其后的内容）与 pointer-shadow（指针即光源 —— 实时投影）。减少动态效果时为固定光照。',
    ['light', 'lens', 'refraction', 'glass', 'shadow', 'pointer'],
    '<usa-fx effect="light-follow" trigger="load">\n  <div class="card">…</div>\n</usa-fx>',
    '<usa-fx effect="light-follow" trigger="load"><div class="demo-tile demo-lens">Light</div></usa-fx>',
    [{ key: 'effect', values: ['light-follow', 'refraction', 'pointer-shadow'] }], '6.4'),
  X('fx-materials', ['fx-light', 'registerLightEffects'], 'Brushed metal & pearl', '金属拉丝与珠光',
    '6.4: brushed-metal (fine lines with an anisotropic sheen that turns with the pointer) and pearlescent (a nacre / holographic film whose hues shift as you move).',
    '6.4：brushed-metal（细密拉丝纹理，各向异性高光随指针转动）与 pearlescent（珍珠 / 镭射薄膜，色相随移动变化）。',
    ['metal', 'brushed', 'pearl', 'holographic', 'material', 'card'],
    '<usa-fx effect="brushed-metal" trigger="load">\n  <div class="card">…</div>\n</usa-fx>',
    '<usa-fx effect="brushed-metal" trigger="load"><div class="demo-tile demo-metal">Titanium</div></usa-fx>',
    [{ key: 'effect', values: ['brushed-metal', 'pearlescent'] }], '6.4'),
  X('fx-god-rays', ['fx-light', 'registerLightEffects'], 'Volumetric light (god rays)', '体积光（耶稣光）',
    '6.4: light shafts fan out from a source point and slowly sweep, drawn additively on Canvas 2D; renders only while visible, one still frame under reduced motion.',
    '6.4：光束从光源点扇形散开并缓慢摆动，以叠加混合绘制在 Canvas 2D 上；仅在可见时渲染，减少动态效果时为一帧静态画面。',
    ['god rays', 'volumetric', 'light', 'background', 'canvas'],
    '<usa-fx effect="god-rays" trigger="load" self class="hero">\n  <h1>Dawn</h1>\n</usa-fx>',
    '<usa-fx effect="god-rays" trigger="load"><div class="demo-tile demo-gen demo-rays">Dawn</div></usa-fx>', undefined, '6.4'),
  // ---- 6.5 -------------------------------------------------------------
  W('usa-milestones', 'timeline', 'Scroll-drawn milestones', '滚动绘制的里程碑',
    '6.5: a progress line grows down the rail as you scroll; each milestone pops its dot and slides its card in when the line reaches it. Alternating sides on wide screens, one column on phones; data-date labels.',
    '6.5：随着滚动，进度线沿轨道向下生长；线到达时，里程碑的圆点弹出、卡片滑入。宽屏左右交替，手机单列；支持 data-date 日期标签。',
    ['timeline', 'milestones', 'roadmap', 'history', 'scroll'],
    '<usa-milestones>\n  <div data-date="2024"><h3>Idea</h3><p>…</p></div>\n  <div data-date="2025"><h3>Beta</h3><p>…</p></div>\n  <div data-date="2026"><h3>Launch</h3><p>…</p></div>\n</usa-milestones>',
    '<usa-milestones layout="left" class="demo-ms"><div data-date="2024"><strong>Idea</strong></div><div data-date="2025"><strong>Beta</strong></div><div data-date="2026"><strong>Launch 🚀</strong></div></usa-milestones>',
    [{ key: 'layout', values: ['left', 'alternate'] }], { since: '6.5' }),
  W('usa-masonry-flow', 'layout', 'Masonry with layout animation', '带布局动画的瀑布流',
    '6.5: a masonry grid whose items glide to their new places (FLIP) on resize, insert / remove, filter(), shuffle() and sort(); hidden items scale out, new ones scale in.',
    '6.5：瀑布流网格，在尺寸变化、增删、filter()、shuffle()、sort() 时项目平滑移动到新位置（FLIP）；隐藏项缩小消失，新项缩放进入。',
    ['masonry', 'grid', 'flip', 'filter', 'shuffle', 'layout'],
    '<usa-masonry-flow min="160" gap="12">\n  <img src="1.jpg" alt="…">\n  <img src="2.jpg" alt="…">\n  …\n</usa-masonry-flow>\n<!-- grid.filter(\'.cats\'), grid.shuffle(), grid.sort((a, b) => …) -->',
    `<div class="demo-col demo-mf-wrap"><div class="demo-row"><button type="button" class="demo-btn" data-mf="shuffle">Shuffle</button><button type="button" class="demo-btn demo-btn-alt" data-mf="filter">Filter</button></div><usa-masonry-flow min="56" gap="8" class="demo-mf">${[60, 90, 50, 80, 70, 45, 95, 55].map((h, i) => `<div class="demo-slide-${i % 5} demo-mf-item${i % 2 ? ' odd' : ''}" style="height:${h}px">${i + 1}</div>`).join('')}</usa-masonry-flow></div>`,
    undefined, { since: '6.5' }),
  W('usa-compare', 'interaction', 'Before / after compare', '前后对比滑块',
    '6.5: drag the handle (or hover with the hover attribute), click to jump, or use the keyboard slider; horizontal or vertical; an intro sweep plays once when it scrolls into view.',
    '6.5：拖动手柄（或加 hover 属性随指针移动），点击跳转，或用键盘滑块操作；支持水平 / 垂直；首次滚入视口时播放一次引导滑动。',
    ['compare', 'before after', 'slider', 'image', 'diff'],
    '<usa-compare labels="Before,After" intro>\n  <img src="before.jpg" alt="Before">\n  <img src="after.jpg" alt="After">\n</usa-compare>',
    '<usa-compare labels="Before,After" intro class="demo-cmp"><div class="demo-cmp-b">RAW</div><div class="demo-cmp-a">GRADED</div></usa-compare>',
    [{ key: 'orientation', values: ['horizontal', 'vertical'] }], { since: '6.5' }),
  W('usa-cube-gallery', 'cards', 'Cube gallery', '立方体画廊',
    '6.5: slides sit on adjacent faces of a 3D cube that turns between them — swipe, arrow keys, buttons or autoplay (pauses on hover / focus / off screen); turn around the Y or X axis.',
    '6.5：幻灯片位于 3D 立方体的相邻面上，立方体在它们之间转动 —— 支持滑动、方向键、按钮或自动播放（悬停 / 聚焦 / 离开视口时暂停）；可绕 Y 轴或 X 轴转动。',
    ['cube', 'gallery', '3d', 'carousel', 'slider'],
    '<usa-cube-gallery autoplay="4000" label="Products">\n  <img src="a.jpg" alt="…">\n  <img src="b.jpg" alt="…">\n  <img src="c.jpg" alt="…">\n</usa-cube-gallery>',
    `<usa-cube-gallery class="demo-cube-g" label="Demo">${slides(4)}</usa-cube-gallery>`,
    [{ key: 'axis', values: ['y', 'x'] }], { since: '6.5' }),
  X('fx-depth', ['fx-3d', 'register3dEffects'], '3D depth, product spin & orbit', '3D 景深、商品旋转与环绕镜头',
    '6.5: depth-stack (layers separate in Z and parallax as the card tilts), product-spin (drag to turn with inertia, idle turntable) and orbit-camera (the camera orbits the 3D layers while you scroll).',
    '6.5：depth-stack（卡片倾斜时各层在 Z 轴分离并产生视差）、product-spin（拖动旋转带惯性，空闲时转台自转）与 orbit-camera（滚动时镜头环绕 3D 图层）。',
    ['3d', 'depth', 'parallax', 'product viewer', '360', 'orbit'],
    '<usa-fx effect="depth-stack" trigger="load">\n  <div class="card">\n    <img data-depth="1" src="bg.png" alt="">\n    <h3 data-depth="3">Title</h3>\n  </div>\n</usa-fx>',
    '<usa-fx effect="depth-stack" trigger="load"><div class="demo-depth3"><span class="demo-d3-a">◆</span><span class="demo-d3-b">3D</span><span class="demo-d3-c">depth</span></div></usa-fx>',
    [{ key: 'effect', values: ['depth-stack', 'product-spin', 'orbit-camera'] }], '6.5'),
  X('fx-depth-flip', ['fx-3d', 'register3dEffects'], 'Thick card flip', '厚卡片翻转',
    '6.5: card-flip-3d turns a card over to its back face (the second child) with a lift and visible thickness; the faces swap aria-hidden.',
    '6.5：card-flip-3d 把卡片翻到背面（第二个子元素），翻转时抬起并显出厚度；正反面会切换 aria-hidden。',
    ['flip', 'card', '3d', 'back face', 'click'],
    '<usa-fx effect="card-flip-3d">\n  <div class="card">\n    <div>Front</div>\n    <div>Back</div>\n  </div>\n</usa-fx>',
    '<usa-fx effect="card-flip-3d"><div class="demo-flip3"><div class="demo-slide-0">Tap me</div><div class="demo-slide-1">Back side ✨</div></div></usa-fx>', undefined, '6.5'),
  X('fx-origami', ['fx-3d', 'register3dEffects'], 'Origami unfold', '折纸展开',
    '6.5: origami unfolds the element panel by panel like folded paper (enter effect; skipped under reduced motion).',
    '6.5：origami 让元素像折纸一样逐片展开（入场效果；减少动态效果时不播放）。',
    ['origami', 'fold', 'paper', 'unfold', 'enter'],
    '<usa-fx effect="origami" trigger="enter">\n  <article>…</article>\n</usa-fx>',
    '<usa-fx effect="origami" trigger="click" options=\'{"panels":4}\'><div class="demo-tile demo-trail">Click to unfold</div></usa-fx>', undefined, '6.5'),
  // ---- 6.6 -------------------------------------------------------------
  W('usa-dock', 'ui', 'macOS-style dock', 'macOS 风格 Dock 栏',
    '6.6: items magnify with a smooth cosine falloff as the pointer moves along the dock, neighbours make room, labels pop above the hovered item and a click bounces it. Keyboard focus magnifies too.',
    '6.6：指针沿 Dock 移动时图标按余弦曲线平滑放大，相邻图标让位，悬停项上方弹出标签，点击时弹跳。键盘聚焦同样会放大。',
    ['dock', 'macos', 'magnify', 'toolbar', 'icons'],
    '<usa-dock magnify="1.9" bounce label="Apps">\n  <button data-label="Finder" aria-label="Finder">🗂</button>\n  <button data-label="Music" aria-label="Music">🎵</button>\n  <a href="/mail" data-label="Mail" aria-label="Mail">✉️</a>\n</usa-dock>',
    '<usa-dock magnify="1.8" bounce class="demo-dock" label="Apps"><button data-label="Files" aria-label="Files">F</button><button data-label="Music" aria-label="Music">♪</button><button data-label="Photos" aria-label="Photos">◎</button><button data-label="Mail" aria-label="Mail">@</button></usa-dock>',
    undefined, { since: '6.6' }),
  W('usa-nav-morph', 'ui', 'Navbar with morphing indicator', '形变指示器导航栏',
    '6.6: the indicator follows the hovered or focused link — stretching from the old one, leading edge first — and settles back on the current page. Underline, pill, blob or dot.',
    '6.6：指示器跟随悬停或聚焦的链接 —— 从旧位置拉伸过去（前缘先到）—— 并回到当前页面。下划线、胶囊、液滴或圆点。',
    ['navbar', 'navigation', 'underline', 'indicator', 'morph'],
    '<usa-nav-morph indicator="underline" label="Main">\n  <a href="/" aria-current="page">Home</a>\n  <a href="/docs">Docs</a>\n  <a href="/blog">Blog</a>\n</usa-nav-morph>',
    '<usa-nav-morph indicator="underline" class="demo-navm" label="Demo"><a href="#c-nav-morph" aria-current="page">Home</a><a href="#c-nav-morph">Docs</a><a href="#c-nav-morph">Blog</a><a href="#c-nav-morph">About</a></usa-nav-morph>',
    [{ key: 'indicator', values: ['underline', 'pill', 'blob', 'dot'] }], { since: '6.6' }),
  W('usa-menu-toggle', 'click', 'Hamburger → close', '汉堡菜单 → 关闭',
    '6.6: the three bars morph into a cross, a back arrow, a minus or a spinning plus-to-cross; a real toggle button with aria-expanded that can open the element it controls (for).',
    '6.6：三条横线变形为叉号、返回箭头、减号或旋转的加号 → 叉号；带 aria-expanded 的真正切换按钮，可通过 for 打开所控制的元素。',
    ['hamburger', 'menu', 'toggle', 'close', 'icon morph'],
    '<usa-menu-toggle for="site-menu" variant="cross" label="Menu"></usa-menu-toggle>\n<nav id="site-menu" hidden>…</nav>',
    '<div class="demo-row"><usa-menu-toggle variant="cross" label="Menu" class="demo-mt"></usa-menu-toggle><usa-menu-toggle variant="arrow" label="Back" class="demo-mt"></usa-menu-toggle><usa-menu-toggle variant="plus-x" label="Add" class="demo-mt"></usa-menu-toggle></div>',
    undefined, { since: '6.6' }),
  W('usa-tip', 'ui', 'Tooltip / popover 2.0', '提示 / 气泡 2.0',
    '6.6: springs out of its trigger with an arrow, flips to stay inside the viewport and shifts along the edge; hover + keyboard focus (Esc closes) or click popovers with rich content.',
    '6.6：带箭头从触发元素处弹出，自动翻转以留在视口内并沿边缘平移；悬停 + 键盘聚焦（Esc 关闭），或点击弹出可含富内容的气泡。',
    ['tooltip', 'popover', 'hint', 'flip', 'a11y'],
    '<usa-tip text="Copied to clipboard" placement="top">\n  <button>Copy</button>\n</usa-tip>\n<usa-tip trigger="click" placement="bottom">\n  <button>Details</button>\n  <div slot="tip"><strong>Pro tip</strong> …</div>\n</usa-tip>',
    '<div class="demo-row"><usa-tip text="Springs out with an arrow" placement="top"><button type="button" class="demo-btn">Hover me</button></usa-tip><usa-tip trigger="click" placement="bottom"><button type="button" class="demo-btn demo-btn-alt">Click me</button><div slot="tip"><strong>Popover</strong><br>Flips to stay on screen.</div></usa-tip></div>',
    [{ key: 'placement', values: ['top', 'bottom', 'left', 'right'] }], { since: '6.6' }),
  X('fx-morph', ['fx-morph', 'registerMorphEffects2'], 'Path morph & stroke draw', '路径补间与描边绘制',
    '6.6: path-morph flows an SVG path between any shapes (resampled points, so different commands morph smoothly); stroke-draw draws every stroke of an SVG, then fades the fills in.',
    '6.6：path-morph 让 SVG 路径在任意形状间流动（重采样点，不同命令也能平滑补间）；stroke-draw 逐条绘制 SVG 描边，然后淡入填充。',
    ['svg', 'morph', 'path', 'stroke', 'draw', 'shape'],
    '<usa-fx effect="path-morph" trigger="loop" options=\'{"paths":["M…","M…"]}\'>\n  <svg viewBox="0 0 100 100"><path d="M…"/></svg>\n</usa-fx>',
    '<usa-fx effect="path-morph" trigger="loop" options=\'{"paths":["M50 8 L61 38 L94 38 L67 58 L78 90 L50 70 L22 90 L33 58 L6 38 L39 38 Z","M50 10 C75 10 90 30 90 50 C90 75 70 90 50 90 C25 90 10 70 10 50 C10 25 30 10 50 10 Z"]}\'><svg viewBox="0 0 100 100" width="120" height="120" class="demo-morph-svg"><path d="M20 20 L80 20 L80 80 L20 80 Z"/></svg></usa-fx>',
    [{ key: 'effect', values: ['path-morph', 'stroke-draw'] }], '6.6'),
  X('fx-blob', ['fx-morph', 'registerMorphEffects2'], 'Liquid blob button', '液态 blob 按钮',
    '6.6: blob-button puts a liquid blob behind the element that wobbles and bulges toward the pointer.',
    '6.6：blob-button 在元素后方放置一个液态 blob，会晃动并朝指针方向鼓起。',
    ['blob', 'button', 'liquid', 'hover', 'svg'],
    '<usa-fx effect="blob-button" trigger="load">\n  <button>Get started</button>\n</usa-fx>',
    '<usa-fx effect="blob-button" trigger="load"><button type="button" class="demo-blob-btn">Get started</button></usa-fx>', undefined, '6.6'),
  X('fx-noise', ['fx-morph', 'registerMorphEffects2'], 'SVG filter reveal & icon swap', 'SVG 滤镜揭示与图标切换',
    '6.6: noise-reveal condenses the element out of SVG turbulence (an SVG-filter transition); icon-swap cycles child icons with a gooey blur-scale-rotate morph.',
    '6.6：noise-reveal 让元素从 SVG 湍流中凝聚成形（SVG 滤镜转场）；icon-swap 以粘稠的模糊 + 缩放 + 旋转变形在子图标间循环切换。',
    ['svg filter', 'turbulence', 'reveal', 'icon', 'swap', 'transition'],
    '<usa-fx effect="noise-reveal" trigger="enter">\n  <img src="hero.jpg" alt="…">\n</usa-fx>\n<usa-fx effect="icon-swap">\n  <button><span>☀️</span><span>🌙</span></button>\n</usa-fx>',
    '<usa-fx effect="noise-reveal" trigger="click"><div class="demo-tile demo-trail">Click: reveal</div></usa-fx>',
    [{ key: 'effect', values: ['noise-reveal', 'icon-swap'] }], '6.6'),
  // ---- 6.7 -------------------------------------------------------------
  W('usa-stepper', 'ui', 'Stepper / wizard', '步骤条 / 向导',
    '6.7: the rail fills toward the current step, finished steps pop a drawn check mark and the current step pulses. Horizontal or vertical; next() / prev() / value.',
    '6.7：进度轨道向当前步骤填充，已完成步骤弹出描边勾选，当前步骤脉冲一次。支持水平或垂直；next() / prev() / value。',
    ['stepper', 'wizard', 'steps', 'progress', 'checkout'],
    '<usa-stepper value="1" label="Checkout">\n  <span>Cart</span>\n  <span>Shipping</span>\n  <span>Payment</span>\n  <span>Done</span>\n</usa-stepper>',
    '<div class="demo-col"><usa-stepper value="1" class="demo-stepper" label="Checkout"><span>Cart</span><span>Ship</span><span>Pay</span><span>Done</span></usa-stepper><div class="demo-row"><button type="button" class="demo-btn" data-st="prev">Back</button><button type="button" class="demo-btn" data-st="next">Next</button></div></div>',
    undefined, { since: '6.7' }),
  W('usa-pagination', 'ui', 'Pagination with sliding ink', '滑动墨迹分页',
    '6.7: the highlight springs to the chosen page (squashing on the way) and page numbers slide in from the direction of travel when the window shifts. Prev / next, ellipses, aria-current.',
    '6.7：高亮块以弹簧动画移到所选页（途中挤压变形），页码窗口移动时数字从移动方向滑入。上一页 / 下一页、省略号、aria-current。',
    ['pagination', 'pages', 'pager', 'ink', 'navigation'],
    '<usa-pagination total="20" page="1" siblings="1"></usa-pagination>',
    '<usa-pagination total="12" page="3" class="demo-pg"></usa-pagination>',
    undefined, { since: '6.7' }),
  W('usa-segmented', 'ui', 'Segmented control', '分段控件',
    '6.7: an iOS-style thumb slides under the chosen segment with a spring and stretches while it travels. A real radio group: arrow keys, Home / End. iOS, pill or outline.',
    '6.7：iOS 风格滑块以弹簧动画移到所选分段，移动途中拉伸。真正的单选组：方向键、Home / End。iOS、胶囊或描边样式。',
    ['segmented', 'radio', 'toggle group', 'ios', 'switcher'],
    '<usa-segmented variant="ios" label="View">\n  <button>Day</button>\n  <button>Week</button>\n  <button>Month</button>\n</usa-segmented>',
    '<usa-segmented variant="ios" class="demo-seg" label="View"><button type="button">Day</button><button type="button">Week</button><button type="button">Month</button><button type="button">Year</button></usa-segmented>',
    [{ key: 'variant', values: ['ios', 'pill', 'outline'] }], { since: '6.7' }),
  W('usa-switch', 'click', 'Toggle switch variants', '开关变体',
    '6.7: four switches — iOS (the thumb stretches while pressed), day / night (sun becomes moon, stars appear), bounce (squash at the end) and liquid (a gooey fill pours in). role="switch", forms, keyboard.',
    '6.7：四种开关 —— iOS（按下时滑块拉长）、昼夜（太阳变月亮、星星出现）、弹跳（到端点时挤压回弹）与液态（粘稠填充倾泻而入）。role="switch"、表单、键盘。',
    ['switch', 'toggle', 'day night', 'dark mode', 'ios'],
    '<usa-switch variant="daynight" name="dark" label="Dark mode"></usa-switch>',
    '<div class="demo-row"><usa-switch variant="ios" checked label="Wi-Fi"></usa-switch><usa-switch variant="daynight" label="Dark mode"></usa-switch><usa-switch variant="bounce" label="Bounce"></usa-switch><usa-switch variant="liquid" label="Liquid"></usa-switch></div>',
    undefined, { since: '6.7' }),
  X('fx-transitions2', ['fx-transitions', 'registerTransitionEffects2'], 'Transitions 2.0: ripple dissolve & liquid wipe', '转场 2.0：涟漪溶解与液体擦除',
    '6.7: ripple-dissolve grows a circle from the pointer; liquid-wipe sweeps a wavy edge across. pageTransition() runs them inside the View Transitions API; crossDocumentTransitions() gives an MPA the same look.',
    '6.7：ripple-dissolve 从指针处扩散圆形揭示；liquid-wipe 以波浪边缘横扫。pageTransition() 在 View Transitions API 内运行它们；crossDocumentTransitions() 让多页站点获得同样效果。',
    ['transition', 'view transitions', 'ripple', 'wipe', 'mpa', 'page'],
    '<usa-fx effect="ripple-dissolve" trigger="click" options=\'{"mode":"in"}\'>\n  <section>…</section>\n</usa-fx>\n<script type="module">\n  import { pageTransition } from \'motionary/components/fx-transitions\';\n  pageTransition(() => render(next), \'liquid-wipe\');\n</script>',
    '<usa-fx effect="ripple-dissolve" trigger="click" options=\'{"mode":"in"}\'><div class="demo-tile demo-trans">Click: ripple dissolve</div></usa-fx>',
    [{ key: 'effect', values: ['ripple-dissolve', 'liquid-wipe', 'camera-dolly'] }], '6.7'),
  X('fx-shatter', ['fx-transitions', 'registerTransitionEffects2'], 'Shatter & mosaic flip', '碎片爆裂与马赛克翻牌',
    '6.7: shatter breaks the element into triangular shards that fly together (in) or apart (out); mosaic-flip turns a grid of tiles over in a diagonal wave.',
    '6.7：shatter 将元素碎成三角形碎片后聚合（in）或飞散（out）；mosaic-flip 让网格瓷砖沿对角线波浪式翻转。',
    ['shatter', 'shards', 'mosaic', 'tiles', 'flip', 'transition'],
    '<usa-fx effect="shatter" trigger="click" options=\'{"mode":"in","pieces":16}\'>\n  <img src="photo.jpg" alt="…">\n</usa-fx>',
    '<usa-fx effect="shatter" trigger="click" options=\'{"mode":"in","pieces":16}\'><div class="demo-tile demo-trans demo-trans-b">Click: shatter in</div></usa-fx>',
    [{ key: 'effect', values: ['shatter', 'mosaic-flip'] }], '6.7'),
  X('fx-curl', ['fx-transitions', 'registerTransitionEffects2'], 'Page curl & camera dolly', '卷页与镜头推拉',
    '6.7: page-curl turns the element like a book page around its left edge with a moving shade; camera-dolly moves it in from depth with a depth-of-field blur.',
    '6.7：page-curl 让元素像书页一样绕左边缘翻动并带移动阴影；camera-dolly 以景深模糊从远处推近。',
    ['page curl', 'book', 'dolly', 'zoom', 'transition'],
    '<usa-fx effect="page-curl" trigger="enter">\n  <article>…</article>\n</usa-fx>',
    '<usa-fx effect="page-curl" trigger="click"><div class="demo-tile demo-trans demo-trans-c">Click: page curl</div></usa-fx>',
    [{ key: 'effect', values: ['page-curl', 'camera-dolly'] }], '6.7'),
];

/** item id → live-demo wiring. */
export const wire = {
  'progress-ring': (stage) => {
    const r = stage.querySelector('usa-progress-ring');
    stage.querySelector('[data-pr-step]')?.addEventListener('click', () => (r.value = r.value >= 100 ? 8 : Math.min(100, (r.value || 0) + 20)));
  },
  odometer: (stage) => {
    const o = stage.querySelector('usa-odometer');
    stage.querySelector('[data-odo-step]')?.addEventListener('click', () => (o.value = o.value + Math.round(37 + Math.random() * 900)));
  },
  'skeleton-reveal': (stage) => {
    const s = stage.querySelector('usa-skeleton-reveal');
    const b = stage.querySelector('[data-skr-toggle]');
    b?.addEventListener('click', () => {
      s.loading = !s.loading;
      b.textContent = s.loading ? 'Reveal' : 'Reload';
    });
  },
  'masonry-flow': (stage) => {
    const g = stage.querySelector('usa-masonry-flow');
    let only = false;
    stage.querySelector('[data-mf=shuffle]')?.addEventListener('click', () => g.shuffle());
    stage.querySelector('[data-mf=filter]')?.addEventListener('click', () => g.filter((only = !only) ? '.odd' : null));
  },
  stepper: (stage) => {
    const s = stage.querySelector('usa-stepper');
    stage.querySelector('[data-st=next]')?.addEventListener('click', () => (s.value >= s.steps.length - 1 ? (s.value = 0) : s.next()));
    stage.querySelector('[data-st=prev]')?.addEventListener('click', () => s.prev());
  },
};
