// The component categories, in display order. Each is a directory under
// src/components/ and a subpath export `motionary/components/<id>`
// (+ `components/<id>.css`). Keep in sync with COMPONENT_CATEGORIES in
// src/components/index.ts (a test checks it); `npm run sync:exports`
// regenerates the package.json exports from this list.
export const CATEGORIES = ['reveal', 'text', 'interaction', 'feedback', 'background', 'transitions', 'physics', 'cards', 'click', 'ui', 'page', 'timeline', 'gesture', 'svg', 'webgl', 'depth', 'layout', 'packs', 'fx'];

// Extra `motionary/components/<name>` entry points (name → source under src/components/).
export const COMPONENT_ENTRIES = { react: 'frameworks/react', vue: 'frameworks/vue', svelte: 'frameworks/svelte', solid: 'frameworks/solid', angular: 'frameworks/angular', jsx: 'frameworks/jsx', lazy: 'lazy', tokens: 'tokens/index', a11y: 'a11y/index', perf: 'perf/index', bridge: 'bridge/index', effects: 'effects/index', widgets: 'widgets/index', fx2: 'fx2/index', 'fx-gpu': 'fx2/gpu', 'fx-text': 'fx2/text3', 'fx-light': 'fx2/light', 'fx-3d': 'fx2/depth3', 'fx-morph': 'fx2/morph2', 'fx-transitions': 'fx2/transitions2', 'fx-weather': 'fx2/weather', 'fx-physics': 'fx2/physics2', 'fx-focus': 'fx2/focus', marketplace: 'marketplace/index', 'fx-music': 'fx2/music', 'fx-chart': 'fx2/chart', 'fx-shop': 'fx2/shop', 'fx-social': 'fx2/social', 'fx-game': 'fx2/game', 'fx-geo': 'fx2/geo', 'fx-form': 'fx2/form', 'fx-ai': 'fx2/ai', engine: 'engine/index', 'fx-festival': 'fx2/festival', 'fx-retro': 'fx2/retro2', 'fx-organic': 'fx2/organic', 'fx-cyber': 'fx2/cyber', 'fx-paper': 'fx2/paper', 'fx-surface': 'fx2/themefx', 'fx-gesture': 'fx2/gesture3', 'fx-spatial': 'fx2/spatial', dsl: 'dsl/index', 'fx-cinema': 'fx2/cinema', 'fx-lottie': 'fx2/lottie', 'fx-genart': 'fx2/genart', 'fx-video': 'fx2/video', 'fx-safe': 'fx2/safemotion', 'fx-perf': 'fx2/perf3', design: 'design/index', native: 'native/index', core: 'core/index', plugins: 'plugins/index', lite: 'lite' };

// 10.1+: `motionary/runtime` and its modules (dist name → source under src/runtime/), each also built as a
// self-registering IIFE for CDNs (dist/runtime.iife.js, dist/runtime/<module>.iife.js).
export const RUNTIME_ENTRIES = { runtime: 'index', 'runtime/format-css': 'format-css', 'runtime/format-motion': 'format-motion', 'runtime/scroll': 'scroll', 'runtime/format-svg': 'format-svg', 'runtime/text': 'text', 'runtime/format-sprite': 'format-sprite', 'runtime/smooth': 'smooth', 'runtime/format-gif': 'format-gif', 'runtime/format-apng': 'format-apng', 'runtime/format-webp': 'format-webp', 'runtime/gl': 'gl', 'runtime/format-gltf': 'format-gltf', 'runtime/format-obj': 'format-obj' };
