// 10.9: per-component entry points — `motionary/widgets/<name>` (one per <usa-*> widget tag, name = tag without "usa-")
// and `motionary/effects/<name>` (one per 6.x+ effect, e.g. motionary/effects/pearlescent). Each entry registers only its
// own tag / effect. Generates src/entries/{widgets,effects}/*.ts, scripts/entries.json (read by rollup, sync-exports,
// gen-manifest, size budgets and the tests) and docs/entry-points.md.
//   node scripts/gen-entries.mjs          write
//   node scripts/gen-entries.mjs --check  fail when anything is out of date
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const rd = (f) => readFileSync(join(ROOT, f), 'utf8');

// 1. what exists: WIDGETS (tag → define) and EFFECT_PACKS (pack → effect names), evaluated from the source
const probe = `import { WIDGETS } from './src/components/widgets/index';
import { EFFECT_PACKS } from './src/components/fx2/index';
const w = {}; for (const [v, m] of Object.entries(WIDGETS)) for (const [tag, fn] of Object.entries(m)) w[tag] = { define: fn.name, since: v };
const e = {}; for (const [k, defs] of Object.entries(EFFECT_PACKS)) e[k] = defs.map((d) => d.name);
console.log(JSON.stringify({ w, e }));`;
const raw = { name: 'raw', setup(b) { b.onResolve({ filter: /\?raw$/ }, (a) => ({ path: join(a.resolveDir, a.path.replace(/\?raw$/, '')), namespace: 'raw' })); b.onLoad({ filter: /.*/, namespace: 'raw' }, (a) => ({ contents: `export default ${JSON.stringify(readFileSync(a.path, 'utf8'))};`, loader: 'js' })); } };
const out = await build({ stdin: { contents: probe, resolveDir: ROOT, loader: 'ts' }, bundle: true, write: false, platform: 'node', format: 'esm', keepNames: true, plugins: [raw], logLevel: 'silent' });
const code = out.outputFiles[0].text;
const tmp = join(ROOT, 'node_modules/.cache/gen-entries-probe.mjs');
mkdirSync(dirname(tmp), { recursive: true });
writeFileSync(tmp, code);
const { execFileSync } = await import('node:child_process');
const { w: WIDGETS, e: PACKS } = JSON.parse(execFileSync(process.execPath, [tmp], { maxBuffer: 16 << 20 }).toString().trim().split('\n').pop());

// 2. where each define / pack lives (import lines of the two index files)
const importsOf = (file) => {
  const m = {};
  for (const [, names, from] of rd(file).matchAll(/import \{([^}]+)\} from '(\.\/[\w/-]+)';/g))
    for (const n of names.split(',').map((x) => x.trim()).filter(Boolean)) m[n.replace(/^type /, '')] = { from, isType: n.startsWith('type ') };
  return m;
};
const wImp = importsOf('src/components/widgets/index.ts');
const fImp = importsOf('src/components/fx2/index.ts');
const packArray = Object.fromEntries([...rd('src/components/fx2/index.ts').split('export const EFFECT_PACKS')[1].split('};')[0].matchAll(/^\s+([\w-]+|'[\w-]+'): (\w+),/gm)].map((m) => [m[1].replace(/'/g, ''), m[2]]));

const entries = [];
// widgets (bundled in motionary/components/widgets until now)
for (const [tag, { define, since }] of Object.entries(WIDGETS)) {
  const src = wImp[define]?.from;
  if (!src) throw new Error(`gen-entries: no import for ${define}`);
  const types = Object.entries(wImp).filter(([n, v]) => v.isType && v.from === src && /Element$/.test(n)).map(([n]) => n);
  entries.push({ kind: 'widget', name: tag.replace(/^usa-/, ''), tag, define, since, module: `components/widgets/${src.slice(2)}`, types, dts: '../components/widgets' });
}
// 10.8+ components that already ship as their own entry: an alias under motionary/widgets/ too
for (const [name, tag, define, dtsEntry] of [['snap-carousel', 'usa-snap-carousel', 'defineSnapCarousel', 'snap-carousel'], ['gl-model', 'usa-gl-model', 'defineGlModel', 'gl-model'], ['dotlottie', 'usa-dotlottie', 'defineDotLottie', 'dotlottie']])
  if (existsSync(join(ROOT, `src/components/widgets/${name}.ts`))) entries.push({ kind: 'widget', name, tag, define, since: null, module: `components/widgets/${name}`, types: [], dts: `../components/${dtsEntry}` });
// effects
const camel = (s) => s.replace(/(^|-)(\w)/g, (_, __, c) => c.toUpperCase());
for (const [pack, names] of Object.entries(PACKS)) {
  const arr = packArray[pack];
  const src = fImp[arr]?.from;
  if (!src) throw new Error(`gen-entries: no import for ${arr}`);
  for (const n of names) entries.push({ kind: 'effect', name: n, pack, array: arr, module: `components/fx2/${src.slice(2)}`, register: `register${camel(n)}` });
}
const dup = entries.map((e) => `${e.kind}/${e.name}`).filter((k, i, a) => a.indexOf(k) !== i);
if (dup.length) throw new Error('gen-entries: duplicate entry names ' + dup.join(', '));

// 3. files
const files = {};
const HEAD = '// Generated by scripts/gen-entries.mjs — do not edit.\n';
for (const e of entries) {
  if (e.kind === 'widget') {
    e.entry = `motionary/widgets/${e.name}`;
    e.src = `src/entries/widgets/${e.name}.ts`;
    files[e.src] = `${HEAD}/** \`${e.entry}\` — registers only <${e.tag}>: \`import { ${e.define} } from '${e.entry}'; ${e.define}();\` */\nexport { ${e.define} } from '../../${e.module}';\n${e.types.length ? `export type { ${e.types.join(', ')} } from '../../${e.module}';\n` : ''}`;
  } else {
    e.entry = `motionary/effects/${e.name}`;
    e.src = `src/entries/effects/${e.name}.ts`;
    files[e.src] = `${HEAD}/** \`${e.entry}\` — the \`${e.name}\` effect alone (${e.pack} pack): \`import { ${e.register} } from '${e.entry}'; ${e.register}();\` then <usa-fx effect="${e.name}"> (defineFx from motionary/components/fx). */\nimport { registerEffects, type EffectDefinition } from '../../components/fx/registry';\nimport { ${e.array} } from '../../${e.module}';\n\n/** The effect definition. */\nexport const effect: EffectDefinition = /*#__PURE__*/ ${e.array}.find((d) => d.name === '${e.name}')!;\n/** Register only this effect (idempotent). */\nexport function ${e.register}(): void {\n  registerEffects([effect]);\n}\nexport { ${e.register} as register };\n`;
  }
}
const list = entries.map(({ kind, name, tag, define, register, entry, src, module, types, dts, pack }) => ({ kind, name, entry, src, ...(tag ? { tag, define, types, dts } : { pack, register }), module }));
files['scripts/entries.json'] = JSON.stringify(list, null, 1) + '\n';
const W = list.filter((e) => e.kind === 'widget'), E = list.filter((e) => e.kind === 'effect');
files['docs/entry-points.md'] = [
  '# Per-component entry points (10.9)',
  '',
  'Load one component instead of a whole group. Every `<usa-*>` widget has its own subpath `motionary/widgets/<name>` (the tag without `usa-`), and every 6.x+ effect has `motionary/effects/<name>`. An entry registers **only its own tag** (or effect) — verified in CI for every entry — and has a fixed gzip budget (`size-budget.json`).',
  '',
  '```js',
  "import { defineToastStack } from 'motionary/widgets/toast-stack';",
  'defineToastStack(); // registers <usa-toast-stack> only',
  "import { registerPearlescent } from 'motionary/effects/pearlescent';",
  "import { defineFx } from 'motionary/components/fx';",
  "registerPearlescent(); defineFx(); // <usa-fx effect=\"pearlescent\">",
  '```',
  '',
  'Notes: an effect entry imports its pack file (the effects of a pack share helpers), so its size is the pack’s, not the whole 6.x set. Runtime-powered widgets still need their prerequisites (`use(…)`, see the Requires badge). The group entries (`motionary/components/widgets`, `/fx2`, `/lite`) are unchanged.',
  '',
  `## Widgets (${W.length})`,
  '',
  '| Tag | Import | Define |',
  '|---|---|---|',
  ...W.map((e) => `| \`<${e.tag}>\` | \`${e.entry}\` | \`${e.define}()\` |`),
  '',
  `## Effects (${E.length})`,
  '',
  '| Effect | Import | Register | Pack |',
  '|---|---|---|---|',
  ...E.map((e) => `| \`${e.name}\` | \`${e.entry}\` | \`${e.register}()\` | ${e.pack} |`),
  '',
].join('\n');

let stale = [];
for (const [f, s] of Object.entries(files)) {
  const p = join(ROOT, f);
  if (!existsSync(p) || readFileSync(p, 'utf8') !== s) stale.push(f);
}
// generated files that should no longer exist
for (const d of ['src/entries/widgets', 'src/entries/effects'])
  if (existsSync(join(ROOT, d))) for (const f of readdirSync(join(ROOT, d))) if (!files[`${d}/${f}`]) stale.push(`${d}/${f} (remove)`);
if (CHECK) {
  if (stale.length) {
    console.error(`gen-entries: ${stale.length} file(s) out of date — run node scripts/gen-entries.mjs\n  ` + stale.slice(0, 10).join('\n  '));
    process.exit(1);
  }
  console.log(`entries current: ${W.length} widgets, ${E.length} effects`);
} else {
  for (const f of stale) {
    if (f.endsWith('(remove)')) { rmSync(join(ROOT, f.replace(' (remove)', ''))); continue; }
    mkdirSync(dirname(join(ROOT, f)), { recursive: true });
    writeFileSync(join(ROOT, f), files[f]);
  }
  console.log(`entries written: ${W.length} widgets, ${E.length} effects (${stale.length} file(s) changed)`);
}
