// Generated by motionary/native (9.8) from: enter: fade-up; click: pop
import 'package:flutter/material.dart';

class MotionView extends StatefulWidget {
  const MotionView({super.key, required this.child, this.index = 0, this.onTap});
  final Widget child;
  final int index;
  final VoidCallback? onTap;
  @override
  State<MotionView> createState() => _MotionViewState();
}

class _MotionViewState extends State<MotionView> with SingleTickerProviderStateMixin {
  late final AnimationController _c = AnimationController(vsync: this, duration: const Duration(milliseconds: 500));
  late final Animation<double> _t = CurvedAnimation(parent: _c, curve: const Cubic(0.22, 1, 0.36, 1));
  double _scale = 1;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    if (MediaQuery.of(context).disableAnimations) { _c.value = 1; return; }
    Future.delayed(Duration(milliseconds: 0 + widget.index * 80), () { if (mounted) _c.forward(); });
  }

  @override
  void dispose() { _c.dispose(); super.dispose(); }

  @override
  Widget build(BuildContext context) {
    Widget w = AnimatedBuilder(
      animation: _t,
      builder: (context, child) => Opacity(
        opacity: 0 + (1 - 0) * _t.value,
        child: Transform.translate(
          offset: Offset(0 * (1 - _t.value), 24 * (1 - _t.value)),
          child: Transform.scale(scale: 1 + (1 - 1) * _t.value, child: child),
        ),
      ),
      child: widget.child,
    );
    return GestureDetector(
      onTapDown: (_) => setState(() => _scale = 0.92),
      onTapUp: (_) => setState(() => _scale = 1),
      onTapCancel: () => setState(() => _scale = 1),
      onTap: widget.onTap,
      child: AnimatedScale(scale: _scale, duration: const Duration(milliseconds: 180), curve: Curves.easeOutBack, child: w),
    );
  }
}
